### ISSUE TITLE
[Rule Tuning] Review for reduction of wildcard usage

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#1023]
All rules should be reviewed to verify usage of wildcards. Elasticsearch added regex support to EQL in https://github.com/elastic/elasticsearch/pull/68791, so where possible and that makes sense, wildcards should be replaced by tighter regex. Wildcards that remain in place should be reviewed to ensure that they are as efficient as possible.

Things to avoid:
* leading wildcards
* unbound wildcards (`*`) when limited wildcards (`?`) would suffice (KQL only)
* wildcards as shortcuts when they can be broken out (such as x86 and x64 paths) (within reason)

**Comment by rw-access** [comment]
Another good use case, we should use groups in some cases like bad extensions:
```
file.name regex~ """.*(jpg|docx|xlsx|pptx)\.exe"""
```

**Comment by rw-access** [comment]
> unbound wildcards (*) when limited wildcards (?) would suffice (KQL only)

EQL will recognize `?` as of 7.11 (per https://github.com/elastic/elasticsearch/pull/65545).

I believe KQL will not recognize `?` as a single character wildcard. Here are some of my findings:
* https://github.com/elastic/kibana/blob/acb7b7726ec038d0ae152e94e3ac1f176c97a8d4/src/plugins/data/common/es_query/kuery/ast/kuery.peg#L189-L198
* https://github.com/elastic/kibana/blob/acb7b7726ec038d0ae152e94e3ac1f176c97a8d4/src/plugins/data/common/es_query/kuery/ast/kuery.peg#L253-L254
* https://github.com/elastic/kibana/blob/acb7b7726ec038d0ae152e94e3ac1f176c97a8d4/src/plugins/data/common/es_query/kuery/node_types/wildcard.ts#L15-L23
