### ISSUE TITLE
[FR] Automatically convert KQL to EQL (or vice versa) with a command

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#1088]
**Is your feature request related to a problem? Please describe.**
EQL solves some problems that KQL can't solve well, like case-insensitivity.

But KQL is more ubiquitous in the product so it's easier to create a rule.
It'd be sweet if we could create the rule initially in KQL, then convert to EQL automagically.

**Describe the solution you'd like**
Use the `kql2eql` functions to automatically convert KQL to EQL.
That logic also needs to be updated for the new EQL operators like `:`.

**Describe alternatives you've considered**
Otherwise, we could just do it manually.
We should also be careful to double check the logic that nothing breaks.

**Comment by austinsonger** [comment]
There has been so many times that I thought how nice it would be to convert KQL to EQL, but didn't think that would be easy. There has been times when I thought it would be nice to convert Lucene to KQL and that would probably be easy.

**Comment by rw-access** [comment]
the lucene part is definitely trickier.

We actually have some conversion logic buried away in the repo https://github.com/elastic/detection-rules/blob/main/kql/kql2eql.py

It needs some updating but is mostly functional. So I was planning on making some updates and exposing this better

**Comment by rw-access** [comment]
I think we've already done this manually, work no longer needed.
