### ISSUE TITLE
[Bug] ThresholdQueryRuleData does not implement parsed_query()

### ISSUE THREAD

**Issue by pepastach** [elastic/detection-rules#1102]
**Describe the bug**
I should start with a confession, that I'm probably using this project differently than it was supposed to. So this is more like a question rather than a bug. What I do is load all AWS rules using `RuleCollection().load_directory()` and then convert the rule to pandas query and create a bunch of Python detectors that we run while processing cloudtrail logs in AWS. I'm basically stealing the queries :) What I found is that 2 rules don't return parsed query. Both of them define a threshold. Then it was quick to notice that the `ThresholdQueryRuleData`class does not implement the `parsed_query()` method and therefore uses the one from `BaseQueryRuleData` which just returns `None`.

It may very well be the expected behavior for the indended use case. I just want to check. 

Thank you. BTW cool project, I love it! 👍

**Comment by rw-access** [comment]
yeah, I realized that ultimately the whole parsed_query and query checking needs to happen on the base class in general, based off language+query, not from.

but `parsed_query()` can still return `None` for Lucene queries, because we don't have a lucene parser. I think that all Lucene rules will be migrated to EQL anyway though.

just curious though, what do you need the `parsed_query` logic for? is `.query` insufficient? I'd love to know more about the use case you have that needs that method

**Comment by pepastach** [comment]
I use `parsed_query()` because it gives me the tree and I can just implement a simple `Walker` which then produces Python code. 

It basically translates a query like this:
```
event.action:(DeleteNetworkAcl or DeleteNetworkAclEntry) and event.dataset:aws.cloudtrail and event.provider:ec2.amazonaws.com and event.outcome:success
```

into Python code:

```python
    def query(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        event.action:(DeleteNetworkAcl or DeleteNetworkAclEntry) and event.dataset:aws.cloudtrail and event.provider:ec2.amazonaws.com and event.outcome:success

        """
        return data.query(
            '(((`event.action` == "DeleteNetworkAcl") | (`event.action` == "DeleteNetworkAclEntry")) & (`event.dataset` == "aws.cloudtrail") &'
            ' (`event.provider` == "ec2.amazonaws.com") & (`event.outcome` == "success"))'
        )
```

**Comment by rw-access** [comment]
Hey @pepastach, we updated some logic in #1136 to fix this issue.
Now, you should be able to do `rule.contents.data.ast` to get the syntax tree for a rule. It'll return None for lucene queries, and it can raise an exception if the syntax is invalid.

**Comment by pepastach** [comment]
Awesome, thank you @rw-access !
