### ISSUE TITLE
[New Rule] Microsoft 365 - User Logged in From Multiple Countries

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1110]
> **NOTE**: This rule could be expanded to Active Directory Domain accounts I believe, but I haven't thought that far out. This rule could probably include google, aws, and okta accounts, but you will probably want a separate rule for each cloud provider.

## Description

A user has been logged in from multiple countries in a short period of time. This could be an indication that the credentials have been compromised.

### Target indexes

`filebeat-*, logs-o365*`

### Platforms

`Microsoft 365`

### Query

```shell
event.action:(UserLoggedIn or MailboxLogin) and event.category:web and event.dataset:o365.audit 
and event.provider:(Exchange or AzureActiveDirectory) and event.outcome:success
```

#### The next part of the logic of the rule will work like this (I think)
> The following ECS fields I haven't used in a query, so I haven't figure out how to make this one flow exactly.

```shell
user.id >> [user] AND source.ip  ==> |source.geo.country_name|  # Canada
user.id >> [user] AND source.ip  ==> |source.geo.country_name|  # United States
                                     | Canada, United States |
```

#### Example with Email Address as user.id
```shell
user.id >> [johndoe@example.com] AND source.ip  ==> |source.geo.country_name|  # Canada
user.id >> [johndoe@example.com] AND source.ip  ==> |source.geo.country_name|  # United States
                                                    | Canada, United States |
```

Timeframe: `10m`
> I've seen this occur usually within a timeframe of 5 mins to 10 mins

### **False Positives**

- VPN
- Proxy

### TAGS

- Azure
- Microsoft 365
- Cloud
- Continuous Monitoring
- Identity and Access
- SecOps

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
| ~~T1078~~  | ~~T1078.001~~ | ~~Valid Accounts~~ | ~~Default Accounts~~   |
| ~~T1078~~  | ~~T1078.002~~ | ~~Valid Accounts~~ | ~~Domain Accounts~~ |
| ~~T1078~~  | ~~T1078.003~~ | ~~Valid Accounts~~ | ~~Local Accounts~~ |
| T1078  | T1078.004    | Valid Accounts | Cloud Accounts     |

**Comment by bm11100** [comment]
This could be best suited for an ML job.
