### ISSUE TITLE
[Rule Tuning] Attempts to Brute Force a Microsoft 365 User Account

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1126]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/microsoft-365/credential_access_microsoft_365_brute_force_user_account_attempt.toml

#### Current
 - Let me know if am I wrong about this... This current rule triggers too easily and too often that I would rather turn this detection off. And there really isn't anything that a company can do about these attempt besides enforcing Multi-factor authentication for the employees.
 -  As a security engineer, I don't understand the rationale of being notified every time that a Brute Force attempt ended up being a failure anyways. 
 - This could also go 9 failure attempts and then 1 success for it be triggered.

```
event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication 
and event.action:UserLoginFailed and event.outcome:failure
```

#### Could potentially expand coverage by:

```
event.action:(UserLoggedIn or MailboxLogin)  
event.provider:(Exchange or AzureActiveDirectory) 
```

**Comment by austinsonger** [comment]
Now this issues is somewhat related to #1127 

## Like if the following happen 9 times, and
```
event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication 
and event.action:UserLoginFailed and event.outcome:failure
```

## then on the 10th try this query happen, is when a detection should be generated.
```
event.action:(UserLoggedIn or MailboxLogin) and event.category:web and event.dataset:o365.audit 
and event.provider:(Exchange or AzureActiveDirectory) and event.outcome:success
```

**Comment by bm11100** [comment]
> Let me know if am I wrong about this... This current rule triggers too easily and too often that I would rather turn this detection off. And there really isn't anything that a company can do about these attempt besides enforcing Multi-factor authentication for the employees.

I can understand your thoughts here, but it is really dependent on the environment using this detection. For some environments its possible it could be noisy, for others it may not be noisy at all. That said, the threshold or exceptions can be tuned on a per environment basis, or the rule can be disabled altogether. A threshold rule is definitely going to have a high variance depending on the company, infrastructure, amount of employees, remote workers, etc.

> As a security engineer, I don't understand the rationale of being notified every time that a Brute Force attempt ended up being a failure anyways.

I think it is useful context to know, but obviously not as actionable as if there was a success at the end. This once again depends on the environment. I think this one just comes down to a matter of opinion. 

> This could also go 9 failure attempts and then 1 success for it be triggered.

I do think having a success at the end would be more actionable. However, we won't know the amount of attempts before the success. I think it is worth revisiting.

**Comment by austinsonger** [comment]
This can also be improved by adding another event action `PasswordLogonInitialAuthUsingPassword`


```
event.dataset:o365.audit and event.provider:(Exchange or AzureActiveDirectory) and event.category:authentication and 
event.action:("UserLoginFailed"  or "PasswordLogonInitialAuthUsingPassword") and event.outcome:failure
```


### References
- https://answers.microsoft.com/en-us/msoffice/forum/all/understanding-failed-login-in-audit-logs/3408f2ae-650f-489c-bc92-9bffbde499dd?page=2
- https://answers.microsoft.com/en-us/msoffice/forum/all/office-365-audit-logs-multiple-failed-login/80d26a71-75c7-494d-acaf-8a3bb695bcd6
- https://blog.jijitechnologies.com/get-office365-services-usage-details
