### ISSUE TITLE
[New Rule] Exfiltration to Source Code Repository

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1131]
## Description

Detects an executable/binary in the System or Linux exfiltrating data to source code (git) website.

> This will expand Elastic Coverage ([Analytic Coverage Comparison | MITRE Cyber Analytics Repository](https://car.mitre.org/coverage/)) by adding
>
> `T1567.001  - Exfiltration Over Web Service -  Exfiltration to Code Repository`

### Target indexes

`winlogbeat-*, logs-windows.*, logs-endpoint.events.*, auditbeat-*` 

### Platforms

`Windows` `linux` 

### Query

```shell
network where network.protocol == "dns" and
	dns.question.name : 
	(
		"*.github.*",
		"*.githubusercontent.*",
		"*.bitbucket.*",
		"*.gitlab.*",
		"*.fogbugz.com.*",
		"*.assembla.*",
		"*.beanstalkapp.*",
		"*.sourceforge.*",
		"*.codebasehq.*",
		"*.sourcerepo.*",
		"*.perforce.*",
		"*.rhodecode.*"
	) and 
	(process.executable :
           ( 
		   "?:\\Users\\*\\AppData\\Local\\Programs\\Git\\bin\\git.exe", 
		   "?:\\Program Files\\Git\\bin\\git.exe",
		   "?:\\Program Files\\Git\\cmd\\git.exe",
		   "?:\\Program Files\\Git\\mingw64\\bin\\git.exe",
		   "?:\\Program Files\\Git\\mingw64\\libexec\\git-core\\git.exe",
		   "?:\\Program Files\\Git\\mingw64\\libexec\\git-core\\headless-git.exe"
           )  and
          process.args : ("git init", "git push", "git remote"))
```

### **False Positives**

- Authorized Software Development Users Pushing Code

  

### MITRE

| Tactic           | Technique ID | Technique Name                         | Sub-Technique Name              |
| ---------------- | ------------ | -------------------------------------- | ------------------------------- |
| Lateral Movement | T1105        | Ingress Tool Transfer                  |                                 |
| Exfiltration     | T1567.001    | Exfiltration Over Web Service          | Exfiltration to Code Repository |
| Exfiltration     | T1048        | Exfiltration Over Alternative Protocol |                                 |

### References

- https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/data/module_source/exfil/Invoke-ExfilDataToGitHub.ps1

**Comment by rw-access** [comment]
@austinsonger any ideas to make this more likely to detect malicious vs benign activity? There probably are some clever ways, but none come to mind for me.

My gut instinct for the rule is that the true positives are around 1e-9 (one in a billion).

In the current state, the idea and pseudocode say  "Exfiltration to Source Code Repository" but it seems like a misnomer and just detects "Git network connection"

**Comment by austinsonger** [comment]
I guess adding something like this to it would improve it a little.

```
process.args in("git init", "git push", "git pull","git remote")
```

**Comment by austinsonger** [comment]
@rw-access I looked a littler closer at `MITRE Exfiltration to Code Repository`

```
Tactic: Exfiltration
ID: T1567
Technique: Exfiltration Over Web Service
ID: T1567.001
Sub-technique: Exfiltration to Code Repository

Adversaries may exfiltrate data to a code repository rather than over their primary command and control channel. 
Code repositories are often accessible via an API (ex: https://api.github.com). 
Access to these APIs are often over HTTPS, which gives the adversary an additional level of protection.

Exfiltration to a code repository can also provide a significant amount of cover to the adversary if it is a popular 
service already used by hosts within the network. 
```

Would this mean that that I should just close this?  

Because from what it says ^above, it looks like MITRE is basically saying it was a "git network connection" using Github API, Gitlab API, Bitbucket API, and etc. There would be a lot of false positives if the organization had any software development, but if it was a organization didn't then it would stand out and more than likely could be malicious.

- I came across this nice article https://www.optimizationcore.com/security/github-exfiltration-indicators-threat-hunt-monitor-block/
