### ISSUE TITLE
[Rule Tuning] Attempt to Deactivate MFA for an Okta User Account

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1160]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/okta/persistence_attempt_to_deactivate_mfa_for_okta_user_account.toml

## Description

- The Current query is to open, there is the possibly of a deactivating MFA for a user triggering false positives when it was not successful. I believe it would be preferred to only be alerted when the attempt was successful. 

```
event.dataset:okta.system and event.action:user.mfa.factor.deactivate and event.outcome:success
```

**Comment by threat-punter** [comment]
@austinsonger - Have you ever seen `event.outcome:failure` logged for `event.action:user.mfa.factor.deactivate`? During my research last year, I could not trigger `event.outcome:failure` for many of the event types listed [here](https://developer.okta.com/docs/reference/api/event-types/#catalog), which is why many of our Okta rules do not include the `event.outcome` field.

**Comment by austinsonger** [comment]
@threat-punter  So I work at a `Managed Services Security Provider - SOC` and we have multiple SIEM vendors that we use for different clients and one of our client, uses AlienVault and I've seen their version of the rule be triggered in AV a couple times, and it doesn't even use `failure` it uses `success`

And I'm pretty sure that AlienVault Event Outcome, is going to be exactly the same thing in elastic.

**AlienVault Rule - Deactivated MFA for Okta user**
![](https://i.imgur.com/TA0MZpq.png)

**Comment by threat-punter** [comment]
Have you observed a false positive or event with `event.action:user.mfa.factor.deactivate` and `event.outcome:failure`?

**Comment by austinsonger** [comment]
No never.

**Comment by rw-access** [comment]
Not to be pedantic, but wouldn't that that change the definition of the rule? Since by title/definition it just says attempt and doesn't discriminate between success and failure.

That's not necessarily good or bad, just worth keeping the original intent in mind

**Comment by threat-punter** [comment]
During my Okta research, there were several event types that I examined where `event.outcome:failure` was not logged, nor did I find documentation to state that this is/is not logged for certain event types. The upshot of that was to exclude `event.outcome:failure` from the query in a number of rules and alert on "attempted" behavior instead. I think we should leave the rule as is until we know for certain whether or not `event.outcome:failure` is logged for the respective event types and that the rule is actually producing false positives or its efficacy can be improved.
