### ISSUE TITLE
[Schema] Add minimum stack version to rule metadata

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#1170]
**Is your feature request related to a problem? Please describe.**
We should always know the minimum stack + schema dependencies for a rule.

Today, we have ECS and beats versions, which default to master. But being explicit is a much more stable approach.

**Approach**
Add TOML like this:
```toml
[metadata]
min_stack_version = "7.13.0"
```

* Keep the field optional for backwards compatibility of existing rules.
    * Make it mutually exclusive with beats/ECS version. We can validate this in marshmallow.
* Use the field in place of beats/ECS. We should have a single `etc/` file to tie all of these versions together
* Add a unit test (not marshmallow validation) to check this for correctness. This essentially means that the rule can be downgraded to that stack version _without any changes_ to the rule hash.
* Eventually, we need to add an EQL function and update the upstream `endgameinc/eql` library to give a list of feature flags, function names, etc. We can tag each feature with a stack version and say
* No restrictions to make the `min_stack_version` the _most_ minimum. Sometimes there are things like bugfixes that we don't have insight to. Trust that it was an intentional choice, but verify that there aren't any issues.

**Comment by brokensound77** [comment]
related to #958
