### ISSUE TITLE
[Rule Tuning] SMB (Windows File Sharing) Activity to the Internet

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#1223]
## Link to rule
https://www.elastic.co/guide/en/security/current/smb-windows-file-sharing-activity-to-the-internet.html

## Description
This rule generates quite a bit of false positives for SMB on 445 to `198.18.0.0/15`
As described in https://www.speedguide.net/ip/198.18.1.0 and https://datatracker.ietf.org/doc/html/rfc2544 `198.18.0.0/15` is a reserved private range, so it should not be included in a rule which is called "* to the Internet"?

## Example Data

![image](https://user-images.githubusercontent.com/6462991/119562776-066e1d80-bda7-11eb-96e6-27cce886e842.png)

**Comment by bm11100** [comment]
Makes sense, I think this rule can be tweaked a bit. Thanks for the suggestion!
