### ISSUE TITLE
[New Rule] AWS KMS CMK Disabled or Scheduled for deletion

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1233]
## Description
Identifies when a CMK is disable or scheduled for deletion.

### Target indexes

`filebeat-*, logs-aws*`

### Platforms

AWS Cloudtrail

### Query

```
event.dataset:aws.cloudtrail and 
event.provider:kms.amazonaws.com and 
event.action: 
    (
    "DisableKey" or
    "ScheduleKeyDeletion"
    ) and 
event.outcome:success
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|        |              |                |                    |
|        |              |                |                    |

### References
- https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html

**Comment by bm11100** [comment]
👍
