### ISSUE TITLE
[New Rule] AWS RDS - Security Group Created

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1238]
## Description
Identifies when a RDS Security Group is Created

### Target indexes

`filebeat-*, logs-aws*`

### Platforms

AWS Cloudtrail

### Query

```
event.dataset:aws.cloudtrail and 
event.provider:rds.amazonaws.com and 
event.action: 
    (
    "CreateDBSecurityGroup"
    ) and 
event.outcome:success
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|        |              |                |                    |
|        |              |                |                    |

### References
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBSecurityGroup.html

**Comment by bm11100** [comment]
I like to keep creations and deletions as separate rules since they are opposite events. I think we could split this one into two rules.

**Comment by austinsonger** [comment]
@bm11100 Okay I will split into separate issues.
