### ISSUE TITLE
[New Rule] AWS S3 - Bucket Encryption Disabled

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1239]
## Description

Identifies when a S3 bucket default encryption is disabled. Data at rest is no longer encrypted when stored.

### Target indexes

`filebeat-*, logs-aws*`

### Platforms

AWS Cloudtrail

### Query

```
event.dataset:aws.cloudtrail and 
event.provider:s3.amazonaws.com and 
event.action: 
    (
    "DeleteBucketEncryption"
    ) and 
event.outcome:success
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|        |              |                |                    |
|        |              |                |                    |

### References
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucketEncryption.html

**Comment by bm11100** [comment]
We actually have this API covered in the `AWS S3 Bucket Configuration Deletion` rule.

**Comment by austinsonger** [comment]
My Bad
