### ISSUE TITLE
[New Rule] AWS S3 - ACL Exposed object or bucked added

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1241]
## Description

Identifies when a S3 object or bucket ACL has been modified. This ACL exposes the object or bucket to anyone.

### Target indexes

`filebeat-*, logs-aws*`

### Platforms

AWS Cloudtrail

### Query

```
event.dataset:aws.cloudtrail and 
event.provider:s3.amazonaws.com and 
event.action: 
  (
    "PutBucketAcl" or
    "PutObjectAcl"
    ) and 
    aws.cloudtrail.request_parameters.text : AccessControlPolicy.AccessControlList.Grant*.Grantee.URI and
event.outcome:success
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|        |              |                |                    |
|        |              |                |                    |

### References
- https://auth0.com/blog/fantastic-public-s3-buckets-and-how-to-find-them/
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketAcl.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectAcl.html

**Comment by austinsonger** [comment]
@bm11100 

Any advice on how to add the following to this query:

`*AllUsers*` or `*AuthenticatedUsers*`

- https://auth0.com/blog/fantastic-public-s3-buckets-and-how-to-find-them/#More-Ways-to-Detect-a-Public-Bucket-Using-the-CLI

**Comment by bm11100** [comment]
It looks like the event .provider should be `s3.amazonaws.com`.  I would need to test the Grantee info to see what it looks like from our side.
