### ISSUE TITLE
[Rule Tuning] Attempts to Brute Force a Microsoft 365 User Account

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#1243]
## Link to rule

https://www.elastic.co/guide/en/security/current/attempts-to-brute-force-a-microsoft-365-user-account.html

## Description

This rule seems to trigger a lot on the logon error `UserAccountNotFound`. Imho, considering the scope of this rule and considering the `user.name` seems unexistant and `user.id` seems always "Not Available" (the audit log never mentions the user name for which a logon was detected when the user account was not found...), I think UserAccountNotFound should be excluded from this rule.

Managing this rule is rather complex and imho, I think it could be worth splitting it up with different settings, depending on the logon error. (Of course I can / could do this myself, but I wanted to inquire community animo for this..)

Some examples of logon errors for this rule:

![image](https://user-images.githubusercontent.com/6462991/120332997-8e947b80-c2ef-11eb-96be-4695be7ec4ac.png)

Are wrong entitlements (EntitlementGrantsNotFound) ,wrong auth requirements (UserStrongAuthEnrollmentRequired) or invalid reply to (InvalidReplyTo) applicable logon errors for a "brute force" detection rule (just to name a few)?

**Comment by austinsonger** [comment]
@willemdh Can you show a json payload.

This is common issue with M365(O365) with all SIEM tools from my experience, but with Office 365 you may see successful login events when the user actually fails to log in. M365(O365)uses Azure Active Directory to authenticate users, so you could theorize that the user accounts are not synchronized. which is causing this.

**Comment by austinsonger** [comment]
Opps. My bad, I forgot that this rule has the following:

```
event.action:UserLoginFailed
event.outcome:failure
```

But what I said above still stands.
> M365(O365)uses Azure Active Directory to authenticate users, so you could theorize that the user accounts are not synchronized. which is causing this.

And if you are also using "AD Connect," it could be running into the same issue.

Maybe this could work for you.


```
event.dataset:o365.audit and event.provider:AzureActiveDirectory and
event.category:authentication and event.action:UserLoginFailed and (not o365.audit.LogonError : UserAccountNotFound) and
event.outcome:failure
```

@bm11100 you have any suggestions?

**Comment by willemdh** [comment]
Thanks @austinsonger Ill have a look at your suggestions, could take some time.

**Comment by bm11100** [comment]
Yeah I think we could just exclude the errors we want to suppress by using a `not`. Also, do you find the threshold value of 10 being enough / not enough? Should we increase the threshold value or modify the lookback time at all?

**Comment by willemdh** [comment]
Well, its not a small topic, and I dont have much time, but lets say the rule query and thresholds could be finetuned.. Most of the signals are from users who have wrong or outdated crdedentials on their smartphone. I have been thinking about splitting up the rule based on user agent and on logon error. The threshold is ok for windows endpoints but too noisy for smartphones.

**Comment by austinsonger** [comment]
Relates to Issue #1126
Relates to PR #1163

**Comment by willemdh** [comment]
Hello, Considering there apparently is some movement in this I freed up some time and 'improved' the query for now to:

`event.dataset: o365.audit and event.provider: AzureActiveDirectory and event.category: authentication and  event.action: UserLoginFailed and not ( o365.audit.LogonError : UserAccountNotFound or o365.audit.LogonError : EntitlementGrantsNotFound or o365.audit.LogonError : UserStrongAuthEnrollmentRequired or o365.audit.LogonError : UserStrongAuthClientAuthNRequired or o365.audit.LogonError : InvalidReplyTo ) and event.outcome:failure`

This reduces the noice with about 66 % for me.

So these are the Logon Errors left after the above change (in descending order)

- InvalidUserNameOrPassword
- IdsLocked
- UserDisabled
- DeviceAuthenticationRequired
- DeviceAuthenticationFailed
- UserDisabled
- OnPremisePasswordValidationAuthenticationAgentTimeout
- OnPremisePasswordValidatorErrorOccurredOnPrem
- UserUnauthorized
- UnauthorizedClientDoesNotMatchRequest

Kindly let me know what's your opinion on my updated query and on the leftover Logon Errors.

**Comment by bm11100** [comment]
@willemdh, I appreciate all the additional context you are providing as I don't have an M365 environment setup with real world data. 

If we combined the multiple PR's, the query would look like below : 
```
event.dataset:o365.audit and event.provider:(AzureActiveDirectory or Exchange) and
  event.category:authentication and event.action:(UserLoginFailed or PasswordLogonInitialAuthUsingPassword) and
  not o365.audit.LogonError:(UserAccountNotFound or EntitlementGrantsNotFound or UserStrongAuthEnrollmentRequired or
                             UserStrongAuthClientAuthNRequired or InvalidReplyTo) and event.outcome:failure
```
I think the override scenario could be good on a per environment basis. There is an [issue](https://github.com/elastic/kibana/issues/86306) I put in related to the override settings, but I think there is still work that can be done to improve that.

Can you run this query, which also includes `Exchange` and `PasswordLogonInitialAuthUsingPassword` and see if that increases the noise in any way? 

I'm happy to adjust the current rule to include these changes.

**Comment by bm11100** [comment]
PR https://github.com/elastic/detection-rules/pull/1251

**Comment by willemdh** [comment]
@bm11100 Just out of curiosity, where do the `Exchange` `event.provider` logs come from? Because I cannot find those anywhere? Same with `PasswordLogonInitialAuthUsingPassword`.. So as far as your question 

> see if that increases the noise in any way?

 goes, I can tell you that it does not seem to matter.. But I really like to find out what data I might be missing..

**Comment by willemdh** [comment]
Hmm ok, I see now where my confusion comes from.. I haven't been thinking too much about it, but my first thought was that I'd rather have a separate rule for Exchange and for AzureActiveDirectory. 

But after testing the query a bit more, I noticed we have zero logs with `event.action` `PasswordLogonInitialAuthUsingPassword`..

Which makes me think something is not right with the query.

**Comment by austinsonger** [comment]
@willemdh sorry I just saw this, it is a specific use case so you may not see the alerts in your environment. I'll explain the entire thing later on today. When I have more time.

**Comment by jdieguezbean** [comment]
Hi guys, can someone tell me what is the field in o365 logs related to event.category?
