### ISSUE TITLE
[FR] Detection Rule support for Geo Queries/Filters

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#127]
**Is your feature request related to a problem? Please describe.**
Currently, most Beat modules focused on security take advantage of enriching data with Geo information. However, there doesn't appear to be a way to create detection rules that can take advantage of the [geo queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html) that Elasticsearch offers. These queries are powerful for detecting geocentric events. 

A common use case for geo location is unauthorized access by a remote party. You can use access logs to detect access via a location that would be physically impossible to get to within a specific time frame.

**Describe the solution you'd like**
It would therefore be nice if detection rules could support these queries. So that geocentric events could be detected.

**Describe alternatives you've considered**
The only other alternative I can think of it to use an advanced watcher, which offers the possibility to use geo queries. This option while okay, doesn't integrate with the rest of the SIEM interface and its features.

**Comment by threat-punter** [comment]
Hi @BenB196. Thanks for reaching out with your use case on detecting "fast/impossible travel" events. I'm doing some digging and will get back to you on this.

**Comment by threat-punter** [comment]
@BenB196 - It's not possible to accomplish the fast travel detection use case today by using a KQL or EQL query in Elasticsearch to calculate the distance between two geographic coordinates. There are a couple of options for you to explore though that **can** help you achieve this use case.

1. Create a [transform](https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-overview.html) on your authentication events data to calculate things like the distance between a user's two authentication events and their speed of travel between the two locations.
    - Once you've done that, you can create a custom detection rule (using data from the transform's destination index) to alert when a user authenticates in more than one location within 1 hour and the locations are more than 100km apart. This is just an example. I've included what an example alert could look like in Elastic Security.

![image](https://user-images.githubusercontent.com/56409778/104753269-fbc6bc00-5714-11eb-9ad2-e86ffb1c0077.png)

2. If you're a Platinum user, you have access to Machine Learning and can create an [anomaly detection](https://www.elastic.co/guide/en/machine-learning/7.10/create-jobs.html) job to detect authentication activity that is unusual compared to the behavior of the population.

**Comment by BenB196** [comment]
@threat-punter Thanks for the options. Unfortunately I don't have access to ML currently. 

Would you be able to provide an example of transform you would use? I looked into this, but wasn't able to determine the best logic to use for it. (I can take this qustion over to the forums if preferred)

**Comment by threat-punter** [comment]
@BenB196 - Your transform will look similar to the example below. There are some values that will be unique to your environment such as the query to match the authentication events that you're interested in analyzing, the frequency that the transform runs, the `calendar_interval`, and the destination index.

I've included `POST _transform/_preview` in the example so that you can tweak the example, run it in Kibana Dev Tools, and preview the results.

I hope this helps. Please let me know if you have any questions.

```json
POST _transform/_preview
{
  "source": {
    "index": "filebeat-*",
    "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "bool": {
            "filter": [
              {
                "bool": {
                  "should": [
                    {
                      "match_phrase": {
                        "event.category": "authentication"
                      }
                    }
                  ],
                  "minimum_should_match": 1
                }
              },
              {
                "bool": {
                  "filter": [
                    {
                      "bool": {
                        "should": [
                          {
                            "exists": {
                              "field": "source.ip"
                            }
                          }
                        ],
                        "minimum_should_match": 1
                      }
                    },
                    {
                      "bool": {
                        "should": [
                          {
                            "exists": {
                              "field": "source.geo.location"
                            }
                          }
                        ],
                        "minimum_should_match": 1
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ],
      "should": [],
      "must_not": [
        {
          "match_phrase": {
            "data_stream.dataset": "windows.security"
          }
        }
      ]
    }
    }
  },
  "dest" : { 
    "index" : "impossible_travel"
  },
  "pivot": {
    "group_by": {
      "user": { 
        "terms": {
          "field": "source.user.full_name"
        }
      },
      "@timestamp": {
        "date_histogram": {
          "field": "@timestamp",
          "calendar_interval": "1h"
        }
      }
    },
    "aggregations": { 
      "total_distinct_locations_over_time": {
        "cardinality": {
          "field": "source.geo.location"
        }
      },
      "session_details": {
        "scripted_metric": {
          "init_script": "state.docs = []", 
          "map_script": """ 
            Map span = [
              '@timestamp':doc['@timestamp'].value,
              'source.geo.location':doc['source.geo.location'].value
            ];
            state.docs.add(span)
          """,
          "combine_script": "return state.docs;", 
          "reduce_script": """ 
            def all_docs = [];
            for (s in states) {
              for (span in s) {
                all_docs.add(span);
              }
            }
            all_docs.sort((HashMap o1, HashMap o2)->o1['@timestamp'].millis.compareTo(o2['@timestamp'].millis));
            def size = all_docs.size();
            def min_time = all_docs[size-2]['@timestamp'];
            def max_time = all_docs[size-1]['@timestamp'];
            def first_src = all_docs[size-2]['source.geo.location'];
            def second_src = all_docs[size-1]['source.geo.location'];
            def lat2 = second_src.lat; 
            def lon2 = second_src.lon;
            def lat = first_src.lat;
            def lon = first_src.lon;
            def dx = 71.5*(lon2-lon);
            def dy = 111.3*(lat2-lat);
            def distance = Math.round(Math.sqrt((dx*dx) + (dy*dy)));
            def duration = (max_time.millis - min_time.millis)/1000;
            def ret = new HashMap();
            if (distance > 0 && duration > 0) {
            def speed = Math.round(distance/duration);
            ret['speed_kmh'] = speed;
            } else {
              def speed = 0;
              ret['speed_kmh'] = speed;
            }
            ret['one_before_last_login'] = min_time;
            ret['last_login'] = max_time;
            ret['duration_in_seconds_between_last_logins'] = duration;
            ret['total_logins_over_time'] = size;
            ret['distanceInKM_between_last_logins'] = distance;
            return ret;
          """
        }
      }
    }
  }
}
```

cc @jamesspi
