### ISSUE TITLE
Incorrect field used to identify Console login events

### ISSUE THREAD

**Issue by starssec** [elastic/detection-rules#1289]
**Describe the bug**
We ingest Cloudtrail logs using filebeat with the applicable module into our on-prem ELK stack. Using **_privilege_escalation_root_login_without_mfa.toml_** as an example

event.action:ConsoleLogin is invalid - should be:

aws.cloudtrail.event_type: AwsConsoleSignIn

**To Reproduce**
1. search your filebeat-* index (or index housing cloudtrail data) and search event.action:ConsoleLogin
2. change the search term to aws.cloudtrail.event_type:AwsConsoleSignIn
3. Observe the difference in results

**Expected behavior**
Query should return AwsConsoleSignin events

**Comment by bm11100** [comment]
Hey @starssec, can you provide a little more detail? All the AWS rules are using the `event.action` field, do any of the AWS rules work for you? What version of Filebeat are you using? Are you using [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-event.html)? What stack version are you on? Our other cloud rules also use `event.action`, are you using those as well and do they work? You are correct that `aws.cloudtrail.event_type` populates, but so should the relevant `event.action`, see below. 

![image](https://user-images.githubusercontent.com/56412096/122107432-1185fd80-cde9-11eb-8cd0-4aa27b243ac1.png)

**Comment by starssec** [comment]
Hi @bm11100 - I haven't been through all the rules yet, but any using event.action certainly don't work for us as they only seem to contain "Management"

We are on stack version 7.9.3
Our SecEng team tell me we are indeed using ECS
Filebeat version is 7.10.0

**Comment by starssec** [comment]
![image](https://user-images.githubusercontent.com/85959535/122178639-a8e96000-ce7e-11eb-9e91-537cca38dc8e.png)

**Comment by bm11100** [comment]
Are you sure you are using Elastic's AWS module and not a third party? Are you implementing ECS yourselves? If so, it may be a bad conversion on your end. Could you attach your Filebeat configuration (redact any sensitive info) so I can take a look at what you have configured?

**Comment by starssec** [comment]
Is this enough?

**filebeat.yml**

filebeat.inputs:
    filebeat.config.modules:
      # Glob pattern for configuration loading
      path: ${path.config}/modules.d/*.yml
      # Set to true to enable config reloading
    #reload.enabled: true
      # Period on which files under path should be checked for changes
    #  reload.period: 10s
    output.logstash:
      hosts: xxxxxxx:5045

**aws.yml**
module: aws
      cloudtrail:
        enabled: true
        var.queue_url: https://sqs.xxxxxxx.amazonaws.com/xxxxxxxx/xxxxxxxxxxx-queue
        var.access_key_id: xxxxxxxxx
        var.secret_access_key: /xxxxxxxxxx
        var.visibility_timeout: 300s
        var.api_timeout: 120s
        var.endpoint: amazonaws.com

**Comment by bm11100** [comment]
Thanks. I'm not seeing this in any of my clusters, so I'm going to spin up the exact versions you are using and test. In the meantime, where is the Filebeat running that is producing these results? Is it running within the AWS account on a VM? Or is it running elsewhere?

**Comment by starssec** [comment]
on a VM within the AWS account. We have multiple accounts within our AWS org. Each account is configured to send cloudtrail events to an S3 bucket within one of those child accounts whose sole purpose is to receive logs. We then extract the logs using filebeat and ship it to our centralised stack on premise over a vpn

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
