### ISSUE TITLE
[New Rule] Possible Illicit Consent Grant Attack via Azure-Registered Application

### ISSUE THREAD

**Issue by threat-punter** [elastic/detection-rules#129]
## Description

> An adversary may create an Azure-registered application that requests access to data such as contact information, email, or documents. The attacker then tricks an end user into granting that application consent to access their data either through a phishing attack, or by injecting illicit code into a trusted website.
>
> After the illicit application has been granted consent, it has account-level access to data without the need for an organizational account. Normal remediation steps, like resetting passwords for breached accounts or requiring Multi-Factor Authentication (MFA) on accounts, are not effective against this type of attack, since these are third-party applications and are external to the organization.
Source: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide

This rule identifies when a user grants permissions to an Azure-registered application or when an administrator grants tenant-wide permissions to an application.

The screenshot below shows what it looks like when an application requests permissions.

![image](https://user-images.githubusercontent.com/56409778/90187924-d9043600-dd77-11ea-9cf7-86d25f062a94.png)

The screenshot below shows what it looks like when an application requests permissions for an organization.

![image](https://user-images.githubusercontent.com/56409778/90188136-2b455700-dd78-11ea-8be4-badfb4ffc0b5.png)

## Query

```
event.module:azure and event.dataset:azure.activitylogs and event.category:Administrative and azure.activitylogs.operation_name:"Consent to application"
```

## Required Info

- **Eventing Sources:**

`filebeat-*`

- **Target Operating Systems:**

- **Platforms**

Azure

- **Target ECS Version:** 1.5.0
- **New fields required in ECS for this?** No
- **Related issues or PRs** None

## Optional Info
- **References:**
  - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide
  - https://adsecurity.org/wp-content/uploads/2019/08/2019-BlackHat-US-Metcalf-Morowczynski-AttackingAndDefendingTheMicrosoftCloud.pdf

## Example Data

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/56409778/90188361-92fba200-dd78-11ea-8b1f-da1a6e57e814.png">

**Comment by hrvojep** [comment]
@threat-punter great post. Should we call out specifically that filebeat needs to have o365 module enabled for this work?

**Comment by threat-punter** [comment]
Thank you for your comment, @hrvojep 🙂

I believe that the `Consent to application` event is logged in both the Azure activity log _and_ the O365 audit logs. I will double check that is the case and include that information in the rule accordingly (that the Azure or O365 module is required to use this rule).

I will update this issue once I've confirmed. Cheers

**Comment by threat-punter** [comment]
I need to verify whether `Consent to application` is logged in _both_ the Azure and O365 logs when an administrator or individual user grants consent to an application. I'll do this when my test environment is available.

Note the `.` in the O365 event, but not the Azure event above.

```
event.module:o365 and event.dataset:o365.audit and event.category:web and event.code:AzureActiveDirectory and o365.audit.Operation:"Consent to application." and event.outcome:success
```

<img width="2547" alt="image" src="https://user-images.githubusercontent.com/56409778/91890675-165c3500-ec4d-11ea-85e1-faf729109852.png">
