### ISSUE TITLE
[New Rule] Parent Process PID Spoofing

### ISSUE THREAD

**Issue by Samirbous** [elastic/detection-rules#1337]
## Description

Identifies Parent Process Spoofing from commonly abused vectors (i.e. maldoc, scripts, lolbins, untrusted PE).

https://blog.didierstevens.com/2017/03/20/"

![image](https://user-images.githubusercontent.com/64742097/125622744-0fc490f1-649c-47c9-8b68-bfd50d2c93c9.png)

### Tested ECS Version
x.x.x

**Comment by eklike100** [comment]
@Samirbous Thanks a lot!
