### ISSUE TITLE
[Rule Tuning] detection-rules/rules/linux/defense_evasion_hidden_file_dir_tmp.toml

### ISSUE THREAD

**Issue by eklike100** [elastic/detection-rules#1355]
[Existing](https://github.com/elastic/detection-rules/blob/414d32027632a49fb239abb8fbbb55d3fa8dd861/rules/linux/defense_evasion_hidden_file_dir_tmp.toml) rule has KQL errors with regex due to which cannot use it. Please take a look or convert to eql with correct regex.

**Comment by rw-access** [comment]
Hey @eklike100, looks like that rule is written in Lucene.

Can you explain more the problem you're getting?

**Comment by eklike100** [comment]
yeah my bad it's Lucene. The query is not matching any valid results. Something wrong with regex I guess. How this query will look like in eql? I've seen many old rules are getting converted into eql.

**Comment by rw-access** [comment]
If you can give me some specific examples where it's not matching what it's supposed to, we can help figure out what's wrong.

If this were written in EQL, it would look something like
```python
process where event.type in (start, process_started) and
  process.working_directory in ("/tmp", "/var/tmp", "/dev/shm") and
  process.args regex~ """\.[a-zA-Z0-9_\-][a-zA-Z0-9_\-\.]{1,254}""" and
  not process.name in (ls, find)
```

**Comment by eklike100** [comment]
I have require data with attached fields: 
![image](https://user-images.githubusercontent.com/62762611/126182311-0be1c9ee-20fb-460c-ad1c-ee2ec3e30a01.png)
![image](https://user-images.githubusercontent.com/62762611/126182362-426dfe8f-a904-45b1-b41d-1b6349762bc7.png)
![image](https://user-images.githubusercontent.com/62762611/126182423-bd2755ac-63a3-40ba-8fae-736ef1c48a47.png)
![image](https://user-images.githubusercontent.com/62762611/126182575-07cd3cc5-c0b4-4d91-8a6a-be715a0120d4.png)
Will skip `process.working_directory` for now and same I edited query as:
```
event.category:process AND event.type:(start or process_started)  AND
  process.args:/\.[a-zA-Z0-9_\-][a-zA-Z0-9_\-\.]{1,254}/ AND
  NOT process.name:(ls or find)
```
Still I have no results even after regenerating the same logs. I tried your eql query as well but that has error too. 
![image](https://user-images.githubusercontent.com/62762611/126183481-4559dc85-b255-458a-a219-1a665e8fd518.png)

**Comment by rw-access** [comment]
Sorry that was a "rough" query. I forgot quotes
```python
process where event.type in ("start", "process_started") and
  process.working_directory in ("/tmp", "/var/tmp", "/dev/shm") and
  process.args regex~ """\.[a-zA-Z0-9_\-][a-zA-Z0-9_\-\.]{1,254}""" and
  not process.name in ("ls", "find")
```

But also, in your JSON query, it doesn't like `"""` inside `"""`, and that's the error you see. To get around that error you can't use `"""` style strings in EQL and have to use `"` style and escape all the slashes `\` -> `\\`
```python
process where event.type in ("start", "process_started") and
  process.working_directory in ("/tmp", "/var/tmp", "/dev/shm") and
  process.args regex~ "\\.[a-zA-Z0-9_\\-][a-zA-Z0-9_\\-\\.]{1,254}" and
  not process.name in ("ls", "find")
```

**Comment by eklike100** [comment]
yes it worked! Thank you for detailed kind answer :)

**Comment by rw-access** [comment]
I created a PR https://github.com/elastic/detection-rules/pull/1357 to convert this rule to EQL
