### ISSUE TITLE
[Rule Tuning] Credential Acquisition via Registry Hive Dumping

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1366]
## Description

Need to add HIVENightmare to this.

Identifies when a non-admin being able to read registry hives.

### Target indexes

`filebeat-*, logs-windows.*`

### Target Operating Systems

Windows 10 and 11

### Query

```
process where event.type in ("start", "process_started") and
  process.pe.original_file_name == Cmd.Exe and
  process.args : ("*\\config\\SAM", "\\*\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*\\*")
```

### References
- https://doublepulsar.com/hivenightmare-aka-serioussam-anybody-can-read-the-registry-in-windows-10-7a871c465fa5 
- https://github.com/GossiTheDog/HiveNightmare

**Comment by austinsonger** [comment]
@rw-access @threat-punter

**Comment by rw-access** [comment]
Looks like this overlaps with these rules and possibly more:
* [Credential Acquisition via Registry Hive Dumping](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_dump_registry_hives.toml)
* [NTDS or SAM Database File Copied](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_copy_ntds_sam_volshadowcp_cmdline.toml)

I think the best place for any new logic is to extend **Credential Acquisition via Registry Hive Dumping**. We could add some references to that rule and extend the logic if you have ideas.

**Comment by austinsonger** [comment]
I was originally going to create a issue to tune the rule **Credential Acquisition via Registry Hive Dumping**, I was unsure if it would fit. It would probably change the name.

**Comment by austinsonger** [comment]
@rw-access  
 Could elastic security somehow check if  `BUILTIN\\Users` has ability to access `C:\windows\system32\config\sam`

**Comment by austinsonger** [comment]
@rw-access this has expanded now. This doesn't just effect SAM hives. It also effect SYSTEM, and SECURITY hives.

**Comment by austinsonger** [comment]
Just keeping this active.
