### ISSUE TITLE
[New Rule] SAM Hive Copying by esentutl.exe

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1375]
## Description

Identifies when esentutl.exe copies SAM Hive to a temporary directory.

### Target indexes

`winlogbeat-*, "logs-endpoint.events.*, "logs-windows.*`

### Platforms

Windows

### Query

`esentutl.exe /y /vss %SystemRoot%/system32/config/SAM /d %temp%/SAM`

```
process where event.type in ("start", "process_started") and
  process.name : ("cmd.exe", "esentutl.exe") and 
  process.args : ("*/y*", "*/vss*", "*/d*")  
  process.args : ("*/system32/config/SAM*", "*/SAM*")
```

### **False Positives**
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|        |              |                |                    |
|        |              |                |                    |

### References
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.002/T1003.002.md

**Comment by threat-punter** [comment]
@austinsonger what do you think about adding `esentutl.exe` to [NTDS or SAM Database File Copied](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_copy_ntds_sam_volshadowcp_cmdline.toml)?
