### ISSUE TITLE
[Rule Tuning] Add Packetbeat Index to Network Rules

### ISSUE THREAD

**Issue by peasead** [elastic/detection-rules#14]
## Description
The Packetbeat Index needs to be added to network SIEM rules. 

Filebeat was originally used to take advantage of the [Zeek](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-zeek.html) and [Suricata](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-suricata.html) network data modules. While Packetbeat is not a full-fledged protocol analyzer like Zeek, or even Suricata, it can act as a data source for these rules.

## Example Data
Existing Index designation: `index = ["filebeat-*"]`
Suggested Index designation: `index = ["filebeat-*", "packetbeat-*"]`

**Comment by Ares3266** [comment]
You probably also want to add the `auditbeat-*` index as well. We dont run pacletbeat on every host, but we do run auditbeat, which is actually where we get more hits (thanks so its socket module)

See [this](https://twitter.com/3266miles/status/1276527633099096065) tweet

**Comment by peasead** [comment]
Thanks for the feedback, @Ares3266 

I agree, adding `auditbeat-*` is a great idea. I can circle back on this with a fresh Issue/PR in the future, or please feel free to contribute it.

**Comment by rw-access** [comment]
@Ares3266 I created #35 for adding auditbeat to the rules
