### ISSUE TITLE
[New Rule] Obtaining Insecurely Stored Credentials 

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#1411]
## Description

Identifies when insecurely stored credentials are obtained.

### Target indexes

`winlogbeat-*, logs-windows*`

### Query

```
process where event.type in ("start", "process_started") and
  (process.name : "reg.exe" or process.pe.original_file_name == "reg.exe") and
  process.args : ("query","HKLM","REG_SZ","HKCU","*/f","*/t","*/s" ) or
  (process.name : ("pwsh.exe", "powershell.exe", "powershell_ise.exe") or process.pe.original_file_name in
      ("pwsh.exe", "powershell.exe", "powershell_ise.exe") and
	process.args : 
                      (
                       "*Get-UnattendedInstallFile*",
                       "*Get-Webconfig*",
                       "*Get-ApplicationHost*",
                       "*Get-SiteListPassword*",
                       "*Get-CachedGPPPassword*",
                       "*Get-RegistryAutoLogon*"))
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | -------------- | ------------------ |
|Credential Access|T1552.002|Unsecured Credentials|Credentials in Registry|
|        |              |                |                    |

### References
- https://d00mfist.gitbooks.io/ctf/content/cleartext-passwords.html
- http://www.exumbraops.com/penetration-testing-102-windows-privilege-escalation-cheatsheet
- https://powersploit.readthedocs.io/en/latest/

**Comment by austinsonger** [comment]
Just keeping it open.

**Comment by willemdh** [comment]
Ping
