### ISSUE TITLE
[New Rule] Windows Logs Cleared using Wevtutil.exe 

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#1465]
## Description
Adversaries may clear Windows Event Logs to hide the activity of an intrusion. Windows Event Logs are a record of a computer's alerts and notifications. There are three system-defined sources of events: System, Application, and Security, with five event types: Error, Warning, Information, Success Audit, and Failure Audit.

This is a very specific and simple rule that looks for threat actors using the Wevtutil utility to clear Windows event logs on a system by using the cl option for clear. 

There should be no false positives when it comes to this detection and it should be very rare for this event to fire as clearing event logs manually is not a normal occurrence. 

### Target indexes
logs-\*, filebeat-\*, winlogbeat-*

### Additional requirements
Ensure Sysmon is installed with Process Create events being logged or that Windows Event ID 4688 (Process Creation) with process command line enabled is logging to detect this activity.

### Target Operating Systems
Windows

### Tested ECS Version
7.14.0

## Optional Info

It is worth noting that a threat actor could also write custom tooling that utilizes the Windows API to delete Windows Event Logs but it is my understanding that Event ID 1102 will still be logged indicating the logs were cleared although I have not taken time to test this yet.

### Query

```sql
process where process.name : "wevtutil.exe" and process.args : "*cl*"
```

### References

https://attack.mitre.org/techniques/T1070/001/

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil

## Example Data

```json

{
  "_index": ".ds-logs-endpoint.events.process-default-2021.08.26-000001",
  "_type": "_doc",
  "_id": "pQHZl3sBDd5RH2lHVtIy",
  "_score": 1,
  "_source": {
    "agent": {
      "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208",
      "type": "endpoint",
      "version": "7.14.0"
    },
    "process": {
      "Ext": {
        "ancestry": [
          "YWMxNjI5MGQtY2RkMC00M2RmLWFlMDItODY5ZmQ2ZDliMjA4LTEwMzYtMTMyNzQ0ODcwOTQuNTgxODcyMDAw",
          "YWMxNjI5MGQtY2RkMC00M2RmLWFlMDItODY5ZmQ2ZDliMjA4LTM5NjAtMTMyNzQ0NzA2NjIuNjU0NjQzMDA="
        ],
        "code_signature": [
          {
            "trusted": true,
            "subject_name": "Microsoft Windows",
            "exists": true,
            "status": "trusted"
          }
        ]
      },
      "parent": {
        "args": [
          "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
          "-WorkingDirectory",
          "~"
        ],
        "name": "pwsh.exe",
        "pid": 1036,
        "args_count": 3,
        "entity_id": "YWMxNjI5MGQtY2RkMC00M2RmLWFlMDItODY5ZmQ2ZDliMjA4LTEwMzYtMTMyNzQ0ODcwOTQuNTgxODcyMDAw",
        "command_line": "\"C:\\Program Files\\PowerShell\\7\\pwsh.exe\" -WorkingDirectory ~",
        "executable": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
      },
      "pid": 8448,
      "entity_id": "YWMxNjI5MGQtY2RkMC00M2RmLWFlMDItODY5ZmQ2ZDliMjA4LTg0NDgtMTMyNzQ4MTM3ODguODM0NTU2NDAw",
      "executable": "C:\\Windows\\System32\\wevtutil.exe",
      "args": [
        "C:\\Windows\\system32\\wevtutil.exe",
        "cl",
        "security"
      ],
      "code_signature": {
        "trusted": true,
        "subject_name": "Microsoft Windows",
        "exists": true,
        "status": "trusted"
      },
      "pe": {
        "original_file_name": "wevtutil.exe"
      },
      "exit_code": 0,
      "name": "wevtutil.exe",
      "args_count": 3,
      "command_line": "\"C:\\Windows\\system32\\wevtutil.exe\" cl security",
      "hash": {
        "sha1": "177d75b7c2563c84d5c562cc169bc7e0669b520b",
        "sha256": "be25116a08cca0d57e9247f2aace033bfa1ffb6aa9852f9a9f24dbc2bc32d187",
        "md5": "c57c1292650b6384903fe6408d412cfa"
      }
    },
    "message": "Endpoint process event",
    "@timestamp": "2021-08-30T16:16:28.8910233Z",
    "ecs": {
      "version": "1.6.0"
    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "endpoint.events.process"
    },
    "elastic": {
      "agent": {
        "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208"
      }
    }
}
```

**Comment by austinsonger** [comment]
This is already  taken care of here.
- https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_clearing_windows_event_logs.toml

```
process where event.type in ("process_started", "start") and
  (process.name : "wevtutil.exe" or process.pe.original_file_name == "wevtutil.exe") and
    process.args : ("/e:false", "cl", "clear-log") or
  process.name : "powershell.exe" and process.args : "Clear-EventLog"
```

You might be able to change this to "Rule Tuning"

by changing `cl` to `*cl*`
