### ISSUE TITLE
[New Rule] Windows Logs Cleared using Powershell 

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#1466]
## Description
Adversaries may clear Windows Event Logs to hide the activity of an intrusion. Windows Event Logs are a record of a computer's alerts and notifications. There are three system-defined sources of events: System, Application, and Security, with five event types: Error, Warning, Information, Success Audit, and Failure Audit.

This is a very specific and simple rule that looks for threat actors using Powershell cmdlets (Clear-EventLog and Remove-EventLog) to clear Windows event logs on a system. 

There should be no false positives when it comes to this detection and it should be very rare for this event to fire as clearing event logs manually is not a normal occurrence. 

### Target indexes
logs-\*, filebeat-\*, winlogbeat-*

### Additional requirements
Ensure Windows Powershell\Operational logs are being collected and Script Block logging is enabled.

### Target Operating Systems
Windows

### Tested ECS Version
7.14.0

## Optional Info

It is worth noting that a threat actor could also write custom tooling that utilizes the Windows API to delete Windows Event Logs but it is my understanding that Event ID 1102 will still be logged indicating the logs were cleared although I have not taken time to test this yet.

### Query

```sql
event.code : 4104 and powershell.file.script_block_text : "*Clear-EventLog*" or powershell.file.script_block_text : "*Remove-EventLog*"
```

### References

https://attack.mitre.org/techniques/T1070/001/

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/clear-eventlog?view=powershell-5.1

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-eventlog?view=powershell-5.1

## Example Data

```json
{
  "_index": ".ds-logs-windows.powershell_operational-default-2021.08.26-000001",
  "_type": "_doc",
  "_id": "xwJLmHsBDd5RH2lH2x7p",
  "_score": 1,
  "_source": {
    "agent": {
      "hostname": "windows10",
      "name": "windows10",
      "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208",
      "type": "filebeat",
      "ephemeral_id": "549e32b9-283c-4f77-b35b-678fba06041a",
      "version": "7.14.0"
    },
    "winlog": {
      "computer_name": "windows10",
      "process": {
        "pid": 7804,
        "thread": {
          "id": 3184
        }
      },
      "channel": "Microsoft-Windows-PowerShell/Operational",
      "opcode": "On create calls",
      "version": 1,
      "record_id": "1773",
      "task": "Execute a Remote Command",
      "event_id": "4104",
      "provider_guid": "{a0c1853b-5c40-4b15-8766-3cf1c58f985a}",
      "activity_id": "{6bde730a-9a9a-0000-9aab-de6b9a9ad701}",
      "api": "wineventlog",
      "provider_name": "Microsoft-Windows-PowerShell",
      "user": {
        "identifier": "S-1-5-21-2010172997-3706935026-3061584476-1000",
        "domain": "WINDOWS10",
        "name": "vagrant",
        "type": "User"
      }
    },
    "log": {
      "level": "verbose"
    },
    "elastic_agent": {
      "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208",
      "version": "7.14.0",
      "snapshot": false
    },
    "message": "Creating Scriptblock text (1 of 1):\nClear-EventLog -LogName \"Windows Powershell\" -Confirm\n\nScriptBlock ID: 10c537f3-fbcc-4eeb-a98a-0a109963982c\nPath: ",
    "input": {
      "type": "winlog"
}
```

**Comment by austinsonger** [comment]
`Clear-EventLog` is already used here, 

- https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_clearing_windows_event_logs.toml

you may be able to expand this rule.

and change it to

```
process where event.type in ("process_started", "start") and
  (process.name : "wevtutil.exe" or process.pe.original_file_name == "wevtutil.exe") and
    process.args : ("/e:false", "cl", "clear-log") or
  process.name : "powershell.exe" and process.args : "*Clear-EventLog*" and process.args :  "*Remove-EventLog*"
```

But I wonder what @brokensound77 thinks.

**Comment by w0rk3r** [comment]
Using process.args don't cover ScriptBlock Logging AFAIK, this kind of Rule looks for ScriptBlock contents... But using this field can bring problems that I've solved by modifying the analyzer not to ignore the `-` that the cmdlets have, so I don't think it is  a good idea to include them if they still don't work out-the-box.

![image](https://user-images.githubusercontent.com/26856693/131422300-ecc0bac0-2245-448c-8cac-080a82029f39.png)

Ref:
https://discuss.elastic.co/t/hyphens-in-queries-are-ignored-on-powershell-logs-collected-by-elastic-agent-and-winlogbeat/259537

**Comment by w0rk3r** [comment]
Here is the effect that the standard analyzer causes when you search for cmdlets, at least when I had this problem back in December

![image](https://user-images.githubusercontent.com/26856693/131422465-33866cd4-d95e-4550-b2d7-e8bced8e5a7d.png)
