### ISSUE TITLE
[New Rule] Windows Logs Cleared Event ID 1102

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#1467]
## Description
Adversaries may clear Windows Event Logs to hide the activity of an intrusion. Windows Event Logs are a record of a computer's alerts and notifications. There are three system-defined sources of events: System, Application, and Security, with five event types: Error, Warning, Information, Success Audit, and Failure Audit.

This is a very specific and simple rule that looks for the creation of the Windows Event ID 1102 audit logs cleared to alert the user to the fact that audit logs have been cleared. 

There may be false positives with this particular Event ID depending on if a user has a script to go delete event logs after a certain amount of time or something to that affect. This event ID should still be logged. 

### Target indexes
logs-\*, filebeat-\*, winlogbeat-*

### Additional requirements
Ensure Event ID 1102 is enabled via GPO or local audit policy.

### Target Operating Systems
Windows

### Tested ECS Version
7.14.0

### Query

```sql
event.code : "1102"
```
### References

https://attack.mitre.org/techniques/T1070/001/

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-1102

## Example Data

```json
{
  "_index": ".ds-logs-system.security-default-2021.08.26-000001",
  "_type": "_doc",
  "_id": "ggHZl3sBDd5RH2lHENBi",
  "_score": 1,
  "_source": {
    "agent": {
      "hostname": "windows10",
      "name": "windows10",
      "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208",
      "ephemeral_id": "549e32b9-283c-4f77-b35b-678fba06041a",
      "type": "filebeat",
      "version": "7.14.0"
    },
    "winlog": {
      "computer_name": "windows10",
      "process": {
        "pid": 848,
        "thread": {
          "id": 1428
        }
      },
      "keywords": [
        "Audit Success"
      ],
      "logon": {
        "id": "0xa8808"
      },
      "channel": "Security",
      "user_data": {
        "SubjectUserName": "vagrant",
        "SubjectDomainName": "WINDOWS10",
        "SubjectLogonId": "0xa8808",
        "SubjectUserSid": "S-1-5-21-2010172997-3706935026-3061584476-1000",
        "xml_name": "LogFileCleared"
      },
      "opcode": "Info",
      "record_id": "250344",
      "task": "Log clear",
      "event_id": "1102",
      "provider_guid": "{fc65ddd8-d6ef-4962-83d5-6e5cfe9ce148}",
      "api": "wineventlog",
      "provider_name": "Microsoft-Windows-Eventlog"
    },
    "log": {
      "level": "information"
    },
    "elastic_agent": {
      "id": "ac16290d-cdd0-43df-ae02-869fd6d9b208",
      "version": "7.14.0",
      "snapshot": false
    },
    "message": "The audit log was cleared.\nSubject:\n\tSecurity ID:\tS-1-5-21-2010172997-3706935026-3061584476-1000\n\tAccount Name:\tvagrant\n\tDomain Name:\tWINDOWS10\n\tLogon ID:\t0xA8808",
    "input": {
      "type": "winlog"
    },
}
```

**Comment by austinsonger** [comment]
`event.code` (Event IDs) leading to false positives is highly likely.
