### ISSUE TITLE
[Bug] Roshal Archive (RAR) or PowerShell File Downloaded from the Internet

### ISSUE THREAD

**Issue by VictorGgc** [elastic/detection-rules#1471]
Hello,

I receive the following error when I try to active the rule "Roshal Archive (RAR) or PowerShell File Downloaded from the Internet". 
Please see below screenshot:

![rule fail](https://user-images.githubusercontent.com/90254637/132335130-dedd5ed1-4ed4-4f34-9133-d1bd171f280e.jpg)

Seems to be a bug because I didn't changed the rule just simply activated it. I checked the fields from query and found nothing wrong.

I already reported it via slack channel to James Spiteri.

**Comment by w0rk3r** [comment]
Hey @VictorGgc, which version of Elastic are you running?

**Comment by VictorGgc** [comment]
Hi, we are using 7.14
