### ISSUE TITLE
PSRunner.exe is detected as a trojan

### ISSUE THREAD

**Issue by jdieguezbean** [elastic/detection-rules#1483]
[PsRunner.exe](https://github.com/elastic/detection-rules/blob/main/rta/bin/PsRunner.exe) is detected as a trojan

1. Download repo

**Comment by devonakerr** [comment]
I don't believe this is the right repo for this issue, as it seems to pertain to a classifier behavior and not a behavior of a rule. I'll pass it along to the appropriate team and close this issue.
