### ISSUE TITLE
[New Rule] Suspicious Registry Modifications

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#1488]
## Description
This detection looks at suspect changes being made within the HKEY_USERS hive of the registry specifically within a users SID_Classes subkey where the process could be used to execute code against the registry and the registry key value upon change is an empty string. This rule was created following analysis of a new version of a known strain of malware that implements this technique for executing malicious obfuscated Powershell in the registry. This query was ran against Windows data dating back 90 days and detected no false positives. That doesn't mean they don't exist. 

### Target indexes
logs-\*, winlogbeat-*

### Additional requirements
This detection will match on both Elastic endpoint file events and Symon file creation events.

### Target Operating Systems
Windows

### Tested ECS Version
7.14.0

### Query

```sql

registry where event.type == "change" and 
process.name : ("cmd.exe", "powershell.exe", "wmic.exe", "mshta.exe", "pwsh.exe", "cscript.exe", "wscript.exe", "regsvr32.exe", "RegAsm.exe", "rundll32.exe", "EQNEDT32.EXE", "WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE", "iexplore.exe", "InstallUtil.exe") and 
registry.hive : "HKEY_USERS" and 
registry.path : "*Classes\\*" and 
registry.value in (null, "")

```

**Comment by willemdh** [comment]
@DefSecSentinel It would be nice if the Sysmon registry bug could be fixed, see https://github.com/elastic/beats/issues/27408

Otherwise detectting this might be hard.
