### ISSUE TITLE
[New Rule] DCSync Detection

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#1490]
## Description

Adversaries may attempt to access credentials and other sensitive information by abusing a Windows Domain Controller's application programming interface (API) to simulate the replication process from a remote domain controller using a technique called DCSync.

This detection looks at the property values associated with the active directory object which denote the type of access used and what that access provided access to. The below property values are directly associated with Active Directory replication  

### Target indexes
logs-\*, winlogbeat-*

### Additional requirements
Requires you to collect EventID 4662 (An operation was performed on an object) located in the Directory Service Access subcategory of events. The below command will enable these logs.

auditpol.exe /set /subcategory:"Directory Service Access" /success:enable /failure:disable

### Target Operating Systems
Windows

### Tested ECS Version
7.14.0

## Optional Info

A false positive for this detection would be valid domain replication by a domain administrator. The computer name field below should be altered to reflect your domain controller naming convention.

### Query

```sql
event.code : "4662" and 
winlog.computer_name : "*DC*"
winlog.event_data.Properties : "*1131f6aa-9c07-11d1-f79f-00c04fc2dcd2*" or 
winlog.event_data.Properties : "*1131f6ad-9c07-11d1-f79f-00c04fc2dcd2*"
```

### References

https://attack.mitre.org/techniques/T1003/006/

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4662

https://gist.githubusercontent.com/gentilkiwi/dcc132457408cf11ad2061340dcb53c2/raw/453f33a5c2371c6d7a01ddaa8135a562d3ec82cc/dcsync-dcshadow.splunk

**Comment by austinsonger** [comment]
Can try this out and see.

```
winlog.event_data.AccessMask : "0x100" and winlog.computer_name : "*DC*" and
winlog.event_data.Properties : ("*1131f6aa-9c07-11d1-f79f-00c04fc2dcd2*" or 
"*1131f6ad-9c07-11d1-f79f-00c04fc2dcd2*" or "89e95b76-444d-4c62-991a-0facbeda640c*" or 
"*Replicating Directory Changes All*")
```

or

```
winlog.event_data.AccessMask : ("0x100" or "0x40000") and winlog.computer_name : "*DC*" and
winlog.event_data.Properties : ("*1131f6aa-9c07-11d1-f79f-00c04fc2dcd2*" or 
"*1131f6ad-9c07-11d1-f79f-00c04fc2dcd2*" or "89e95b76-444d-4c62-991a-0facbeda640c*" or 
"*Replicating Directory Changes All*")
```
