### ISSUE TITLE
[Bug] KQL Module - Wildcard check

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#1529]
**Describe the bug**
When validating the query using `python -m detection_rules toml-lint -f file.toml`, the module indicates that `Unable to perform wildcard on field powershell.file.script_block_text of text`, but the query is working on Kibana.

```
kql.errors.KqlParseError: Error at line:1,column:89
Unable to perform wildcard on field powershell.file.script_block_text of text
event.code: "4104" and event.module: "windows" and powershell.file.script_block_text : (*WindowsErrorReporting or Dbghelp.dll) and powershell.file.script_block_text : (MiniDumpWriteDump)
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
stack: 7.14.0, beats: 7.14.0, ecs: 1.11.0
```

**To Reproduce**
Rule: https://github.com/elastic/detection-rules/pull/1528

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by brokensound77** [comment]
> Full event dump
> 
> Event Dump

I think this is meant for #1527

**Comment by brokensound77** [comment]
I am gonna close this as a `wontfix`

For an explanation of why, refer to this [comment](https://github.com/elastic/detection-rules/pull/1530#issuecomment-935089728) from the PR
