### ISSUE TITLE
[Bug] [Windows] auto Pop ups on laptop screen

### ISSUE THREAD

**Issue by samad-nasar** [elastic/detection-rules#1534]
I am suffering an annoying behavior in windows laptop. Any time I connect my laptop to the power supply (charge), a small black window pops up for a second and then disappears automatically. I have scanned the system several times for viruses, but didn't work. plz help.
OS: Windows 10 enterprise
laptop: hp elitebook 840 g1
<img width="671" alt="bug2" src="https://user-images.githubusercontent.com/64058029/136610149-7f463af5-bee6-40a3-80c8-5b35f0fceaee.png">

**Comment by devonakerr** [comment]
The installutil application is shipped with Windows for assisting with software installation, and it may be used legitimately by both the Operating System and third party software applications. We have many rules already for malicious use of this utility, though it sounds like you haven't investigated whether this use is malicious or not. My recommendation is to research that further using a tool like Autoruns, specifically looking for references to Installutil. If you confirm a malicious entry, that could indicate malware has been installed and your computer should be rebuilt from a known clean set of media. I'll close this issue as it does not appear related to rules.
