### ISSUE TITLE
Update EQL schemas to fail validation on text fields

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#1554]
Elasticsearch EQL does not currently support text fields

cc: @w0rk3r

**Comment by Mikaayenson** [comment]
Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/eql-syntax.html#eql-text-fields

**Comment by Mikaayenson** [comment]
Updates Needed (Does not list kql references to `text`)

- https://github.com/elastic/detection-rules/blob/main/tests/kuery/test_kql2eql.py#L76
- https://github.com/elastic/detection-rules/blob/main/tests/kuery/test_kql2eql.py#L78
- https://github.com/elastic/detection-rules/blob/main/etc/non-ecs-schema.json#L42
- https://github.com/elastic/detection-rules/blob/main/etc/non-ecs-schema.json#L56
- https://github.com/elastic/detection-rules/blob/main/detection_rules/ecs.py#L121

**Comment by Mikaayenson** [comment]
@brokensound77  We should flush this out a bit more.  

- Fail [here](https://github.com/elastic/detection-rules/blob/main/detection_rules/rule_validators.py#L96) in `EQLValidator` if the `text` field is present (Most likely from `beats` or `ecs` schemas.
- Remove KQL to EQL validation unit test in `test_schema` e.g. [here](https://github.com/elastic/detection-rules/blob/main/tests/kuery/test_kql2eql.py#L76)
- Add test cases to make sure the eql fails.
- Anything else?

**Comment by brokensound77** [comment]
>Fail [here](https://github.com/elastic/detection-rules/blob/main/detection_rules/rule_validators.py#L96) in EQLValidator if the text field is present (Most likely from beats or ecs schemas.

That is where we would catch it and wrap it but we will need to invalidate it in `ecs.py` or possibly even within the `kql` module, since some of it depends on the conversion schema.

The rest of your list LGTM.

**Comment by Mikaayenson** [comment]
`text` fields in ecs 1.9.0, 1.10.0, 1.11.0

- error.message
- message

Since then the field types changed to "match_only_text". Just to be clear, should the `match_only_text` field type pass validation?

**Comment by Mikaayenson** [comment]
After digging through the code, it appears that the validation part is already complete.  The code will get the Elasticsearch mapping type in the [parser](https://github.com/elastic/detection-rules/blob/main/kql/parser.py#L51) but then try to lookup eql_hinting based on the types in [ecs](https://github.com/elastic/detection-rules/blob/main/detection_rules/ecs.py#L200) and returns the `eql_hint`.

During the validation, if the returned `eql_hint` value is `None`, then the parser will fail in [eql](https://github.com/endgameinc/eql/blob/master/eql/parser.py#L443), thus causing the validation to fail with a message `message = "Field not recognized"`.

To complete this issue, I think we just need to remove the KQL to EQL validation unit tests and add specific tests that fail if the field is type `text`.

Does that make sense?

**Comment by brokensound77** [comment]
Yep, 💯 . I verified that eql text fields fail with `not recognized` just as you stated. Revised tests and more explicit failure make sense to me (from your PR). Thanks!
