### ISSUE TITLE
[New Rule] Threshold rule to detect multiple different Mitre Tactics on the same host in the last 24h

### ISSUE THREAD

**Issue by aarju** [elastic/detection-rules#1597]
## Description

A Threshold rule that looks for unique count of more than 2 different `kibana.alert.rule.threat.tactic.name` values for a single host.name in the last 24h and generates a critical alert when they are observed. This could be an indicator of an ongoing attack impacting multiple parts of the kill chain.

This is an example rule I created on my cluster
<img width="1010" alt="Screen Shot 2021-10-29 at 14 53 37" src="https://user-images.githubusercontent.com/14032876/139438406-14066c94-3401-4910-b6b4-913b39530263.png">

### Target indexes

`.siem-signals-*`

### Additional requirements

Detection rules need to be configured with `kibana.alert.rule.threat.tactic.name` as much as possible.

**Comment by w0rk3r** [comment]
@aarju, I think that having more than one tactic in a rule is the normal and desired behavior. These are used to classify the detection and also to give context to the analyst on what enabled the attacker (Execution, for example)

**Comment by aarju** [comment]
Within our environment this has worked pretty well. I increased the `unique count` of `kibana.alert.rule.threat.tactic.name` to >= 3 and I set the rule to run every hour with a 24h additional lookback. While not perfect, this has helped alert us to hosts that are at a higher risk due to multiple parts of the kill chain being seen.

**Comment by aarju** [comment]
We've been running this detection rule on our production servers over the last few months and it has worked out really well.

**Comment by w0rk3r** [comment]
Thanks for letting us know @aarju, I'll work in a PR for this in the next few days

**Comment by SHolzhauer** [comment]
Came across this so created a PR for it; I left MITRE mapping out of this one as it triggers on others, which felt duplicate.
@aarju does this look like it matches with your logic/expectation?

**Comment by aarju** [comment]
Thanks for submitting the PR @SHolzhauer, the logic in that PR looks good to me.
