### ISSUE TITLE
[Rule Tuning] defense_evasion_misc_lolbin_connecting_to_the_internet

### ISSUE THREAD

**Issue by bohops** [elastic/detection-rules#1600]
## Link to rule

https://github.com/elastic/detection-rules/blob/12577f7380f324fcee06dab3218582f4a11833e7/rules/windows/defense_evasion_misc_lolbin_connecting_to_the_internet.toml

## Description

I noticed a very small oversight with this rule. The rule references 'extrac.exe' lolbin.  I believe the reference should be  'extrac32.exe'.

## Example Data
Relative code snippet:
''''...
  [process where (process.name : "expand.exe" or process.name : "extrac.exe" or
                 process.name : "ieexec.exe" or process.name : "makecab.exe") and
                 event.type == "start"]
  [network where (process.name : "expand.exe" or process.name : "extrac.exe" or
                 process.name : "ieexec.exe" or process.name : "makecab.exe") and

...'''

**Comment by w0rk3r** [comment]
Thanks @bohops ;)

**Comment by bohops** [comment]
My pleasure!

**Comment by brokensound77** [comment]
resolved by #1601
