### ISSUE TITLE
[Bug] Need to update rule "Windows Defender Exclusions Added via PowerShell"

### ISSUE THREAD

**Issue by hsvhora** [elastic/detection-rules#1642]
**Describe the bug**
**Windows Defender Exclusions Added via PowerShell** rule is not detecting the events triggered, hence needed minor change in the rule in order to work properly.

**To Reproduce**
1. Make sure you have enabled above mentioned rule in elasticsearch security.
2. Open Command Prompt in windows
3. Execute command `powershell Add-MpPreference - ExclusionPath 'C:\Not Existing Path\'`
4. Execute command `powershell Add-MpPreference - ExclusionProcess 'not_existed.exe'`
5. Above 2 command will add path and process exclusions in windows defender.
6. Rule would not generate alert this time
7. Login to kibana and duplicate rule "Windows Defender Exclusions Added via PowerShell" with "Windows Defender Exclusions Added via PowerShell [Duplicate]"
8. Change custom query to below (**process.commmand_line** is replaced with _process.args_ in older rule)

> process where event.type == "start" and
>  (process.name : ("powershell.exe", "pwsh.exe", "powershell_ise.exe") or process.pe.original_file_name in ("powershell.exe", "pwsh.dll", "powershell_ise.exe")) and
>   process.command_line : ("*Add-MpPreference*-Exclusion*", "*Set-MpPreference*-Exclusion*")

9. Activate newly created duplicate rule.
10. Execute command in step 3 and 4
11. New duplicate rule should trigger now.

**Comment by w0rk3r** [comment]
Hey @hsvhora, I could not reproduce the issue, both queries would match the event as shown below:

Using process.args:

![image](https://user-images.githubusercontent.com/26856693/144431587-a264ea5b-b0fa-4dcd-9182-14883f8ff1db.png)

Using process.command_line:

![image](https://user-images.githubusercontent.com/26856693/144431747-3b572e29-58b2-42e4-bb31-10507d9a82cd.png)

Can you provide more details like:
* Data source
* Stack version
* A full event which doesn't get matched by the process.args query

**Comment by hsvhora** [comment]
Hi @w0rk3r,

Thank you for your time to investigate the issue. Please find required details as below.

- Data source : **winlogbeat-7.14.0**, **Channel : Microsoft-Windows-Sysmon/Operational**, OS : **Windows 10**
- Stack version : 7.14.0
- Full Event : attached json file as txt [event_details.txt](https://github.com/elastic/detection-rules/files/7647475/event_details.txt)

Detection snapshots:
1. Using process.args

<img width="953" alt="2 args_not_detection" src="https://user-images.githubusercontent.com/6726247/144561901-72a6af5f-edfa-4123-9fed-3058fda3a5c5.png">

2. Using process.command_line

<img width="944" alt="1 cmd_line_detection" src="https://user-images.githubusercontent.com/6726247/144561933-1b4f811b-d7ec-4cdf-8ce6-3996a1bf6269.png">

I think issue is because of the way elasticsearch has parsed _(or winlogbeat got)_ process.args in my case. As highlighted in above snap-2 in my case, event is having 5 separate process.args elements created by splitting command line by space.

- process.commnd_line : `"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -c Add-MpPreference -ExclusionPath D:\not_exist\`
<img width="899" alt="image" src="https://user-images.githubusercontent.com/6726247/144563710-f38f538a-c20f-4974-bddd-24c16fbdaf17.png">

- process.args (5 elements): `["C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe", -c, Add-MpPreference, -ExclusionPath, D:\not_exist\]`
<img width="453" alt="image" src="https://user-images.githubusercontent.com/6726247/144563781-34bd1a91-f2d1-47af-8859-fbd0e877da01.png">

 Where as in your case process.args are (3 elements):  `["C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe", -c, Add-MpPreference -ExclusionPath D:\Notexist]`

You can see above in attached json event file as well. Please let me know if you need anything else. Thanks again for your time.

**Comment by w0rk3r** [comment]
Oh, yeah, now I see the problem. As the solution, I'll look for the Exclusion argument in a AND condition instead of the wildcard used.

Elastic splits the command line fields in whitespaces. As you don't put the command (-c) between quotes, each is considered an argument. Thanks for bringing this up!

You can test the query and propose changes in this PR: https://github.com/elastic/detection-rules/pull/1644

Looking forward to more contributions ;)

**Comment by hsvhora** [comment]
New changes works perfectly @w0rk3r. Thank you.
