### ISSUE TITLE
Interactive Terminal Spawned via Python bypass[Bug]

### ISSUE THREAD

**Issue by Youghourta-ghennai** [elastic/detection-rules#1646]
## Description
hello there it is youghourta ghennai from Octodet , i want to share some bypasses about this rule .
these rule is supposed to detect this behaviour : 

`python -c 'import pty; pty.spawn("/bin/sh")'`

first ==>  if an attacker used python3 instead of python like that : `python3 -c 'import pty; pty.spawn("/bin/sh")'` 
these one could not be detected because the process.name that should be detected by the rule you created is "python" according to this part of course = `process.name : python` 

second ==> if an attacker just remove the space between "import pty;" and "pty.spawn(...)" , also these rule will not detect the event 
because it is exactly set to detect `import pty; pty.spawn("/bin/sh")` and you know that it could be no space between ';' and the next instruction in python lang and of course this is according to  : `process.args:("import pty; pty.spawn(\"/bin/sh\")" or
                "import pty; pty.spawn(\"/bin/dash\")" or
                "import pty; pty.spawn(\"/bin/bash\")")`.

third ==> if an attacker uses additional slashes between repos like'/bin/////sh' or '////bin//sh' or something like that , also these one will not be detected because of this part : process.args:`("import pty; pty.spawn(\"/bin/sh\")" or
                "import pty; pty.spawn(\"/bin/dash\")" or
                "import pty; pty.spawn(\"/bin/bash\")") `
this one is configured to detect it like this exactly : '/bin/sh' , '/bin/dash' , '/bin/bash' so if an attacker used these as payload : 

`python -c 'import pty; pty.spawn("///bin//\/sh")'` (this is just an example) .

fourth ==> i detected that you are only trying to detect three kinds of shell , otherwise it could be more shells like 'zsh' , 'csh' , 'ash' and others .
## these is the new eql code i have created for these rule , and i hope you like it .
`process where event.type in ("start" , "process_started") and wildcard(process.name ,"python*") and
process.args regex ("import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}sh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}dash[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}bash[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}zsh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}csh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}ash[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}bsh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}ksh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}tcsh[\"']\\)",
"import pty; {0,}pty\\.spawn\\([\"']/{1,}bin/{1,}pksh[\"']\\)"
)`

**Comment by w0rk3r** [comment]
Hey @Youghourta-ghennai, thanks for bringing this for our attention. I've reviewed the current query and saw some caveats that I'm fixing with the one in this [PR](https://github.com/elastic/detection-rules/pull/1649). Lemme know your thoughts on it.

**Comment by Youghourta-ghennai** [comment]
hello @w0rk3r  , i hope you are fine .
Thank you for your support . 
i saw the modification it sounds good , but i can see that you missed something about other shells like (csh , bsh , ash , zsh ..) 
maybe we can use this one and we will be able to detect everything . 
`process where event.type in ("start", "process_started") and
  process.name : "python*" and (
    process.args : ("*import*pty*") and
    process.args : ("*pty.spawn*/*sh*")
  )`

and this will work for everything .
kind regards .
