### ISSUE TITLE
Account Password Reset Remotely [Bug]

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#1676]
**Describe the bug**
Enabling this rule throws a verification exception

**To Reproduce**
1. Enable the Rule
2. Check Rule State (failed)

![image](https://user-images.githubusercontent.com/33020901/147584175-db3e08d7-d064-401f-8e5c-ec10c8648fcf.png)

I have duplicate the rule and modified it slightly and it seems to pass the verification step 

```
sequence by host.id with maxspan=5m
  [authentication where event.action == "logged-in" and
    /* event 4624 need to be logged */
    winlog.logon.type : "Network" and event.outcome == "success" and source.ip != null and
    not source.ip == "127.0.0.1" and not source.ip == "::1"] by winlog.event_data.TargetLogonId
   /* event 4724 need to be logged */
  [iam where event.action == "reset-password"] by winlog.event_data.SubjectLogonId

```
I do not know if I'm doing something wrong or if it is something wrong with the rule.
Thank you!

**Comment by austinsonger** [comment]
@janniten I recommend posting this on https://discuss.elastic.co/ instead of here and closing this ticket.

Or you can join the slack https://ela.st/slack and posting this in `#security`, `#security-detection-rules`,`#security-eql`,`#security-siem`

**Comment by w0rk3r** [comment]
@austinsonger I've asked @janniten to open the issues here on GitHub. I'm taking a look on these.

**Comment by austinsonger** [comment]
https://discuss.elastic.co/t/verification-exception-error-during-rule-execution/275781
