### ISSUE TITLE
Potential Credential Access via LSASS Memory Dump [Bug]

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#1677]
**Describe the bug**
Enabling this rule throws a verification exception

**To Reproduce**
Enabling this rule throws a verification exception

![image](https://user-images.githubusercontent.com/33020901/147657204-065a9915-aa86-4dc1-9cbc-3a15d1688edb.png)

**Comment by austinsonger** [comment]
@janniten I recommend posting this on https://discuss.elastic.co/ instead of here and closing this ticket.

Or you can join the slack https://ela.st/slack and posting this in `#security`, `#security-detection-rules`,`#security-eql`,`#security-siem`

**Comment by w0rk3r** [comment]
Hey @janniten, I took a look on this and there is nothing wrong with the rule.

The verification_exception occurs in clusters with no sysmon event id 10 events; thus, the field is unknown. Once you configure sysmon to produce those and collect them, you should not see the error anymore.

Stack with no event 10 events:

![image](https://user-images.githubusercontent.com/26856693/150784589-10cfff58-04bd-4d50-92f2-aec0d5deff7a.png)

Stack with event 10 events:

![image](https://user-images.githubusercontent.com/26856693/150784726-2fb9d4b6-5281-4606-9edc-dd2c9ba76905.png)

![image](https://user-images.githubusercontent.com/26856693/150784835-1c8a8cc4-b80a-4100-914f-aab3e3683381.png)

**Comment by janniten** [comment]
Thank you @w0rk3r , originally it was my guess

https://elasticstack.slack.com/archives/C016E72DWDS/p1640766907218200
