### ISSUE TITLE
Suspicious Process Creation CallTrace [Bug]

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#1678]
**Describe the bug**
Enabling this rule throws a verification exception

**To Reproduce**
1. Enable the Rule
2. Check Rule State (failed)

![image](https://user-images.githubusercontent.com/33020901/147657491-5d30d1ad-07da-4be9-8462-0c850778d760.png)

**Comment by austinsonger** [comment]
@janniten I recommend posting this on https://discuss.elastic.co/ instead of here and closing this ticket.

Or you can join the slack https://ela.st/slack and posting this in `#security`, `#security-detection-rules`,`#security-eql`,`#security-siem`

**Comment by w0rk3r** [comment]
Same as https://github.com/elastic/detection-rules/issues/1677#issuecomment-1020060758
