### ISSUE TITLE
[New Rule] Detect Windows Event Log and Event Collector Shutdown

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#1681]
## Description
Basically detect when the either the Windows Event Log or Windows Event Collector are stopped.
Doing this an attacker can evade activity tracking

### Target indexes

logs-system*, winlogbeat*

### Target Operating Systems
Windows
## Optional Info

The information used in this query is hold in the Window's event 7036 (System Channel/Service Control Manager Provider).
Although this event is not into ECS (yet) I think it is important to alert when one of the main event tracking system is stopped.
Once the event in ECS, the rule can be modified to use ECS Fields

### Query

`event.code : "7036" and (winlog.event_data.param1 : "Windows Event Log" or winlog.event_data.param1 : "Windows Event Collector"  ) and winlog.event_data.param2: "stopped" 
`
If the rule is considered useful I can create a PR

## Example Data
(attached)
[example2.txt](https://github.com/elastic/detection-rules/files/7806878/example2.txt)
[example.txt](https://github.com/elastic/detection-rules/files/7806879/example.txt)

**Comment by janniten** [comment]
I did create the rule in my system and it works 
![image](https://user-images.githubusercontent.com/33020901/148046220-80d0f505-bc6e-4a8e-a325-b47ed3ea98c9.png)

**Comment by SHolzhauer** [comment]
If i'm not mistaken this will trigger on a reboot of the host. Have you experienced this behavior and/or given that any thought?

**Comment by janniten** [comment]
Hi @SHolzhauer, this event is triggered on a host reboot but also when you stop the Windows Event Collector Service.

**Comment by SHolzhauer** [comment]
I.m.o. this will create noise when a system is rebooted (stop logging, reboot, start logging) and you only want to be triggered when logging has stopped on its own.

What are the thoughts on this?

**Comment by phillo197** [comment]
how do i detect with ML when the transmission of the log events is turned off

**Comment by phillo197** [comment]
and how do I implement the rule because I am new to Elastic ML
