### ISSUE TITLE
[New Rule] Detect fake apple launch agent being installed

### ISSUE THREAD

**Issue by aarju** [elastic/detection-rules#1707]
## Description
This rule detects when a usermode Launch agent is installed on a MacOS system pretending to be from Apple. The LaunchAgents and LaunchDaemons folders are used for third party applications that start on boot. You should never see files in this folder with the naming convention of `com.apple.*.plist`

### Target indexes
logs-*, auditbeat-*, endgame-*

### Additional requirements
File creating event logging on macOS systems

### Target Operating Systems
macOS

### Query
```
file where event.type != "deletion" and
  file.path : 
  (
    "/Users/*/Library/LaunchAgents/com.apple.*",
    "/Library/LaunchAgents/com.apple.*",
    "/Library/LaunchDaemons/com.apple.*"
  ) 
```

### References
The SysJoker malware creates a persistence file named `/Library/LaunchAgents/com.apple.update.plist` in the LaunchAgents folder for persistence. Because it does not immediately load the persistence and waits for a reboot to load the malware it doesn't trigger the current detections. 

https://objective-see.com/blog/blog_0x6C.html

**Comment by aarju** [comment]
Looking at the events on our fleet of Macs I see events from 5 hosts in the last 90 days where files with a naming convention of `com.apple.*.plist` were created in those paths. I'm investigating now to see if those are legitimate or not.

**Comment by DefSecSentinel** [comment]
We currently have an endpoint rule that detects a similar technique and a new data source we are testing for 8.4 will replace this detection.
