### ISSUE TITLE
[FR] Move to setup.py installation

### ISSUE THREAD

**Issue by DJRickyB** [elastic/detection-rules#1765]
In order to finalize the work started in #1672, the project should have dependency and package declaration in setup.cfg.  This will allow `pip install .` or `pip install git+https://github.com/elastic/detection-rules.git` to include everything necessary to run.

- [x] move etc under detection_rules #1885
- [x] update setup.cfg #1948

**Comment by Kogl1n** [comment]
Please consider that `kibana` and `kql` folders (that are situated outside of the actual package dir) are required.
Maybe it is necessary to include the following block in the setup.cfg?
```
package_dir =
  detection_rules = detection_rules
  detection_rules.kibana = kibana
  detection_rules.kql = kql
python_requires = >=3.8.0
```

Those would be installed outside of the package in the `site-packages`-dir. But there is already a python package called `kibana` available via pip that would overwrite at least the `__init__.py`.

**Comment by DJRickyB** [comment]
Circling back to this now. Thanks a ton for the feedback, I'm assuming it is against the proposed change in #1764 . I will incorporate what I can there

**Comment by brokensound77** [comment]
Thanks @DJRickyB for this and @Kogl1n for the feedback!

I updated the description to break this into separate steps. We will tackle moving etc first, then explore kibana and kql. Once done, we can update to make this a proper package

**Comment by DJRickyB** [comment]
The gist of my challenges with getting this done was mainly that I hit a barrier where resolving files via paths was not working once everything was coming from a package. I think the heavy lifting will come from resolving them using something like [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources)

**Comment by Mikaayenson** [comment]
@brokensound77  Is there a reason we shouldn't use a `MANIFEST.in` file instead of moving `etc`?

**Comment by brokensound77** [comment]
Good points. We also have to decide on a versioning flow
