### ISSUE TITLE
[Rule Tuning] SystemKey Access via Command Line

### ISSUE THREAD

**Issue by ynirk** [elastic/detection-rules#1812]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/macos/credential_access_systemkey_dumping.toml

## Description
On macos, SystemKey file is located at `/private/var/db/SystemKey`but also `/var/db/SystemKey`.

![Screenshot from 2022-03-04 15-39-18](https://user-images.githubusercontent.com/33804891/156784895-60fc7d65-fbf0-44fd-a216-105d95f548c7.png)

`/var/db/SystemKey` should be added to the rule query

**Comment by terrancedejesus** [comment]
This rule has been updated and merged according to the following PR below.
* https://github.com/elastic/detection-rules/pull/1889
