### ISSUE TITLE
[FR] Convert backport logic to sh script

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#1899]
https://github.com/elastic/detection-rules/blob/bcec8a447992a8e49b421858ef8bf109f79006cf/.github/workflows/backport.yml#L110-L148

Then call it from the workflow as a script, passing the args.

This would allow us to manually call it when needed for simplicity

**Comment by brokensound77** [comment]
also add a manual dispatch gh workflow

**Comment by brokensound77** [comment]
Also make it compatible with forks as well

**Comment by Mikaayenson** [comment]
@brokensound77 do you want to also update `backport.yml` to use the new script like the `manual-backport.yml` or leave it as-is?

**Comment by Mikaayenson** [comment]
@brokensound77 do you want to also update `backport.yml` to use the new script like the `manual-backport.yml` or leave it as-is?

**Comment by Mikaayenson** [comment]
This should be done. Waiting on review
