### ISSUE TITLE
Question: macOS rules?

### ISSUE THREAD

**Issue by hazcod** [elastic/detection-rules#190]
Hi, just wanted to pick in and create a tracking ticket since the macOS rules don't seem to exist on this repo.

**Comment by rw-access** [comment]
howdy @hazcod looks like there aren't any macOS-only rules yet.
Some of the linux rules automatically work for macOS, but I'm not sure if we're tracking those. I think we should go through and tag those with macOS.

The linux rules are all [here](https://github.com/elastic/detection-rules/tree/main/rules/linux)
And if you want to make something mac specific, you're more than welcome to. Everything is ready, just create a folder at `rules/macos` and place your rules there.

If you don't mind, can I rename this issue to add a "macOS" tag to rules that work with macOS?

**Comment by peasead** [comment]
Hey there, @hazcod good callout.

We have several `cross-platform` rules that are in the queue, but this is a great idea. I'm working on this now.

LMK if you wanted to lean in - _many hands make light work_

**Comment by hazcod** [comment]
I'm not using the endpoint agent (yet), but will contribute if I get the chance.
Thanks guys!

**Comment by peasead** [comment]
7/1 - update

Issue itself is stale, but we have added multiple macOS rules (and continue to do so).
https://github.com/elastic/detection-rules/tree/main/rules/macos
