### ISSUE TITLE
[Bug] Unusual File Creation - Alternate Data Stream not considering offline files

### ISSUE THREAD

**Issue by jdixon-86** [elastic/detection-rules#1965]
**Describe the bug:**
It appears this query does not consider offline files which causes an alert on all the files that match the extension. Please have you security team investigate but it appears you should exclude: "C:\Windows\CSC\*\namespace\*\profiles\*\*\<filename here>:CscBitmapStream"

For example:
file.path: "C:\Windows\CSC\v2.0.6\namespace\SRV01\profiles\ryan\Desktop\cleaning bid.docx:CscBitmapStream"

**Kibana/Elasticsearch Stack version:**
8.2.0

**Server OS version:**
Ubuntu

**Browser and Browser OS versions:**
NA

**Elastic Endpoint version:**
8.2.0

**Original install method (e.g. download page, yum, from source, etc.):**
NA

**Functional Area (e.g. Endpoint management, timelines, resolver, etc.):**
Security Alerts

**Steps to reproduce:**

1. Enable offline files in windows where it caches files to c:\Windows\CSC\*

**Current behavior:**
Alerts on all file changes that match the file extension

**Expected behavior:**
Not alerting

**Screenshots (if relevant):**
![image](https://user-images.githubusercontent.com/5861587/168155080-32f75d47-d453-4902-a59d-8165bfe92709.png)

**Errors in browser console (if relevant):**
NA

**Provide logs and/or server output (if relevant):**
I can provide these privately but not on Github

**Any additional context (logs, chat logs, magical formulas, etc.):**

**Comment by w0rk3r** [comment]
I'm sorry this got lost in the repo, but I just pushed a tuning to solve it and other FP patterns: https://github.com/elastic/detection-rules/pull/3848
