### ISSUE TITLE
[Rule Tuning] Connection to Commonly Abused Web Services

### ISSUE THREAD

**Issue by PurpleV0id** [elastic/detection-rules#1966]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/command_and_control_common_webservices.toml

## Description
The exclusion for Discord is not working, it is currently
"?:\\Users\\*\\AppData\\Local\\Discord\\-*\\Discord.exe"
But from my alerts it looks as though it should be (app-*)
"?:\\Users\\*\\AppData\\Local\\Discord\\app-*\\Discord.exe"

## Example Data
![image](https://user-images.githubusercontent.com/55829496/168307422-6c88dc46-3990-4f1a-8953-6b19a99b7635.png)

**Comment by w0rk3r** [comment]
Hey @PurpleV0id, thanks for bringing this to our attention. I've opened a [PR](#1970) to update the path. Looking forward to your future contributions!
