### ISSUE TITLE
[FR] Add integration-specific query validation

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#1994]
related to #1776

As of today, queries (except lucene) are validated against ECS (with no assumptions of fields existing in the datasources). For any fields that are not validated, if filebeat exists in the `index` and a module/dataset defined in the query, a subschema of that dataset will be pulled from beats to validate the extra fields. This expands that same approach to explicitly validate integrations specific fields (as opposed to deferring to filebeat)

- [x] add `integrations.py`
- [x] update rule validators to build integrations schemas when integration indexes defined
- [x] update stack-schema-map

----

_Note: This is also an opportunity to more tightly couple rule-to-integration version validation. Many integration packages push updates to older versioned stacks, which may not align with the static approach to validate a rule based on stack mapping. (ex, aws 7.14 integration may continue to be updated, which could break rule compatibility vs the initial 7.14 integration package that accompanies the stack). Need to investigate this more as a separate issue_

**Comment by Mikaayenson** [comment]
![Untitled-2022-12-21-0927-7](https://user-images.githubusercontent.com/1636709/211406888-ab52f3d8-60eb-4748-be9e-1c231f7edf9c.png)
![Untitled-2022-12-21-0927-6](https://user-images.githubusercontent.com/1636709/211406891-7d380172-5254-41de-b226-f1eeba49a8ff.png)

**Comment by Mikaayenson** [comment]
- Window of integration to stack
- windows of valid rule to integration
- mapping intrgrations-> rules -> stack

e.g. in a given stack 8.6, aws-cloudtrail, what is the full iteration of possibility 
 - to build, of all packages, what are 8.6^ 

Q: If we find a diverge in support, how do we handle that?

Should have this conversation with the simplified working group later.

**Comment by Mikaayenson** [comment]
If we validate all compatible versions, this list will become very exhaustive (and potentially large).

 
<img width="1229" alt="Screenshot 2023-01-14 at 8 11 02 PM" src="https://user-images.githubusercontent.com/1636709/212504016-96477934-ff2f-4493-b6a1-06fa94da1e50.png">
