### ISSUE TITLE
[Rule Tuning] Creation of Hidden Files and Directories

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#2002]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/linux/defense_evasion_hidden_file_dir_tmp.toml

## Description
This rule has a chance to trigger on events that don't actually have to do with a hidden file/directory.

## Example Data

```json
"process": {
  "name": "check_snmp",
  "executable": "/usr/local/nagios/libexec/check_snmp",
  "pid": 14076,
  "working_directory": "/tmp",
  "args": [
    "/usr/local/nagios/libexec/check_snmp",
    "-H",
    "<snipped>",
    "-p",
    "161",
    "-o",
    ".1.3.6.1.4.1.674.10892.5.2.2.0",
    "-C",
    "<snipped>",
    "-P",
    "1",
    "-l",
    "SystemLCDStatus",
    "-w",
    "3",
    "-c",
    "5"
  ],
  "ppid": 26838,
  "title": "/usr/local/nagios/libexec/check_snmp -H <snipped> -p 161 -o .1.3.6.1.4.1.674.10892.5.2.2.0 -C <snipped> -P 1 -l SystemLCDS"
}
```

In this example, `.1.3.6.1.4.1.674.10892.5.2.2.0` (an SNMP OID) triggers the rule.

**Comment by shashank-elastic** [comment]
Seems to be a old issue, will recheck if some tunings have made effect or needs more.
