### ISSUE TITLE
[FR] Refactor Kibana and kql subpackages for packaging rulelib prep

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2039]
For detection-rules that has logic not within the root package, (kql, kibana) we will move those folders within the detection-rules folder as an intermediary step to moving this shared logic to the rulelib shared repo.

**Comment by brokensound77** [comment]
We may be able to close this out as not implemented

**Comment by Mikaayenson** [comment]
Closing per the last [update](https://github.com/elastic/ia-trade-team/issues/55#issuecomment-1847368223).
