### ISSUE TITLE
[Rule Tuning] Attempt to Install Root Certificate

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2108]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/macos/defense_evasion_install_root_certificate.toml

## Description

- Add exception for Bitdefender

**Comment by willemdh** [comment]
-1 => Imho this is a perfect example for an exclusions... Why this has been excluded in the query is a mystery to me. I would love to know when someone installs Bitdefender and consequently installs a root certificate. Also, why only Bitdefender, there are certainly more tools which install legit rooot certificates.
