### ISSUE TITLE
[Rule Tuning] Abnormal Process ID or Lock File Created

### ISSUE THREAD

**Issue by ynirk** [elastic/detection-rules#2110]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/linux/execution_abnormal_process_id_file_created.toml

## Description
This rule triggers a lot of noise from common legitimate files that could be added to the default filter:

 - yum.pid
 - docker.pid

**Comment by w0rk3r** [comment]
Hey @ynirk, thanks!

Here is the [PR](https://github.com/elastic/detection-rules/pull/2113)
