### ISSUE TITLE
Add ATT&CK subtechniques to the schema and relevant rules

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#215]
**Is your feature request related to a problem? Please describe.**
MITRE recently added subtechniques to ATT&CK! We should use them. 

**Describe the solution you'd like**
In https://github.com/elastic/kibana/issues/75771, I proposed the schema changes and structure.
We just need to update our `threat` mapping to match.

The structure will look like this:

* Tactic [, Tactic]
    * Technique
         * Subtechnique
    * Technique
* Tactic [, Tactic]

**Describe alternatives you've considered**
I'm not sure of any better approaches without significantly restructuring our schema.

**Additional context**
Many tactics <--> many techniques mapping in https://github.com/elastic/kibana/issues/69166 
Proposed addition to ECS  https://github.com/elastic/ecs/issues/867

We should be able to automate this migration, using https://attack.mitre.org/docs/subtechniques/subtechniques-crosswalk.json. We still need to manually or semi-automatically additional tactics, since that will become an array field.

**Comment by brokensound77** [comment]
This looks similar/redundant to #52 but with better detail. Maybe consolidate to this issue?

**Comment by rw-access** [comment]
Ah nice find. I'll close the other issue, since this one is "fresher"

**Comment by brokensound77** [comment]
resolved by #337 and #706
