### ISSUE TITLE
[FR] Better Discovery for Rules that are supported by Elastic Agent Integrations

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#2150]
**Is your feature request related to a problem? Please describe.**
Today, it is hard to know if a rule is covered by an Elastic Agent integration and what integration(s) without looking at each rule individually to find out what indices/data sets it uses. With 700+ rules now (and growing), this isn't really a scalable solution.

**Describe the solution you'd like**
I would like to see a way (possibly via tagging) that shows 2 things:
1. Does the rule have a related Elastic Agent Integration(s) or do I need to use a traditional Beat
2. What Elastic Agent Integration(s) do I need for this rule to work
     - I don't think listing any sub-parts of an integration would be useful from a high-level and probably could be relegated to the rule description.

I think you could have a tag on a rule, like `Elastic Agent` if there is an integration(s) that supports this rule. (And maybe a `Beats Only` tag if it only has a Beats module support?)

You could also possibly add a tag(s) with the integration name, though this might cause an explosion of tags and may not be ideal.

**Describe alternatives you've considered**
I've tried to look through the rules one by one, and while this does "work", it takes significant time, and if there are updates to rules, they need to be re-checked to see if anything changed that might allow for new coverage.

**Additional context**
I'm trying to replace traditional Beats with Elastic Agent integrations, but it's time consuming to look through each rule to try and determine this information.

**Comment by Mikaayenson** [comment]
Hey @BenB196 Thanks for opening the issue. We are actively working on this issue and should have a merged PR within a week or so. Ref: https://github.com/elastic/detection-rules/pull/2060
