### ISSUE TITLE
[Bug] Opening Issues in this Repo Causes "Run failed: Community - main"

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#2151]
**Describe the bug**
If I open an issue in this repo, I get an email from GitHub with the error: "Run failed: Community - main"

**To Reproduce**
1. Open an issue on this repo (probably need to not be a member/contributor)
2. Get an email from GitHub about a failed workflow.

**Expected behavior**
I expect to not get a failed workflow email for just opening an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/8277432/180474594-cf0dfb09-97fb-40ba-810a-f8c9d5711050.png)

**Comment by TotalKnob** [comment]
The same script has been throwing errors on pull_request_target.

Link to example failure on issue: https://github.com/elastic/detection-rules/actions/runs/2734969722
"" on PR: https://github.com/elastic/detection-rules/actions/runs/2735000574

**Comment by Mikaayenson** [comment]
This should be resolved once the PR merges.
