### ISSUE TITLE
[Rule Tuning] MacOS Installer Package

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2189]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/macos/execution_installer_spawned_network_event.toml

## Description

This rule logic is flawed. I spent yesterday afternoon executing every installer package payload [Mystikal](https://github.com/D00MFist/Mystikal) has to offer along with various other malicious [packages](https://redcanary.com/blog/clipping-silver-sparrows-wings/) and this rule did not fire once. The problem with the rule is in the way the process tree spawns with installer packages preventing sequencing on process.entity_id as the child processes spawned from installer or package_script_service are not linked directly by process id and therefore cannot be connected together via the process.entity_id. This will prevent the rule from ever firing. 

The rule name, description and logic needs to be updated to the following in order to successfully detect the activity in its entirety. 

Name : MacOS Installer Package Network Event

Description : Detects the execution of a MacOS installer package with an abnormal child process (e.g bash) followed immediately by a network connection via a suspicious process (e.g curl). Threat actors will build and distribute malicious MacOS installer packages, which have a .pkg extension, many times imitating valid software in order to persuade and infect their victims often using the package files (e.g pre/post install scripts etc.) to download additional tools or malicious software. If this rule fires it should indicate a the installation of a malicious or suspicious package.

```sql
sequence by host.id, user.id with maxspan=1m
[process where event.type == "start" and process.parent.name : ("installer", "package_script_service") and process.name : ("bash", "sh", "zsh", "python", "osascript", "tclsh*")] 
[network where event.type == "start" and process.name : ("curl", "osascript", "wget", "python")] 
```

## Example Data

<img width="1634" alt="Screen Shot 2022-07-27 at 12 19 27 PM" src="https://user-images.githubusercontent.com/48036388/181361901-659e8184-4cd3-4120-ad46-54045ff89929.png">

**Comment by Mikaayenson** [comment]
@DefSecSentinel What about:
- DR: https://github.com/elastic/detection-rules/blob/main/rules/macos/execution_installer_spawned_network_event.toml
- ER: https://github.com/elastic/endpoint-rules/blob/main/rules/execution_network_connection_initiated_by_installer.toml

**Comment by DefSecSentinel** [comment]
@Mikaayenson both of those rules are flawed. I spent yesterday afternoon executing every installer package payload [Mystikal](https://github.com/D00MFist/Mystikal) has to offer along with various other malicious [packages](https://redcanary.com/blog/clipping-silver-sparrows-wings/) and neither of these rules fired once. The problem with the above rules is multiple. First, the way the process tree that spawns with installer packages prevents sequencing on process.entity_id as the child processes spawned from installer or package_script_service are not linked directly by process id and therefore cannot be connected together via the process.entity_id. This will prevent both rules from ever firing. Second, for the ER the network.direction field is auditbeat specific it appears and without auditbeat data the rule will never fire either.

**Comment by DefSecSentinel** [comment]
@Mikaayenson both of these rules should be deprecated and replaced with my rule which effectively detects the activity in its entirety.

**Comment by Mikaayenson** [comment]
@DefSecSentinel That makes sense. I did see some [activity](https://elastic.slack.com/archives/CP92S0JJK/p1658476790261419) that was triggered when Andy tried to execute a sample for me.
