### ISSUE TITLE
[Rule Tuning] Persistence via Update Orchestrator Service Hijack

### ISSUE THREAD

**Issue by imays11** [elastic/detection-rules#2194]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_via_update_orchestrator_service_hijack.toml

## Description

Decrease FPs by adding exceptions for MoUsoCoreWorker.exe and UsoCoreWorker.exe

This rule has triggered 2,580 times in the last 24 hours (7/26/22-7/27/22); 2,555 of which were triggered by MoUsoCoreWorker.exe
Over the last 2 months clients have made an exception to this rule for this executable 1,767 times. 

MoUsoCoreWorker.exe or USOCoreWorker.exe are replacement programs for the wuauclt.exe command in Windows 10. The programs are Update Session Orchestrators (USO) - A Windows OS component that orchestrates the sequence of downloading and installing various update types from Windows Update. The MoUSO Core Worker Process runs in the background and does not affect any other process that a user is running. However, this process can use a high memory in some cases due to some errors in downloading or installing an update (which is probably why we're seeing it so often in telemetry).

https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-overview
https://docs.microsoft.com/en-us/windows/deployment/update/how-windows-update-works
https://www.technewstoday.com/mouso-core-worker-process/

**Comment by Mikaayenson** [comment]
We should probably exclude ` OfficeC2RClient.exe` as well.
