### ISSUE TITLE
[New Rule] AWS root account used

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#223]
## Description
This rule should detect when the root acount in aws is used to make api calls. The root account has unlimited authorizations
within an account and should be used as less as possible. Making it a valid reason to investigate when it's used.

This rule does overlap with [AWS Root Login Without MFA](https://github.com/elastic/detection-rules/blob/main/rules/aws/privilege_escalation_root_login_without_mfa.toml), but I do feel like it adds value as root shouldn't be used at all.

## Required Info

- **Eventing Sources:**
Filebeat index. [aws module, cloudtrail dataset](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-aws.html#_cloudtrail_fileset)

- **Target Operating Systems:**
n/a

- **Platforms**
cloudtrail

- **Target ECS Version:** 
1.6
- **New fields required in ECS for this?**
no
- **Related issues or PRs**

## Optional Info
- **References:**
[The AWS Account Root User](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html)

## Example Query
`event.module:aws and event.dataset:aws.cloudtrail and event.provider:signin.amazonaws.com and event.action:ConsoleLogin and aws.cloudtrail.user_identity.type:Root and event.outcome:success`

**Comment by bm11100** [comment]
Hey @SHolzhauer, thanks for reaching out! I completely agree with you, that the Root user should be scrutinized. We do have one more Root login rule that looks for successful Root login activity regardless of MFA status. If you take a look at the rule named [AWS Management Console Root Login](https://github.com/elastic/detection-rules/blob/main/rules/aws/initial_access_console_login_root.toml), it should cover this scenario.

**Comment by SHolzhauer** [comment]
Woops, missed that one. Sorry about that
