### ISSUE TITLE
[Rule Tuning] Microsoft 365 Inbox Forwarding Rule Created

### ISSUE THREAD

**Issue by MichalMarchewka** [elastic/detection-rules#2239]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/integrations/o365/collection_microsoft_365_new_inbox_rule.toml

## Description
Rule is missing "Set-InboxRule" when the inbox rule is modified, not created. Please consider renaming the detection rule to "Microsoft 365 Inbox Forwarding Rule Created or Modified" or creating new detection rule: "Microsoft 365 Inbox Forwarding Rule Modified"

New suggested query: 
event.dataset : o365.audit and (o365.audit.Parameters.RedirectTo : * or o365.audit.Parameters.ForwardAsAttachmentTo : * or o365.audit.Parameters.ForwardTo : *) and (event.action : "New-InboxRule" or "Set-InboxRule") and event.outcome : "success"

![rule01](https://user-images.githubusercontent.com/56821715/184845978-bf1c9580-f1d5-4e73-ab18-765e17266fdf.png)
![rule02](https://user-images.githubusercontent.com/56821715/184845993-394425db-c6aa-4a76-a737-dece77b70452.png)

**Comment by w0rk3r** [comment]
Hey @MichalMarchewka, thanks for bringing this to our attention. Could you provide us a sample *redacted* event?

**Comment by MichalMarchewka** [comment]
Hey @w0rk3r, sure. Json saved as txt
[sample.txt](https://github.com/elastic/detection-rules/files/9350955/sample.txt)

**Comment by w0rk3r** [comment]
Hey @MichalMarchewka, thanks for spotting and reporting this, here is the [PR](https://github.com/elastic/detection-rules/pull/2240) to fix this one.

Looking forward to your next awesome contributions!
