### ISSUE TITLE
[Rule Tuning] AWS Root Login Without MFA severity

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#224]
## Description
I propose to change the severity and risk values for the [AWS Root Login Without MFA](https://github.com/elastic/detection-rules/blob/main/rules/aws/privilege_escalation_root_login_without_mfa.toml) rule.

| property | current value | proposed value |
|------------|---------------|------------|
| severity | low | medium |
| risk | 21 | 30 |

**Reasoning**
As stated by AWS:
>If you continue to use the root user credentials, we recommend that you follow the security best practice to enable multi-factor authentication (MFA) for your account. Because your root user can perform sensitive operations in your account, adding an additional layer of authentication helps you to better secure your account. 

Due to the nature of the account, it should always be protected with 2FA, if someone is able to authenticate without using 2FA this should be investigated.

**Comment by bm11100** [comment]
Hey @SHolzhauer! I agree with you. I think anything involving the Root user in AWS should be at least Medium, potentially even High. We typically use the value of `47` for Medium and `73` for High. I can open a PR to update the severity for this rule. Thanks for your input!

**Comment by SHolzhauer** [comment]
@bm11100 maybe high severity and risk of 47?

**Comment by bm11100** [comment]
I'm thinking since best practices state to always enable MFA with the Root identity, if it does not have MFA, that will be a high risk if compromised. I opened a PR to update the severity to High and risk to 73.
