### ISSUE TITLE
[Rule Tuning] Unusual Network Activity from a Windows System Binary

### ISSUE THREAD

**Issue by twanva** [elastic/detection-rules#2241]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_network_connection_from_windows_binary.toml

## Description
Severity and risk score don't match. Is this on purpose? 

## Example Data
![image](https://user-images.githubusercontent.com/19820556/185063684-054d2911-a703-4fe4-88d9-3712511fe8de.png)

**Comment by w0rk3r** [comment]
Hey @twanva, thanks for bringing this to our attention. I've inspected our ruleset and found some other occurrences; this [PR](https://github.com/elastic/detection-rules/pull/2242) aims to standardize these values across the ruleset.

We are looking forward to your next contributions! Let me know if you find something else.
