### ISSUE TITLE
[FR] Update Integrations Manifest to Include Endpoint and NPC

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2269]
## Description

In 8.3, we added new build-time fields to our rules, specifically `required_fields`,`related_integrations`,`setup`. This feature request focuses solely on the `related_integrations` field.

At this time to determine which integrations to build the integrations manifest file, we rely on the integrations folder to determine this and then reference these names in package-storage. For matching, we rely solely on `event.dataset` fields in these integration queries

The issue:
We do not include the endpoint integration to this integrations manifest. In addition, we cannot rely on `event.dataset`, we need to look for the `logs-endpoint*` index for this.

The second part is any network rules. We need to upgrade all network rules to work on the NPC integration and then move this folder into integrations so it get's picked up by the already existing build integrations process.

The solution:
- [x] Adjust how integrations are determined during build integration manifest process, from folders to integration tag | https://github.com/elastic/detection-rules/pull/2274
    - Add a `^` to each value so Kibana knows this version and above. We need to address if a major is different as well because these will not match.
- [x] Update all metadata integration tags in rules |
    - Add `network_traffic` integration tag to all network rules 
    - Add `endpoint` integration tag to all rules with `logs-endpoint` in them
    - Add `apm` integration tag to all APM rules
    - If `winlogbeat-*` and not `logs-endpoint*` add `windows` integration tag
- [x] Update rules where `logs-*` is the only index pattern | 
- [x] Add unit test to check index and event.dataset to ensure integration tag is set | 
- [x] Adjust code logic to include any core OS where index includes `logs-endpoint*` use the endpoint integration reference | 
- [ ] Lock versions | 
- [ ] v8.7.1 package release | 

Stretch Goals:
- [ ] Finish this issue for network-based rules | https://github.com/elastic/detection-rules/issues/2200

**Comment by terrancedejesus** [comment]
@w0rk3r do you know by chance which integration is required for sysmon events? Is it the Custom Windows Event Logs integration? If so, which index does that require `winlogbeat-*`?

**Comment by w0rk3r** [comment]
Sysmon Events are collected using the Windows integration (https://github.com/elastic/integrations/tree/main/packages/windows) and `winlogbeat-*` is the default index for data collected using beats and not the elastic agent (https://www.elastic.co/downloads/beats/winlogbeat)

**Comment by brokensound77** [comment]
Thinking through this, any endpoint or network rule that has no change but will include the autogenerated `related_integrations` field would _not_ automatically get a version bump (as it would require). Ensuring the _all_ of these effected rules get updated with:

> Update all metadata integration tags in rules |

_should_ address this by causing a version bump from the tag update. This would backport to 8.3, where all versions would get an increment on the 100+ version. This sounds like it should address it completely, but may be worth verifying my assumptions

**Comment by terrancedejesus** [comment]
#### Update 12-13-2022
Bumping priority on this as the intended target is 8.7 release with these changes, meaning they should be available in `v8.5.2` and `v8.7.1` packages.
