### ISSUE TITLE
[Bug]ML Job for AWS rules need to support logs-aws* index pattern 

### ISSUE THREAD

**Issue by amarzana** [elastic/detection-rules#2279]
**Describe the bug**
ML Job for `AWS` need to support more variation of indices. Currently only supports `filebeat-*` only.
ML Job for `AWS` rules need to support `logs-aws*`. 

Rules:
- Unusual AWS Command for a User
- Spike in AWS Error Messages
- Unusual Country For an AWS Command
- Unusual City For an AWS Command
- Rare AWS Error Code

**To Reproduce**
1. Go to 'Machine Learning'
2. Click on 'Job->Datafeed'
3. See `indices`

![image](https://user-images.githubusercontent.com/6897714/187349081-bb0fdc3e-54bd-4b8c-8408-46c8aadfecb1.png)

**Expected behavior**
ML Job indices need to process below patterns
- `filebeat-*`
- `logs-aws*`

**Screenshots**
- Rules
![image](https://user-images.githubusercontent.com/6897714/187345968-5312c006-a1c5-4964-9cab-29f7771b0df1.png)
- 

**Desktop (please complete the following information):**
 - OS:N/A
 - Version: Elastic v8.4.0

**Additional context**
Nothing

**Comment by w0rk3r** [comment]
@jamesspi just a reminder for when you get a few minutes

**Comment by jamesspi** [comment]
Hi,

Here are the steps to update the data feed.

1. Stop the data feed(s) in question

<img width="864" alt="image" src="https://user-images.githubusercontent.com/20421688/196459042-ae991c67-10fb-45bf-b5d7-127888ea252e.png">

2. In Dev tools, for each ML job, update the datafeed like so (if filebeat isn't needed at all, it can be omitted). The datafeeds follow the following naming convention - `datafeed-<job_name>`:

```
POST _ml/datafeeds/datafeed-high_distinct_count_error_message/_update
{
  "indices": [
        "logs-aws*","filebeat*"
      ]
}
```

3. Restart the jobs from the Security or ML UI
