### ISSUE TITLE
Issues with detection rules

### ISSUE THREAD

**Issue by antonino-tocco** [elastic/detection-rules#2316]
Hi, I have tried to install elk with a fleet server and the prebuilt rules integration.
I simulate the mimikatz misc::memssp on a host and generate the mimilsa.log file, but no alerts was triggerer.
I also receive warning with all the endgame rules.

Can you help me?

**Comment by Mikaayenson** [comment]
Hi @antonino-tocco, can you share some details / screenshots about your setup?

For starters:
- What version are you running?
- Can you provide screenshots of your endpoints `https://<stack-url>/app/security/administration/endpoints`
- Can you provide screenshots of your policy `https://<stack-url>/app/security/administration/policy/<policy id>/settings`
- Can you provide screenshots of your rules enabled `https://<stack-url>/app/security/rules`

**Comment by antonino-tocco** [comment]
Hi, I run version 8.4.0 of the ELK stack. When I go to https://<stack-url>/app/security/administration/endpoints it seems that no agents are enrolled and it give me the list of policy for enrollment.
![Immagine 2022-09-21 170039](https://user-images.githubusercontent.com/12016054/191539998-75b553ff-869b-42ba-93ba-85ef72dd04ce.png)
I have multiple policies for different type of agents as windows agents. I have enabled multiple integrations such as "Endpoint security" and "Prebuilt rules". Also you find attached Mimikatz rules enabled screenshots.
![Immagine 2022-09-21 170507](https://user-images.githubusercontent.com/12016054/191540911-5b716f8e-6ab7-4907-8c6d-33e316728deb.png)
.
![Immagine 2022-09-21 170529](https://user-images.githubusercontent.com/12016054/191540916-45fc8dfa-0fe3-42d9-9e8a-2948b8b99dfb.png)

![Immagine 2022-09-21 170255](https://user-images.githubusercontent.com/12016054/191540896-e561fedc-658c-46b1-8b2d-d64018937294.png)
![Immagine 2022-09-21 170336](https://user-images.githubusercontent.com/12016054/191540907-27d3c5c7-cf90-4990-ada1-575ea485bbaa.png)

**Comment by Mikaayenson** [comment]
You need to enroll an endpoint system. Try installing the agent on the system where you're running mimikatz.

**Comment by antonino-tocco** [comment]
I have already do it but nothing changed. No notification. The agent was successfull installed.
![Immagine 2022-09-21 220041](https://user-images.githubusercontent.com/12016054/191599903-bf5262d4-94be-417d-8a8e-9e2d8c29b528.png)
![Immagine 2022-09-21 220156](https://user-images.githubusercontent.com/12016054/191599906-bfea337f-cde8-42a1-a368-eb1a201bc350.png)

**Comment by Mikaayenson** [comment]
Looking at all the screenshots you've provided, it appears that the reason you're not receiving alerts is because your windows endpoints are having issue. For the unhealthy endpoint, can you share a `policy status` screenshot on from `https:///app/security/administration/endpoints `?

It should look something like this:

<img width="765" alt="Screen Shot 2022-09-21 at 7 33 26 PM" src="https://user-images.githubusercontent.com/1636709/191627869-4f1170ff-6bbe-414a-a0fa-ecbe1bed832f.png">


If its not `success`, there should be errors within the policy indicating the actual issue.

**Comment by antonino-tocco** [comment]
Hi, when I go to  https:///app/security/administration/endpoints no
endpoints showed but only a sreen for add agent.



Il giorno gio 22 set 2022 alle ore 01:34 Mika Ayenson <
***@***.***> ha scritto:

**Comment by antonino-tocco** [comment]
Hi, my agents is healty at this moment but this screen always show no endpoints.I start receive alerts from other host for other rules but not for mimikatz on this host. I can’t test mimikatz on the other hosts  Inviato da Posta per Windows Da: entony toccoInviato: giovedì 22 settembre 2022 08:39A: elastic/detection-rulesCc: elastic/detection-rules; MentionOggetto: Re: [elastic/detection-rules] Issues with detection rules (Issue #2316) Hi, when I go to  https:///app/security/administration/endpoints no endpoints showed but only a sreen for add agent.   Il giorno gio 22 set 2022 alle ore 01:34 Mika Ayenson ***@***.***> ha scritto:Looking at all the screenshots you've provided, it appears that the reason you're not receiving alerts is because your windows endpoints are having issue. For the unhealthy endpoint, can you share a policy status screenshot on from https:///app/security/administration/endpoints ?It should look something like this:If its not success, there should be errors within the policy indicating the actual issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Mikaayenson** [comment]
Can you describe what happens when you try running the mimikatz test on one of the healthy windows endpoints? 

Also did you run the command together `mimikatz misc::memssp` or did you spawn mimikatz and then run `misc::memssp`. The former should work on an 8.4.0 stack based on our internal testing. We receive an alert based on the rule [Potential Credential Access via Mimikatz](https://github.com/elastic/protections-artifacts/blob/main/behavior/rules/credential_access_potential_credential_access_via_mimikatz.toml) as a `Malicious Behavior Detection Alert`

**Comment by terrancedejesus** [comment]
Hello @antonino-tocco!

We took some time to setup a lab environment with the requirements to run `mimikatz misc::memssp` and trigger and Elastic security rule alert. I'll try my best to explain how we did so.

### Setup
For the setup, I used a Windows Server 2019 image and deployed a cloud-based stack with version 8.4.1. Using Fleet, I created an agent policy called `endpoint`.

<img width="1222" alt="Screen Shot 2022-09-22 at 5 06 52 PM" src="https://user-images.githubusercontent.com/99630311/191851113-e08508da-63f0-492f-b863-bb9a6648cae3.png">

I then added the "Endpoint and Cloud Security" integration to this policy. This integration allows us to use detection rules from the Protections Artifacts [repository](https://github.com/elastic/protections-artifacts/tree/main/behavior) where we have a rule that should detect `mimikatz misc:memssp` when executed. @Mikaayenson pointed out this rule in the previous comment.

<img width="1141" alt="Screen Shot 2022-09-22 at 5 09 45 PM" src="https://user-images.githubusercontent.com/99630311/191851524-a5d503ed-84cd-4005-aa20-a77278faa413.png">

As you did, I then deployed an Elastic agent to my Windows Server 2019 host with my endpoint policy that uses the "Endpoint and Cloud Security" integration.

I also made sure I updated the endpoint security policy settings by visiting Security > Manage > Policies > endpoint. In here, I made sure every protection level was set to "Detect" and not "Prevent", especially "Malicious behavior".

<img width="1684" alt="Screen Shot 2022-09-22 at 5 14 25 PM" src="https://user-images.githubusercontent.com/99630311/191852209-bf2062b0-f3cc-4cde-ab1b-59c2335b160f.png">

By the end of this, I made sure the agent on my Windows Server 2019 host was in a "Healthy" status to ensure logs were being ingested properly. Sometimes unhealthy agents need updates, re-installed or security settings on the host itself need to be reviewed.

<img width="1612" alt="Screen Shot 2022-09-22 at 5 15 39 PM" src="https://user-images.githubusercontent.com/99630311/191852586-4a487f5b-b6be-46ad-b7d7-7aeda2e044d5.png">

Also, when setting up my Windows Server 2019 host, I made sure to disable any security protections it had such as Windows Defender, Virus Protection, etc. as these often block certain actions necessary to trigger these alerts.

### Rule Managing
For rules, you will notice if you search for "mimikatz" in Security > Manage > Rules, a detection rule does exist, called "Mimikatz Memssp Log File Detected", so I made sure it was enabled. If you select the rule you want to trigger, you will notice data sourced to trigger this rule comes from the Endpoint and Cloud Security integration based on the index pattern it checks for documents in.

<img width="1618" alt="Screen Shot 2022-09-22 at 5 17 42 PM" src="https://user-images.githubusercontent.com/99630311/191853011-7a782615-9996-4e13-a30d-bb5f39cc3631.png">


### Triggering Mimikatz Rule

I downloaded Mimikatz from the Github [repository](https://github.com/ParrotSec/mimikatz) onto my Windows Server 2019 host, unzipped the files and then ran the following from a PowerShell console with administrative privileges.

`.\mimikatz.exe misc::memssp`
`cmd.exe -c mimikatz.exe misc::memssp`

<img width="700" alt="Screen Shot 2022-09-22 at 5 21 44 PM" src="https://user-images.githubusercontent.com/99630311/191853379-f2afbc28-4be9-4bdc-b899-d9b5ad17fcba.png">

The time it takes for the alert to trigger is based on how often the rule is run which can be determined by reviewing the rule itself so we knew it would be about ~5 minutes before an alert was triggered.

<img width="1611" alt="Screen Shot 2022-09-22 at 5 23 42 PM" src="https://user-images.githubusercontent.com/99630311/191853746-c5183b46-8d20-445d-96ca-85b875dea08a.png">

When checking Security > Alerts I used a KQL filter for any Mimikatz rule names that may have triggered and saw that we have a few alerts.

<img width="1125" alt="Screen Shot 2022-09-22 at 5 26 47 PM" src="https://user-images.githubusercontent.com/99630311/191854100-fea4b447-f613-43d0-a401-cdae0b3d8de0.png">

If these alerts do not trigger you can also search Discover to check for the documents by visiting Analytics > Discover and searching for `*mimikatz*` to find any documents with mimikatz references, mainly the `process.name` itself. You can also search for `file.name: mimilsa.log` as well just make sure your data-view selected is `logs-*`.

<img width="2117" alt="Screen Shot 2022-09-22 at 5 30 28 PM" src="https://user-images.githubusercontent.com/99630311/191854645-bda3c379-fa04-40de-85cf-db9876e65aab.png">

I do hope this helps but please continue to let us know if you have questions and we will continue to attempt in helping!

**Comment by antonino-tocco** [comment]
Hi, I want to try to use the protection-artifacts rules but when I try to upload or export the rules with the detection_rules package, I receive this error: marshmallow.exceptions.ValidationError: {'rule': [ValidationError({'type': ['Missing data for required field.'], 'author': ['Missing data for required field.']. Can you help me?

**Comment by Mikaayenson** [comment]
@antonino-tocco Those rules are for the endpoint-sensor (and not the SIEM), so they are already in use within the agent that you installed on your VMs. You can always [create a custom rule](https://www.elastic.co/guide/en/security/current/rules-ui-create.html) in the SIEM for testing purposes with similar logic, but again the protections-artifacts are already enabled and running. 

Feel free to reopen this issue if you have any other issues with your setup!
