### ISSUE TITLE
[Rule Tuning] Screensaver Plist File Modified by Unexpected Process

### ISSUE THREAD

**Issue by aarju** [elastic/detection-rules#2330]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/macos/persistence_screensaver_plist_file_modification.toml

## Description

In it's current form we are seeing a very high number of false positives for this rule making it unusable. The false positives are caused when our MDM system (jamf) enforces the screensaver lockout and time policies on the macs. If the system doesn't have a screensaver enabled with a lockout timer then jamf will modify the screensaver plist file to enable it. The chain of events are `jamf executes -> jamf bash script runs -> jamf runs a sh cp command`. Because `cp` is used to overwrite the screensaver plist file each time so we can't filter by `process.executable`.

## Recommendation
I recommend that the logic of the rule be updated (or a new rule be created) to instead of focusing on file actions with the plist file to alert to strange child processes of `ScreenSaverEngine` or `legacyScreenSaver`. As described in https://posts.specterops.io/saving-your-access-d562bf5bf90b these are the processes that will execute the commands defined in the malicious plist files.

Looking through our fleet of MacOS endpoints I see zero events in the last 30 days where `process.parent.name: "ScreenSaverEngine"`
The `legacyScreenSaver` process executes itself regularly along with occasionally other processes from different custom screensaver applications so it could require some exception tuning by each customer for the more common screensaver applications allowed in their environment.  `process.parent.name:"legacyScreenSaver" and not process.name:"legacyScreenSaver"`

**Comment by w0rk3r** [comment]
@DefSecSentinel @Mikaayenson could you guys take a look on this one?

**Comment by Mikaayenson** [comment]
Sure thing. I see the rule already references the link that Aaron mentioned, but ill take a closer look.
