### ISSUE TITLE
[FR] Add Fork Context to Version Lock

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2333]
**Is your feature request related to a problem? Please describe.**

When we fork rules, we store the previous version information in our `version_lock.json` file. For example 

```json

 "max_allowable_version": 99,
 "rule_name": "Rule Name",
 "sha256": "hash",
 "type": "eql",
 "version": 4

```

We then update the toml file with new metadata. For example

```toml

min_stack_comments = "Description of why we min_stacked"
min_stack_version = "8.3.0"

```
However, we don't store that information in the lock_file.

**Describe the solution you'd like**

Now that we've locked all of our rules at 8.3.0, we should begin to the min_stack_comments to the version_lock to preserve the historical information (if it exist). That way we can ensure (unit test) rules are receiving comment updates when we bump the rule min_stack, and it makes it easier to track progress of rules across many branches.

```json

 "max_allowable_version": 99,
 "min_stack_comments":  "Description of why we min_stacked"
 "rule_name": "Rule Name",
 "sha256": "hash",
 "type": "eql",
 "version": 4

```

**Describe alternatives you've considered**
We should about adding previous_locks and potentially adding previous_lock information to the toml file, but we've punted this idea for now. https://github.com/elastic/detection-rules/pull/1946#discussion_r977109548

**Additional context**
In https://github.com/elastic/detection-rules/pull/2272 we added the "max_allowable_version". We should add a new field similar to this.

**Comment by Mikaayenson** [comment]
In the progress of spot checking the concept and ran across at least one rule:

- https://github.com/elastic/detection-rules/blob/8.4/rules/integrations/google_workspace/collection_google_drive_ownership_transferred_via_google_workspace.toml

This rule was min_stacked at 8.3 and has the correct min_stacked comments:

```
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
```

However, it was min_stacked again at 8.4 and the comments were not updated. 

@terrancedejesus @eric-forte-elastic @brokensound77 Do we want to add duplicate comments into the lock file? We probably should add the redundancy.

**Comment by terrancedejesus** [comment]
> We could add a unit test moving forward to check for this (but we'd want the lock file in place to enable this unit test).

I do not quite understand the "lock file in place to enable this unit test" statement? This requires we update the version lock schema in `version_lock.py` where it expects a type `str`. From here, we could add an assertion to check if the previous and current comments are the same and if so, fail. Thoughts?

**Comment by Mikaayenson** [comment]
> I do not quite understand the "lock file in place to enable this unit test" statement? This requires we update the version lock schema in `version_lock.py` where it expects a type `str`. From here, we could add an assertion to check if the previous and current comments are the same and if so, fail. Thoughts?

It's just a thought. I like the comment in the lock file for historical purposes. If we do add it, then we can add a unit test to check and make sure that when we bump the min version, the update also will include changes to the comment.

**Comment by Mikaayenson** [comment]
Removing from the meta and sending to backlog. Given we have 7 working days until FF, and this no longer affects the historical rules meta based on our discussions.

**Comment by Mikaayenson** [comment]
At some point we will migrate docs to docs.elastic.co. Ideally this is when we would prioritize this. We have the `min_stack_comments` which is great for the current rule, but as soon as we fork, we loose this information so yes we still need to do it.

**Comment by Mikaayenson** [comment]
Now that we officially have started the process of trimming the version lock, we will ultimately loose this context. We also haven't needed to do any deep investigation over the last 6 mo requiring historical context, so we can close this.
