### ISSUE TITLE
Add command/workflow for testing OOB releases

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#2334]
Explore leveraging the `elastic-package` go utility to enhance testing during OOB releases and integrate it into a workflow for simplicity

- [ ] new cli command: `dev integrations test e2e-upgrade`
- [ ] workflow for executing the command
- [ ] new cli command: `dev integrations check-changes <src branch> <target cdn release>`
    - [ ] integrate it as part of the above workflow 

![image](https://user-images.githubusercontent.com/16747370/193353765-430e8c99-1af8-4515-b56a-0268046cf5e6.png)

### Resources
- https://www.elastic.co/guide/en/integrations-developer/current/testing-and-validation.html
- https://github.com/elastic/elastic-package/blob/main/docs/howto/system_testing.md
- https://www.elastic.co/guide/en/integrations-developer/current/testing.html
- https://www.elastic.co/guide/en/integrations-developer/current/system-testing.html

**Comment by brokensound77** [comment]
depending on implementation, may have dependency on #2335 resolution

**Comment by terrancedejesus** [comment]
Package-Storage v2 is live and currently being used when merging PRs into Integrations repository. This process does not use the elastic-package Go binary as promotions no longer exist. All packages go to production EPR and installed updates depend on prerelease tags or not. 

Reference: https://github.com/elastic/ia-trade-team/issues/17
