### ISSUE TITLE
Update Kibana Directory Reference for Pre-Built Rules from "kibana-pr" Command

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2366]
#### Related Issue
* https://github.com/elastic/kibana/pull/142950

#### Summary
Kibana has pending changes in which the location of the pre-built rules will be adjusted. During release, we rely on `kibana-pr` command from `devtools.py` to update the rules in the Kibana repository locally before pushing these changes to Kibana in a separate PR. With the changes expected from the related issue noted above, we need to adjust the target of the Kibana directory being referenced.

* Old target: `x-pack/plugins/security_solution/server/lib/detection_engine/rules/prepackaged_rules/*`
* New target: `x-pack/plugins/security_solution/server/lib/detection_engine/prebuilt_rules/content/prepackaged_rules/*`

This issue and PR should be completed after [#142950](https://github.com/elastic/kibana/pull/142950) is completed for testing locally.

**Comment by banderror** [comment]
@terrancedejesus Sorry for the delayed ping, I just realized that we merged the original PR https://github.com/elastic/kibana/pull/142950 but I never let you know about that. Our app is ready for the corresponding changes to be made in the detection-rules repo.

**Comment by terrancedejesus** [comment]
Fix was implemented in #2397 to update Kibana path.
