### ISSUE TITLE
[Rule Tuning] Windows Defender Disabled via Registry Modification

### ISSUE THREAD

**Issue by kenza-irba** [elastic/detection-rules#2380]
## Link to rule
https://www.elastic.co/guide/en/security/current/windows-defender-disabled-via-registry-modification.html#windows-defender-disabled-via-registry-modification

## Description
Hello everyone, 

We tried to test **Windows Defender Disabled via Registry Modification** detection rule and we noticed that this rule doesn't generate alerts when we follow the steps mentioned below :
1. Create **DisableAntiSpyware** registry key
2. Put the **DisableAntiSpyware** value at 1

After logs monitoring, we noticed that the alerts were not generated because the event of value change (step 2) was not generated. We noticed that only a creation event log was generated. To cover this gap we used this detection rule instead the one existing in elastic website: 

`registry where event.type in ("creation", "change") and ( (
registry.path:"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows
Defender\\DisableAntiSpyware" ) or (
registry.path:"HKLM\\System\\*ControlSet*\\Services\\WinDefend\\Start"
and registry.data.strings in ("3", "4", "0x00000003",
"0x00000004") ) )
`

We removed **`registry.data.strings: ("1","0x00000001")`** check to be sure that all the alerts are generated.

Thanks.

**Comment by w0rk3r** [comment]
Sorry for taking this long, but I've tested creating the key and setting a value using the following:

```
reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntiSpyware /d 1
```

Both creation and modification events were generated, and the query triggered the behavior. Closing this, but feel free to reopen if needed.
