### ISSUE TITLE
[FR] Elastic Defend name adoption

### ISSUE THREAD

**Issue by approksiu** [elastic/detection-rules#2390]
**Is your feature request related to a problem? Please describe.**
Elastic Endpoint Security has its name changed to Elastic Defend in 8.5. We should update the Endpoint rule to be easier for users to find it and understand it is related to Elastic Defend integration.

**Describe the solution you'd like**

1. Add "Elastic Defend" tag to this rule https://github.com/elastic/detection-rules/blob/main/rules/integrations/endpoint/elastic_endpoint_security.toml 
2. Update the rule description with the new integration name. 
3. Rename this rule's folder on github.
4. Update other rules to use Elastic Defend in descriptions instead of Elastic Endpoint Security.

**Comment by terrancedejesus** [comment]
Let's save these changes for the 8.8 minor release as any changes will backport and based on our current-3, it will only backport to 8.5. Changing the folder name should not have any consequences, but descriptions in other rules, endpoint rule changes and so fourth will backport to 8.4 at the 8.7 release.

**Comment by w0rk3r** [comment]
@approksiu can we close this one?

**Comment by approksiu** [comment]
@w0rk3r good call, thanks. Closing the issue.
