### ISSUE TITLE
[Rule Tuning] Suspicious File Creation in /etc for Persistence - add exception for snapd

### ISSUE THREAD

**Issue by ScottElastic** [elastic/detection-rules#2392]
## Link to rule
Suspicious File Creation in /etc for Persistence

## Description
file where event.action == "creation" and user.name == "root" and file.path : ("/etc/ld.so.conf.d/*", "/etc/cron.d/*", "/etc/sudoers.d/*", "/etc/rc.d/init.d/*", "/etc/systemd/system/*") and not process.executable : ("*/dpkg", "*/yum", "*/apt", "*/dnf", "*/systemd")

Running Ubuntu 18.04 LTS on GCP this rule fires off from auto-updates, for ex: 

file event with process snapd , file snap-google\x2dcloud\x2dcli-87.mount.bGSfyNvgDVq7~ , by root on cyberdyne-rf created medium alert Suspicious File Creation in /etc for Persistence . root @ cyberdyne-rf created a file snap-google\x2dcloud\x2dcli-87.mount.bGSfyNvgDVq7~ in /etc/systemd/system/snap-google\x2dcloud\x2dcli-87.mount.bGSfyNvgDVq7~ via snapd (27272)

## Example Data
Suggest adding an exception for "*/snapd" as well.

**Comment by shashank-elastic** [comment]
Will cover this as part of the issue #2348 
cc @DefSecSentinel @brokensound77
