### ISSUE TITLE
Temporarily scheduled task creation - Missing user.name: *$  ?

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#2410]
Hi,
In my last update I've enabled the following 3 rules

1. A scheduled task was created
2. A scheduled task was updated
3. temporarily scheduled task creation

1 and 2 excludes task created by machine's user name, like this

```
iam where event.action == "scheduled-task-created" and
 /* excluding tasks created by the computer account */
 not user.name : "*$" and .....
 
```
 But 3 does not impose that condition. The result is a lot of alerts related to this rule where user.name is *$
 
 Any especial reason why the temporarily scheduled task creation does not exclude users.name. *$ ?
 Thanks

**Comment by w0rk3r** [comment]
Hey @janniten, thanks for bringing this to our attention! The following [PR](https://github.com/elastic/detection-rules/pull/2411) adds the exclusion.
