### ISSUE TITLE
[FR] Add "from" Field Validation for All Rules

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2416]
## Summary
At this time, the `from` field in all detection rules does not have any specific validation to ensure it is compatible with Kibana. A basic string type is given as the value, which validated via typing. However, as long as this value is a string, unit tests will pass as well as dataclass schema validation.

As a result, we should reference the date-math [documentation ](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math)and add some basic validation after splicing the string to ensure it is valid and maybe a warning based on the lookback value given if extremely large. 

Recreation Steps:
Find any rule with `from` field and change the value string `never-never`. Copy the path to the rule and run the following command to prove no dataclass schema errors during validation. Output should the rule in JSON format.

`python -m detection_rules view-rule RULEPATH`

Additionally, run unit tests to show no additional test failures.
Command: `pytest tests`
<img width="1097" alt="Screen Shot 2022-12-05 at 1 36 36 PM" src="https://user-images.githubusercontent.com/99630311/205716922-d257c797-4d14-46a2-817c-f97c0a19dbb8.png">

**Comment by brokensound77** [comment]
The only way we could add viable validation would be with date-math parsing and comprehension. I have seen some libraries but none were great. I also don't know if it would be worth rolling our own. Ideally, all rules are e2e tested before merge, which would help in this case.

Do you still plan to work this or should we close it out

**Comment by terrancedejesus** [comment]
@brokensound77 I do not plan to work on this in the immediate future unless it becomes a priority. This was created to just track the issue.

**Comment by shashank-elastic** [comment]
Good to have Unit test with the format, low priority backlog.
