### ISSUE TITLE
[Rule Tuning] Add Index Pattern 'logs-windows' to several Authentication / Active Direcotry Rules 

### ISSUE THREAD

**Issue by ChriZzn** [elastic/detection-rules#2417]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_dcsync_replication_rights.toml

## Description
There are Several Rules in the Repository which only search on the Index Patterns: "winlogbeat-*" and "logs-system.*" but if Logs are ingested via Forwarding and landing in the "logs-windows.*" none of the Rules will work...

Please Add "logs-windows.*" to the Index Pattern!

## Example Data
index = ["winlogbeat-*", "logs-system.*", "logs-windows.*"]

**Comment by w0rk3r** [comment]
Hey @ChriZzn, thanks for bringing this to our attention, we received a similar issue around this yesterday (https://github.com/elastic/detection-rules/issues/2415), and I'll conduct a review in our ruleset and add the index pattern where relevant.

**Comment by ChriZzn** [comment]
Hi, 
any updates when this is going to be fixed?

**Comment by w0rk3r** [comment]
Hey @ChriZzn, you can expect a PR in January, probably coming in the 8.6 release.

**Comment by w0rk3r** [comment]
Hey @ChriZzn, here is a PR to solve this one: https://github.com/elastic/detection-rules/pull/2438, feel free to review and/or give us your feedback.

**Comment by ChriZzn** [comment]
> Hey @ChriZzn, here is a PR to solve this one: #2438, feel free to review and/or give us your feedback.

Hi @w0rk3r, i ve done a review of the 38 modified Rules, here is a list rules which need the host.id adjusted (otherwise the rule would not work correctly), maybe you can change this to source.ip ?


- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_bruteforce_admin_account.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_bruteforce_multiple_logon_failure_followed_by_success.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_bruteforce_multiple_logon_failure_same_srcip.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_remote_sam_secretsdump.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_saved_creds_vault_winlog.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/credential_access_suspicious_winreg_access_via_sebackup_priv.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/lateral_movement_remote_service_installed_winlog.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/persistence_remote_password_reset.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/persistence_temp_scheduled_task.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/privilege_escalation_create_process_as_different_user.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/privilege_escalation_krbrelayup_service_creation.toml
- https://github.com/elastic/detection-rules/blob/3422ee37d506070bcf74fcf4c86c6c4785632c5e/rules/windows/privilege_escalation_suspicious_dnshostname_update.toml

Regards Christoph

**Comment by w0rk3r** [comment]
Hey @ChriZzn, we already solved that in this commit: https://github.com/elastic/detection-rules/pull/2438/commits/107239fa03c216292e0dd4122c4224d0630505eb, we are using `winlog.computer_name` instead of the `host.id` field

**Comment by ChriZzn** [comment]
okay, but how about this rule (https://github.com/elastic/detection-rules/blob/107239fa03c216292e0dd4122c4224d0630505eb/rules/windows/credential_access_bruteforce_admin_account.toml), lets say we don't have an hostname because Windows is unable to resolve the "attackers" Source Hostname (lets asume its a non domain joined linux host...), so the rule will not trigger, or am i wrong?

Regards Christoph

**Comment by w0rk3r** [comment]
The `winlog.computer_name` will log the name of the computer which generated the record/log. There are no DNS or other operations to resolve anything. 

![image](https://user-images.githubusercontent.com/26856693/208928714-991e461a-d0ca-46bf-b81c-6a674acacf71.png)
