### ISSUE TITLE
[Bug] Conversion from toml to ndjson breaks mail action message for detection rules

### ISSUE THREAD

**Issue by DionAkkerman** [elastic/detection-rules#2418]
**Describe the bug**
When converting a mail connection action with newlines from ndjson to toml, rule.TOMLRule.save_toml() removes newlines. This causes the conversion back to ndjson to fail (output contains wrong formatting or conversion fails due to toml parse errors). 

Mustache supports the use of backslashes and double-spaces as newline characters. Headers (## my header) get automatic newlines.  The returned TOMLRule object contains the original correct formatting, so it seems to be the writing through .save_toml() that causes issues. More specifically, I believe everything goes well in .save_toml() until the call to rule_formatter.toml_write() which removes the newline characters and double spaces. 

**To Reproduce**
1. Export a detection rule with a mail connector action with Moustache newlines (either double space + enter or backslash + enter) or headers (### My header + newline). Characters are preserved in the ndjson. 
2. Convert to TOML using create-rule() with the exported ndjson path as input and required_only set to False.
3. The formatting of message field in the toml output is destroyed or conversion fails.

**Expected behavior**
When converting from ndjson to TOML, formatting of the message field should be maintained.

**Comment by Mikaayenson** [comment]
Without causing significant overhaul to the rule_formatter logic, we can patch the `_do_write` method to handle this edge case where nested fields should not be formatted.

<details><summary>Mail Action Param Patch</summary>
<p>

```diff
diff --git a/detection_rules/rule_formatter.py b/detection_rules/rule_formatter.py
index 5d8516768..01d947924 100644
--- a/detection_rules/rule_formatter.py
+++ b/detection_rules/rule_formatter.py
@@ -186,6 +186,16 @@ def toml_write(rule_contents, outfile=None):
         for k in sorted(list(_contents)):
             v = _contents.pop(k)
 
+            # Special handling for the actions field
+            if k == 'actions':
+                updated_actions = []
+                for action in v:
+                    if 'params' in action and isinstance(action['params'], dict) and 'message' in action['params']:
+                        # Don't wrap format the 'message' field
+                        action['params']['message'] = NonformattedField(action['params']['message'])
+                    updated_actions.append(action)
+                v = updated_actions
+
             if isinstance(v, dict):
                 bottom[k] = OrderedDict(sorted(v.items()))
             elif isinstance(v, list):

```

</p>
</details>

**Comment by brokensound77** [comment]
Can you share an example @DionAkkerman in toml. We may already be able to support it by swapping triple quotes

**Comment by Mikaayenson** [comment]
Speaking with @brokensound77 I can try two things:
1. try adding triple quotes around message before importing
2. try adding `preserved_keys.add("message")` to `get_preserved_fmt_fields`

**Comment by Mikaayenson** [comment]
FWIW I tried both of those recommendations, and neither will address the issue. Anything beyond the patch I recommended will be a substantial refactor. Since this is an edge case, I recommend we go with the patch until we get to the larger [refactors](https://github.com/elastic/security-team/issues/8718) in Q2.
