### ISSUE TITLE
[Rule Tuning] ADFind Command Activity

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#2425]
## Link

https://www.elastic.co/guide/en/security/current/adfind-command-activity.html

## Description
Just have confirmation of a ransomware where adfind was used. This rule didn't trigger as the process name was ADFind2.exe. Maybe the rule could get a small adjustment from equals ADFind.exe to contains adfind?

**Comment by w0rk3r** [comment]
Hey @willemdh, can you give us a bit more details on the execution? Like original file name, command lines, etc? We can communicate over email or slack if you prefer. Thanks!

**Comment by willemdh** [comment]
No I can't give extra info. The query should be 'contains' adfind.
