### ISSUE TITLE
Problem with Multiple Alerts in Different ATT&CK Tactic Rule

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#2460]
Hi!
Today I've enabled the rule **Multiple Alerts in Different ATT&CK Tactic**. 
As far as I understand this is a kind of "Meta-Alert" that groups the ocuurance of several alerts classified with differenr tactics (>=3) on a same host.
![image](https://user-images.githubusercontent.com/33020901/211823642-cf07412d-be36-4d98-b520-f8edd3f49fa9.png)

After few hours an alert was triggered and when anallizing it I've realized that the host.id is not unique so, the alerts where risen in different hosts. I found several hosts in my enviroment sharing the same host.id.

https://elasticstack.slack.com/archives/C02J2JBS0FP/p1673430770481789

Also, looking back in this repo I've found that originally the rule was created by grouping by host.name (https://github.com/elastic/detection-rules/issues/1597)

Is this the normal behaviour of the rule? From which value is the host.id being populated

Thanks!

**Comment by janniten** [comment]
I think the problem comes when cloning machines...I've checked on 3 old Linux servers , has the same host.id 

![image](https://user-images.githubusercontent.com/33020901/211860898-8a8e43b3-a2bb-4215-9522-85683744487a.png)

In summary, all cloned VMs will share the same host.id
In linux, from the file` /etc/machine-id`
In windows from the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\MachineGuid`

**Comment by w0rk3r** [comment]
Hey @janniten, sorry for the delayed response. You can duplicate the rule in this case and group by both `host.name` and `host.id`, we decided not to modify the logic atm as this is an edge case.

![image](https://user-images.githubusercontent.com/26856693/219033461-dcead3fe-7b4a-4ded-a6af-1c9f959781dc.png)

Let me know if this works or if you have any other issue!
