### ISSUE TITLE
[Discuss] Entity Analytics Review

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#2480]
## Summary
Entity Analytics implementation planning discussion.

**Comment by Mikaayenson** [comment]
All of the planning is discussed in this gdoc[https://docs.google.com/document/d/1wt9wI7dO2rObi-fqCs1sTfyGWMcXkFk3pMRTvREjODY/edit?pli=1#heading=h.2b1v1tr0ep8m], with future work tracked in https://github.com/elastic/security-team/issues/4879. 

At the time, no DED support is needed. 

@Aegrah Please let us know if there is anything needed from DED.
