### ISSUE TITLE
[FR] Unit Test for Backporting Deprecated Rule Changes

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2532]
**Is your feature request related to a problem? Please describe.**
After rules are deprecated, they should not updated in future PRs. Instead any updates should require a new rule to be created with tuning adjustments to the deprecated.

Updates to existing deprecated rules have a chance to cause backporting issues and is generally not recommended.

**Describe the solution you'd like**
Implement a unit test that will determine if a rule has previously been deprecated and the existing delta includes changes to that deprecated rule. 

**Describe alternatives you've considered**
The alternative is to reference `stack-schema-map.yaml` and for each active branch, if we noticed the rule is not deprecated in one, fail.

**Comment by shashank-elastic** [comment]
Seems Similar to https://github.com/elastic/ia-trade-team/issues/90. We can ave one during implementation phase and close out other.
