### ISSUE TITLE
[Rule Tuning] Enumerating Domain Trusts via DSQUERY.EXE/nltest.exe

### ISSUE THREAD

**Issue by imays11** [elastic/detection-rules#2536]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/discovery_enumerating_domain_trusts_via_dsquery.toml 
https://github.com/elastic/detection-rules/blob/main/rules/windows/discovery_enumerating_domain_trusts_via_nltest.toml 

## Description

The Mitre Eval Score Analysis - 2022 [ [Refer](https://docs.google.com/document/d/1wVrhMIUS8wPqPhSgU8bf0bjLhaKFuNHv-d4AYkSQ3p0/edit?usp=sharing) ] identified the following:

[[rule.threat.technique]]
id = "T1018"
name = "Remote System Discovery"
reference = "https://attack.mitre.org/techniques/T1018/"

...to be added to the above rules for higher coverage score

## Example Data

N/A

**Comment by w0rk3r** [comment]
I think we can do the PR directly in these cases or create a draft PR to accommodate all mapping changes discovered in the review

**Comment by imays11** [comment]
> I think we can do the PR directly in these cases or create a draft PR to accommodate all mapping changes discovered in the review

I totally understand your suggestion however, this is an ongoing process with work being split between @shashank-elastic and I who work in different time zones. So, unfortunately we are not able to put all changes into 1 PR without slowing down progress. This is the process that has worked best for us. Additionally, we're maintaining consistency with our normalized procedure of Issue first, then PR, even though we made exceptions for this during the MITRE Sprint for the sake of urgency.

**Comment by w0rk3r** [comment]
No problem, just a suggestion, the issue first then PR is done to accommodate discussions around rule dev mostly (which don't seems to be the case), so I just see it as a extra step here, but if it works best for you, keep it up

**Comment by imays11** [comment]
I see what you mean. That may be something we should decide on as a team when it comes to which changes warrant an issue and which do not so we can eliminate unnecessary steps where possible.
