### ISSUE TITLE
[Rule Tuning] Potential Credential Access via Windows Utilities

### ISSUE THREAD

**Issue by hatl3n** [elastic/detection-rules#2539]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_cmdline_dump_tool.toml

## Description
As far as I can see, the rule requires Endpoint to trigger. A small change would make it work with normal Windows Security "process auditing" logs as well.
By: looking for "process.pe.original_file_name" OR "process.name" to match the lolbins.

I'm new to Elastic, so please do correct me if I am mistaking. But "process.pe.\*" tree of ECS seems to be populated by Endpoint Integration, while "process.name" is populated with normal Windows Security logs. *(When the OS has "process auditing" enabled, and ingestion is happening through Fleet+winlogbeat with "Windows Integration".)*
When hovering the integrations in Security->SIEM->Rules in Kibana, it says "one or more" of the integrations are needed, but as far as I can understand, the rule requires Endpoint to work as it is written now.
I cannot grasp if "Endpoint Integration" is directly connected with the Endpoint EDR-agent, or if simply turning on "Endpoint integration" would make winlogbeat populate the "process.pe.\*" fields at ingress. If it does, this can be closed as a non-issue.

## Example Data
Example image of an ingested event with a Windows Server, process auditing turned on, no Endpoint agent.

![image](https://user-images.githubusercontent.com/102922758/218100459-64aa1d1e-a6f6-471d-8297-8ee2cef0d639.png)

The rule did NOT trigger on the screenshoted event, but would if the rule was edited to detect on the "process.name" field as well as "process.pe.original_file_name".

**Comment by w0rk3r** [comment]
Hey @hatl3n, the rule as is today is compatible with endpoint (hence the Endpoint integration) and sysmon logs (which is collected used Windows integration or Winlogbeat), so rn the query isn't compatible with 4688, I see no issues on making it compatible though, I'll push a PR adding it
