### ISSUE TITLE
[Rule Tuning] Abnormal Process ID or Lock File Created

### ISSUE THREAD

**Issue by jamesspi** [elastic/detection-rules#2543]
## Link to rule

https://github.com/elastic/detection-rules/blob/main/rules/linux/execution_abnormal_process_id_file_created.toml

## Description
On Ubuntu 20.x and 22.x, `/var/run` is symlinked to `/run`, which is the path that Elastic Defend picks up as part of a file event.
The current EQL query will not detect any of the file events, such as the creation of a `pid` file, due to the above.

## Example Data
<img width="728" alt="image" src="https://user-images.githubusercontent.com/20421688/218271621-ba74de1a-7a17-4d52-837b-d7ad76dae611.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/20421688/218271642-4192d1d2-fca1-496e-a4ed-5382723a8565.png">

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/20421688/218271669-b1e348cf-c9bd-42c7-9d8b-99df8d962cce.png">

Quick test of adding an optional regex syntax to `/var` seems to work well.

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/20421688/218271931-089190ca-b6af-4e33-8d3f-925f77a348c1.png">

**Comment by brokensound77** [comment]
Thanks James, good find!

I think it is a bit more readable like this

```sql
file.path regex~ """(/var/run|/run)/\w+\.(pid|lock|reboot)"""
```

It should work, but if you can test to validate, that would help

**Comment by jamesspi** [comment]
Hey @brokensound77 , indeed, also works fine.

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/20421688/218460913-df00a91d-6bb1-48d5-938a-fcef6001e8c4.png">

**Comment by w0rk3r** [comment]
@Aegrah / @shashank-elastic maybe you guys could create a PR for this one?
