### ISSUE TITLE
[FR] Include Related Integrations and Setup information for prebuilt ML Rules

### ISSUE THREAD

**Issue by spong** [elastic/detection-rules#2548]
In line with https://github.com/elastic/security-docs/issues/2974, this issue is intended to help users better understand which integrations and what prior setup may be required to successfully use our Prebuilt ML Jobs/Rules.

Please touch base with the @elastic/security-ml folks for specifics on which rules require which integrations, and any additional setup instructions that may be required.

Once added, the `Related Integrations` and `Setup` fields will then be visible to the user within the security app as follows:

<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/2946766/218824140-56b723de-8a5c-4a67-a471-0d53416482ca.png" />   <img width="250" src="https://user-images.githubusercontent.com/2946766/218824155-9957b323-3a1c-4d4b-b8e3-76e38c642427.png" />
</p>

Note: not sure if `required fields` are relevant here as well too, or if integrations/setup will suffice. Please discuss further with the ML folks for their thoughts here.

**Comment by brokensound77** [comment]
completed!
