### ISSUE TITLE
[Meta] Update rules to account for Elastic Agent logs index

### ISSUE THREAD

**Issue by bm11100** [elastic/detection-rules#255]
## Description
If using the Elastic Agent, the events go into the `logs-*` index. All rule types that also have an Agent integration (example - AWS) will need to be updated/reviewed to ensure they work correctly with a standalone beat and the Elastic Agent index pattern.  For the AWS example, need to add `logs-aws*`  to each rule.

Roadmap - https://github.com/elastic/security-team/issues/224 and https://github.com/elastic/siem-team/issues/767

## For 7.10 
- [x] **AWS**
Agent integration: yes
PR (if applicable): https://github.com/elastic/detection-rules/pull/256
- [x] **Okta**
Agent integration: yes in 7.10
PR (if applicable):  #295 

## For 7.11
- [x] **GCP**
Agent integration: 
PR (if applicable): n/a
- [ ] **Linux** 
Agent integration: 
PR (if applicable): 
- [x] **O365**
Agent integration: 
PR (if applicable): https://github.com/elastic/detection-rules/pull/729
- [x] **GSuite** 
Agent integration: 
PR (if applicable): 
- [x] **Azure**
Agent integration: 
PR (if applicable): https://github.com/elastic/detection-rules/pull/729

## For 7.12
- [x] **Windows integration**
index: `logs-windows.*`
PR: #923 

## TBD
- [ ] **Cross-platform**
Agent integration: 
PR (if applicable): 
- [ ] **Network**
Agent integration: 
PR (if applicable): 
- [ ] **ML Jobs**
PR (if applicable): 

## Example 
`index = ["filebeat-*", "logs-aws*"]`

![image](https://user-images.githubusercontent.com/56412096/92138897-ff4c4d00-eddc-11ea-9b07-22f1920cd477.png)

**Comment by bm11100** [comment]
The ML jobs for CloudTrail appear like they may need to be updated if using the Elastic Agent. I didn't see `event.module` in my agent data set for CloudTrail, so that may need to be removed from the ML rules and/or replaced with `cloud.provider` or another applicable field. I'm not as familiar with the ML jobs but added it to this issue to double check.

**Comment by randomuserid** [comment]
We could use cloud.provider I guess but how do we differentiate between one data set and another, when they have been ingested by Filebeat, without the event.module field?

**Comment by bm11100** [comment]
`event.dataset` should be consistent across both as well. so perhaps `event.dataset:aws.cloudtrail` - similar to https://github.com/elastic/detection-rules/issues/339

**Comment by brokensound77** [comment]
do we foresee any more changes needed for this @bm11100?

**Comment by bm11100** [comment]
Some of the dataset names may change in the future, like `o365` will probably turn to `m365` and Teams will replace all the Skype references but I don't think we have to leave this one open.
