### ISSUE TITLE
[Rule Tuning] Hosts File Modified

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2552]
## Link to rule
https://github.com/elastic/detection-rules/blob/73d581500c7294ecec10913692c57833db694f8d/rules/cross-platform/impact_hosts_file_modified.toml#L4

## Description

Rule is generating a large number of FPs. Excluding "/Applications/Parallels Desktop.app/Contents/MacOS/prl_naptd", "/System/*", "/opt/cisco/anyconnect/vpnagentd", "/opt/cisco/secureclient/vpnagentd" process executable paths and process names of vim, cat, nano, pico from file events. Removing nano vim vi emacs from process events.

## Example Data

<img width="1680" alt="Screenshot 2023-02-15 at 12 08 28 PM" src="https://user-images.githubusercontent.com/48036388/219115800-e10510fc-6297-4618-aceb-4a59657cf1b1.png">

**Comment by maof97** [comment]
My opinion: I generally see that false positives are annoying when editing the host file via nano or vim, but I would argue that information that a host file was modified, even via a well known file editor, should still be alarmed. A threat actor could modify the file via the mentioned tools and nobody would ever know it. Nevertheless I am still on board for whitelisting the obvious FP (Parallels etc.).
