### ISSUE TITLE
[Rule Tuning] Bash Shell Profile Modification

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2553]
## Link to rule
https://github.com/elastic/detection-rules/blob/73d581500c7294ecec10913692c57833db694f8d/rules/cross-platform/persistence_shell_profile_modification.toml#L12

## Description

Rule is generating a large number of FPs related to FP process executables. Adding vim, mv, ditto, pico, git, nvim, TextEdit, Finder, jetbrains-toolbox and DesktopServicesHelper to process name exclusion list.

**Comment by maof97** [comment]
I have the same concerns here as I wrote on the "Host file Modified" rule tuning. An attacker could use these tools too, therefore it should still be alarmed.
