### ISSUE TITLE
[Rule Tuning] Modification of Standard Authentication Module or Configuration

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2556]
## Link to rule
https://github.com/elastic/detection-rules/blob/f04ebf277c08aa4a8f4cc5454fa8b60ede9126f7/rules/cross-platform/persistence_credential_access_modify_auth_module_or_config.toml#L10

## Description

Rule is generating FPs due to several FP process executables not relevant to malicious activity. Excluding vim, vi, nano, nvim, pico, codesign and com.docker.backend.

**Comment by maof97** [comment]
Sorry for copy&pasting but same applies here:

My opinion: I generally see that false positives are annoying when editing the host file via nano or vim, but I would argue that information that a host file was modified, even via a well known file editor, should still be alarmed. A threat actor could modify the file via the mentioned tools and nobody would ever know it. Nevertheless I am still on board for whitelisting the obvious FP (Parallels etc.).
