### ISSUE TITLE
[Rule Tuning] Process Created with an Elevated Token

### ISSUE THREAD

**Issue by maof97** [elastic/detection-rules#2578]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/privilege_escalation_via_token_theft.toml

## Description
This rule triggers a FP when TiWorker.exe spawns a ngen.exe which is updating itself:

![Bildschirm­foto 2023-02-19 um 21 21 37](https://user-images.githubusercontent.com/48106483/219973273-71522657-8735-4f5b-a119-d49dfe376880.jpg)

> The Native Image Generator (Ngen.exe) is a tool that improves the performance of managed applications. Ngen.exe creates native images, which are files containing compiled processor-specific machine code, and installs them into the native image cache on the local computer. The runtime can use native images from the cache instead of using the just-in-time (JIT) compiler to compile the original assembly.

Source: https://learn.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator

I would suggest just whitelisting Ngen.exe (if its signed) when the parent is TiWorker.exe.
On the other hand I don't know much about elevated tokens, so maybe attackers can use ngen.exe as well, then obviously whitelisting it like that is a bad idea.

## Example Data
```
process.name : "Ngen.exe" and 	
process.code_signature.subject_name: "Microsoft Corporation" and
process.parent.name: "TiWorker.exe"
```

**Comment by terrancedejesus** [comment]
Referencing the issue that will be used for tuning.

* https://github.com/elastic/detection-rules/issues/2620
