### ISSUE TITLE
[Rule Tuning] Suspicious service was installed in the system

### ISSUE THREAD

**Issue by maof97** [elastic/detection-rules#2580]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_service_windows_service_winlog.toml

## Description
This rule triggers a FP on every Windows Host/Server when Windows Defender is doing a definition update:

```
winlog.event_data.ImagePath: C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{1D936CFD-643E-4043-BB0B-38A4D9BC1488}\MpKslDrv.sys
	
winlog.event_data.ServiceName: MpKsl28770681
```

I think this should just be whitelisted.

Greetings
Martin

**Comment by w0rk3r** [comment]
Hey @maof97, I pushed a [PR](https://github.com/elastic/detection-rules/pull/2693) 2 weeks ago that should solve these noisy patterns, let me know if you have any other feedback! Thanks for your contribution!
