### ISSUE TITLE
[FR] Add schema validation for insights and osquery

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2584]
**Is your feature request related to a problem? Please describe.**
We need to validate the insights and osquery features  within our schema validation so that they fail if not formatted corrected.

<details>

<summary> Insights Example </summary>

```
# working 
!{insight{
    "label":"Investigate activities done by the subject process",
    "providers": [[{
            "field": "process.entity_id", "value": "process.entity_id", "type": "parameter"
        }]]}}


# working

!{insight{
    "label":"Testing",
    "providers": [
        [{
            "field": "host.name", "value": "host.name", "type": "parameter"
        },
        {
            "field": "event.kind", "value": "signal", "type": "literal"
        }],
        [{
            "field": "host.os.family", "value": "host.os.family", "type": "parameter"
        },
        {
            "field": "event.kind", "value": "signal", "type": "literal"
        }]
        ]}}

# failing
!{insight{
    "label":"Investigate activities done by the subject process",
    "providers": [{
            "field": "process.entity_id", "value": "process.entity_id", "type": "parameter"
        }]}}

```

</details>

<details>

<summary>OSQuery Example </summary>

```
!{osquery{"query":"SELECT description, display_name, name, path, pid, service_type, start_type, status, user_account FROM services","label":"Osquery - Retrieve All Services"}}
```

</details>

**Describe the solution you'd like**

In `rule.py` we already `validate_note`. We can leverage this logic to validate these two new note features. 

```python
# pseudocode
if child == osquery:
   validate_osquery(child)
elif child == insight:
   validate_insight(child)

```

In each new validate method, pass the string object to a dataclass schema and use the builtin validation.

See the [discussion](https://elastic.slack.com/archives/C02USDK55AQ/p1675688754935259) for more details.

**Comment by brokensound77** [comment]
An alternative approach that might simplifies this would be to introduce 2 new fields: `insights` and `osquery`, where we define a schema for them accordingly. Then we update the note logic to understand certain patterns, such as `!{insight}`, where `to_api_format()` would render the object into the template.

We would also need to update it to strip those original fields

**Comment by brokensound77** [comment]
Do you have more information on insights? Links or references?
