### ISSUE TITLE
[Bug] Rule Import CLI only importing required fields

### ISSUE THREAD

**Issue by spong** [elastic/detection-rules#2641]
There was a recent [discuss post](https://discuss.elastic.co/t/importing-rules-with-detection-rules-cli/327190) mentioning that the Rule Import CLI is only importing the required fields for rules, leaving off optional fields like `tags`/`from`/`to`/`interval`/etc. This issue is for debugging further.

**Comment by Mikaayenson** [comment]
The issue is that we've explicitly set import to only use required fields here: https://github.com/elastic/detection-rules/blob/main/detection_rules/main.py#L117 We should add an optional flag.

**Comment by Mikaayenson** [comment]
@terrancedejesus mentioned that new terms import will break due to our schemas implementation atm.
