### ISSUE TITLE
[Bug] Failed CI Unit Tests from Marshmallow Schema Validation

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2643]
## Overview
It appears something is causing unit test failures for all PRs at the moment during the build jobs. Failures occur exactly at the license check step, however, raised exceptions relate to Marshmallow.

<img width="1324" alt="Screenshot 2023-03-16 at 10 18 19 AM" src="https://user-images.githubusercontent.com/99630311/225645759-0a157ab2-0fd0-4d56-8099-d8111d8bf428.png">

Example Job: https://github.com/elastic/detection-rules/actions/runs/4437870918/jobs/7788219956?pr=2577

I've recreated this several times by either re-running failed jobs or opening other PRs and updating branches. Locally, no errors occur when running `python -m detection_rules dev license-check` or any related commands found in the `pythonpackage.yml` workflow.

Oddly enough, a few PRs were merged ~1 day before these errors started to occur across the repository. Initially the question is "what changed", but it does not appear that any code-related changes occurred with those PRs and in between the time those were merged and this issue started occurring.

**Comment by Mikaayenson** [comment]
@terrancedejesus If it helps. I think the error is a bit misleading. 

I think the error is coming from `err_msg = json.dumps(e.messages, indent=2)`. I suspect `e.messages` has changed somehow where when we pass it to `json.dumps` it throws an error of `Object of type TypeError is not JSON serializable`.

It could be a bit misleading.

**Comment by Mikaayenson** [comment]
@terrancedejesus some minor testing in [this](https://github.com/elastic/detection-rules/actions/runs/4441004736/jobs/7795522666) run to debug the params.

**Comment by terrancedejesus** [comment]
#### Update - 03/17/2023
So I tested a few things with this bug, capturing hear for documentation purposes.

1. I reviewed if the error generates from the `LockDataclassMixin.from_dict` method as the call traces raise the error at `err_msg = json.dumps(e.messages, indent=2)` in the following code below. However, after commenting out the code and simply printing error messages, the errors still occured.

```sql
        except ValidationError as e:
            err_msg = json.dumps(e.messages, indent=2)
            raise ValidationError(f'Validation error loading: {cls.__name__}\n{err_msg}') from None
```

2. Following the call traces again, it appears to be a potential error from schema Validation specifically when loading the Version Lock file as shown in the error below.

```sql
File "/home/runner/work/detection-rules/detection-rules/detection_rules/version_lock.py", line 342, in <module>
    default_version_lock = VersionLock(ETC_VERSION_LOCK_PATH, ETC_DEPRECATED_RULES_PATH, name='default')
  File "/home/runner/work/detection-rules/detection-rules/detection_rules/version_lock.py", line 1[37](https://github.com/elastic/detection-rules/actions/runs/4441494387/jobs/7814268739#step:6:38), in __init__
    self.version_lock = VersionLockFile.load_from_file(version_lock_file)
  File "/home/runner/work/detection-rules/detection-rules/detection_rules/mixins.py", line 161, in load_from_file
    loaded = cls.from_dict(dict(data=contents))
  File "/home/runner/work/detection-rules/detection-rules/detection_rules/mixins.py", line 142, in from_dict
    err_msg = json.dumps(e.messages, indent=2)
```

`VersionLockFile` is the marshmallow schema for the Version lock file and is defined in the `version_lock.py` library. The method `__getitem__` is used to check if rule IDs are found in the version lock file and return them, if not, raise an error. While this does not error out locally, I noticed `data` was a string checked as a key in the version lock file, which does not exist. Therefore I added an exception for this and re-ran jobs and they still failed.

**Comment by terrancedejesus** [comment]
Ah, looks like Marshmallow made some changes upstream that may have lead to the bug in our code which means we may need to make some adjustments.

Additionally the `argname` addition in there code relates to the errors we are seeing.
Reference: https://github.com/lovasoa/marshmallow_dataclass/pull/235/files

**Comment by terrancedejesus** [comment]
> Ah, looks like Marshmallow made some changes upstream that may have lead to the bug in our code which means we may need to make some adjustments.

Additionally the argname addition in there code relates to the errors we are seeing. Timing seems to line up as well.
Reference: https://github.com/lovasoa/marshmallow_dataclass/pull/235/files
Line reference: [L14](https://github.com/dairiki/marshmallow_dataclass/blob/792dc6606dc0744b4457f151d6f8516e8d81e59e/marshmallow_dataclass/union_field.py#L14)

Seems like this was the case, updated our dependencies to use `marshmallow-dataclass[union]~=8.5.12` and `typing-inspect==0.8.0` and the error seems to have resolved.
