### ISSUE TITLE
[Rule Tuning] Add Network Packet Capture Data Streams to Rules Utilizing Packetbeat Data

### ISSUE THREAD

**Issue by MakoWish** [elastic/detection-rules#2646]
## Link to rule
All rules currently leveraging Packetbeat data. 

## Description
All detection rules currently leveraging `packetbeat-*` indices do not also include data from the Network Packet Capture Integration for Elastic Agent. The `logs-network_traffic*` set of data stream indices need to be added.

**Comment by w0rk3r** [comment]
Hey @MakoWish, thanks for contributing! This is already on our backlog on https://github.com/elastic/detection-rules/issues/2200, as we want to ensure compatibility between packetbeat and the NPC integration. Some testing and evidence will also be involved, which makes the task a bit more expensive, but let us know if you want to team up or tackle a part of them.

**Comment by MakoWish** [comment]
Shoot! I have to run, but will get a better response in the AM.

**Comment by MakoWish** [comment]
@w0rk3r ,

Apologies for the delay. I did submit #2648 for some changes, but I am definitely okay with helping to get this done. We are trying to migrate onto Elastic Agent wherever possible. Let me know what I can do to help.

**Comment by w0rk3r** [comment]
Hey @MakoWish, if you have alert data around some of the rules you're suggesting for the index addition, that would be awesome 🔥 . (Just remember that this data *must be redacted*)

**Comment by MakoWish** [comment]
@w0rk3r ,

What sort of data would you like? You want some Packetbeat and Network Packet Capture JSON documents? Or do you want some JSON documents from alerts that have actually triggered from Packetbeat and/or Network Packet Capture events? Let me know, and I should be able to get those to you on Monday.

Eric

**Comment by MakoWish** [comment]
Looks like @terrancedejesus is on this, so I will just close this and my PR in favor of #2200 and #2665 .
