### ISSUE TITLE
[Bug] Potential Credential Access via Windows Utilities Rule Failure

### ISSUE THREAD

**Issue by MakoWish** [elastic/detection-rules#2658]
**Describe the bug**
Out of the box, the `Potential Credential Access via Windows Utilities` rule fails with the error "An error occurred during rule execution: message: "illegal_argument_exception: [illegal_argument_exception] Reason: expected ')' at position 49""

**To Reproduce**
1. Enable the rule
2. See execution failure

**Expected behavior**
Rule should execute successfully

**Screenshots**
![rule_failure](https://user-images.githubusercontent.com/26614684/227266522-f0b1683b-89df-43a4-9ac1-3833a76bf903.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2

**Additional context**
None

**Comment by w0rk3r** [comment]
Hey @MakoWish, thanks for bringing this to our attention! I've pushed a PR (https://github.com/elastic/detection-rules/pull/2659) to fix it. Let us know if you see any other rule fails!

**Comment by MakoWish** [comment]
Thank you for the quick fix!

**Comment by MakoWish** [comment]
I can confirm the fix worked after manually patching the query. 

![confirmed_fixed](https://user-images.githubusercontent.com/26614684/227357163-f5bded26-7d9c-4976-a6e6-a8b14aa9ba95.png)

Thank you again!
