### ISSUE TITLE
[FR] Update CI release processes and test new historical packages

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2690]
# Summary

**Is your feature request related to a problem? Please describe.**
Based on updates described in #2688 and #2689, we need to update the CI and test the new historical rules.

```[tasklist]
- [ ] Update the [release-fleet](https://github.com/elastic/detection-rules/blob/main/.github/workflows/release-fleet.yml) workflow to build and push historical packages based on new cli commands
- [ ] Test the new package via cypress testing (add gdoc link)
```

**Comment by terrancedejesus** [comment]
These tasks have been added and developed in https://github.com/elastic/detection-rules/pull/2715
