### ISSUE TITLE
[Bug] failed to upload detections rules 

### ISSUE THREAD

**Issue by si-najih99** [elastic/detection-rules#2705]
**Describe the bug**
i got this error trying to upload detection rules (toml rules) to stack version 8.7.0
![image](https://user-images.githubusercontent.com/130451851/231119699-161177ce-b71e-4e03-81ee-1fc3a79cc31e.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/130451851/231119842-d10a2b51-88ef-4143-9570-ebadab4ffbd2.png)

**Expected behavior**
rules been loaded

**Comment by Mikaayenson** [comment]
👋 Thanks @si-najih99 for reporting. We're in the process of updating our schemas. Once we do, you will just have to `git pull` and this error should disappear.  You should be able to try as soon as we close this issue.

**Comment by Mikaayenson** [comment]
> @Mikaayenson thank you for your response i wanna know if there is an old version of the code that can use right now ?

This update should be coming in momentarily. Just remember that you will have to use the `--replace-id` flag if you're using trying to upload a rule with an existing rule_id.
