### ISSUE TITLE
[Rule Tuning] Powershell Keylogging Script

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#2713]
## Link to rule

[Powershell   Keylogging Script](https://www.elastic.co/guide/en/security/current/powershell-keylogging-script.html)

## Description

SentinelOne will by design include `Set-PSBreakpoint `when certain commands like `Get-Keystrokes` are executed.

![image](https://user-images.githubusercontent.com/6462991/231713572-45ae2e85-0ea6-4b97-9996-56060b93617c.png)

This generates a huge amount of false positives, for which there is no easy way to make an exception, as the `powershell.file.script_block_text` field is not an ECS field.

Adding `not powershell.file.script_block_text : "<#sentinelbreakpoints#>"` to the query resolves the issue. 

## New Rule Query Suggestion

event.category:process and ( powershell.file.script_block_text : (GetAsyncKeyState or NtUserGetAsyncKeyState or GetKeyboardState or "Get-Keystrokes") or powershell.file.script_block_text : (	( SetWindowsHookA or SetWindowsHookW or SetWindowsHookEx or SetWindowsHookExA or NtUserSetWindowsHookEx ) and ( GetForegroundWindow or GetWindowTextA or GetWindowTextW or "WM_KEYBOARD_LL" ) ) ) and not user.id : "S-1-5-18" and not powershell.file.script_block_text : "<#sentinelbreakpoints#>"

**Comment by w0rk3r** [comment]
@willemdh, can you provide a *redacted* event around this one?

**Comment by w0rk3r** [comment]
Hey @willemdh, to provide an update, I was investigating this one, and there is a PR coming to solve these FPs around this and other rules

**Comment by w0rk3r** [comment]
The PR: https://github.com/elastic/detection-rules/pull/2907

**Comment by willemdh** [comment]
Thank you very much for this @w0rk3r

**Comment by w0rk3r** [comment]
Sorry for how long we took to investigate this, but we didn't have enough data then. If you have other FPs to report, feel free to open issues, PRs, or ping me at the Community Slack (@Jonhnathan). Thanks for the contribution!
