### ISSUE TITLE
[Rule Tuning] PowerShell Script with Token Impersonation Capabilities

### ISSUE THREAD

**Issue by hatl3n** [elastic/detection-rules#2719]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/privilege_escalation_posh_token_impersonation.toml

## Description
High false positive rate when using **Defender ATP**. 
As and addition to PR #2449 where SYSTEM user.id as added as a NOT-filter to reduce false positives, I think there should be an addition to not flag Defender ATP.

We have an exception and I suggest an additional NOT-condition:
```
AND file.directory IS C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Downloads
AND user.id IS ONE OF S-1-5-20, S-1-5-19
```

The user IDs are Local Service and Network Service.
NB: It also uses S-1-5-18 SYSTEM, but that is already excluded by the rule.

I could probably make a PR for this, but I'm not that skilled in GitHub or Elastic rule-editing best practices. If I see how this is PR'ed I will probably try a PR the next time.

## Example Data
- file.path: "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Downloads\PSScript_{74BD626C-7232-4119-8D46-C683A6E77C71}.ps1" (The ID in {} changes)
- user.id: "S-1-5-20"
- winlog.user.name: "NETWORK SERVICE"

Full (redacted and removed "message") JSON dump of example event:
https://gist.github.com/hatl3n/70682e4ec8f7b8aea132479caecebb59

**Comment by hatl3n** [comment]
Woopsie! The same goes for another rule which triggers at the same time:
PowerShell Suspicious Payload Encoded and Compressed
https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_posh_compressed.toml

We se SID S-1-5-19 on this one, while 18 is already filtered out in the rule.

**Comment by w0rk3r** [comment]
Hey @hatl3n, thank you for bringing this to our attention; I'll be doing a review around those and will push a tuning PR soon! Let me know if you have any other posh rules with a High false positive rate ;)

**Comment by hatl3n** [comment]
Thanks @w0rk3r ! I'll check back and learn when it's done and try to maybe do a PR next time instead. Or do you prefer issues from the community?

We're adding bulks of community rules at a time and spend some time tuning exceptions to our environment. When I spot general much-used things that generate FPs, I'll keep contributing! :) I LOVE the community rules.

**Comment by w0rk3r** [comment]
Hey @hatl3n, deal! We would love to receive PRs, and if you need any help, you can jump on our [community Slack](https://join.slack.com/t/elasticstack/shared_invite/zt-1tchkw7ee-uW~tmSIu1IK2XP6OvfGl9A) and search for me (Jonhnathan) there in DMs, and I can speed you up on the process ;)
