### ISSUE TITLE
[Rule Tuning] Update rules with ATT&CK tactic and technique metadata

### ISSUE THREAD

**Issue by threat-punter** [elastic/detection-rules#272]
## Description

Currently, we cannot include an ATT&CK tactic in a rule without a technique. Some of our rules have no ATT&CK tactic/technique metadata in them. E.g. Some Okta rules that were part of the 7.9 release.

Once https://github.com/elastic/kibana/issues/69166 is resolved, we should update our existing rules to include the relevant ATT&CK tactic metadata (and the technique metadata if there is an appropriate technique to map the rule to at that time).

We've submitted some information on new techniques to ATT&CK to help close some gaps, but they're still reviewing that information.

**Comment by rw-access** [comment]
Potentially a duplicate of #51 and/or #52

**Comment by threat-punter** [comment]
You're right. I missed that. Thanks
