### ISSUE TITLE
[New Rule] ML logs anomaly

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#273]
## Description
The observability-logs provides a Machine Learning job to detect anomalies in the amount of logs for a given event.dataset.

Anomalies in the data coming in could indicate someone tampering with the logs or generating noise to distract from other activites

## Required Info
- **Eventing Sources:**
Default Machine Learning job `kibana-logs-ui-default-default-log-entry-rate`

- **Target Operating Systems:**
n.v.t

- **Platforms**
n.v.t

- **Target ECS Version:** 
1.6

**Comment by SHolzhauer** [comment]
Challenge with this is the use of the "space" name in the ML job. If anyone sees a work around to this...

**Comment by threat-punter** [comment]
Hi @randomuserid. I'm cleaning up some open issues in this repo. I've assigned this issue to you for now, as I see PR #274 is pending your review. Thanks
