### ISSUE TITLE
[Bug] Broken osquery links in docs

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2801]
**Describe the bug**

During the release, we run into issues where osquery links break the security-docs ascii doc. It occurs everytime based on how they are referenced, and we have to change from the static markdown to the site references if possible.

<img width="1366" alt="Screenshot 2023-05-18 at 4 15 35 PM" src="https://github.com/elastic/detection-rules/assets/1636709/8510a9d3-7cd9-4fc7-9aaf-ddbfe334490f">

Sample docs [release](https://github.com/elastic/security-docs/pull/3307/commits/c3ddc463a00c83bc8d3b5332f8a55f0dfa32a158)

The challenging part will be to somehow  identify which {assets} are available in the docs site and if available, replace them. When we move to the new docs version in the future this shouldn't be a problem. For now, it causes delays in the release.

**Comment by brokensound77** [comment]
is this still a bug?

**Comment by terrancedejesus** [comment]
Yes. Here is some code that is used to fix these.

```
import re
import os

def replace_md_links(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    # Regular expression to find markdown links
    md_link_regex = re.compile(r'\[(.*?)\]\((https://www\.elastic\.co/guide/en/(.*?))\)')

    # Replace markdown links with asciidoc format
    new_content = md_link_regex.sub(r'{security-guide}/\3[\1]', content)

    # Write the modified content back to the file
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(new_content)

def main():
    # Directory where .asciidoc files are stored
    root_dir = '/Users/tdejesus/code/src/security-docs/docs/detections'

    # Walk through the directory
    for foldername, subfolders, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith('.asciidoc'):
                replace_md_links(os.path.join(foldername, filename))

if __name__ == "__main__":
    main()

```

**Comment by shashank-elastic** [comment]
This is fixed as part of https://github.com/elastic/detection-rules/pull/3474
 We now don't use Markdown plugins for doc generation but use asciidocs for internal references. 
 Verified from latest doc release PR - https://github.com/elastic/security-docs/pull/5036/files
