### ISSUE TITLE
[Rule Tuning] Suspicious Antimalware Scan Interface DLL

### ISSUE THREAD

**Issue by ZacintheBox88** [elastic/detection-rules#2803]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_amsi_bypass_dllhijack.toml

## Description
Miss-spell on line 112. "Distribuition" should be "Distribution" for the exception to work.

**Comment by w0rk3r** [comment]
Thanks for bringing this one to our attention, we are going to fix it as part of https://github.com/elastic/detection-rules/pull/2850
