### ISSUE TITLE
[FR] Bulk Update Rules

### ISSUE THREAD

**Issue by cgi-gerlando-caldara** [elastic/detection-rules#2804]
**Is your feature request related to a problem? Please describe.**
We need a way to upload and update multple detection rules

**Describe the solution you'd like**
Kibana comand line gets a new command to update existing rules on Kibana

**Describe alternatives you've considered**
Alternatives would be to create own API Implementation and rebuild the Kibana API Code

**Additional context**
To have the possible automatic possibility to create and upload changes over the exiting command line tool.

**Comment by brokensound77** [comment]
Similar to [this](https://github.com/elastic/detection-rules/blob/main/CLI.md#uploading-rules-to-kibana)?
