### ISSUE TITLE
Excluding Linux Rules from Container Scope

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2809]
## Problem

Currently, in order to ensure our detection rules fire on the intended platform and not on others (e.g Linux rules firing on Windows events and vice versa) we have added the ```host.os.type``` field to our rules. Where this has become an issue, specifically in regard to container events and detection rules, is due to the fact that both container events and generic Linux endpoint events contain the ```host.os.type``` field allowing any Linux rule to run on as well as alert on container data. We don't want this for several reasons the most important two being:

* While some of the Linux rules will be good rules for container environments many are too noisy as is or will behave differently on data from a container environment. This will could cause confusion and a flooding of alerts.
* We have not performed testing of our Linux endpoint ruleset on container telemetry data yet. Much of the container dataset is still being worked on and proper testing of our Linux endpoint rules against container specific data is needed prior to adding those rules to container based detection workflows.

## Solutions

Temporary:

Exclusion of Linux endpoint based Detection Rules from Container Data Scope

* Add the ```event.dataset : endpoint.events.file``` field to all current Linux detection rules which will exclude them from running on container event data due to that dataset being different from the one containers use. Ensure all event.datasets are properly included based on the rule index. E.g. endgame-* should have `event.dataset: (... endgame.file, ...)`

* Ensure all container rules contain the ```container.id : "*"``` field and value which doesn't exist in Linux endpoint events. Eventually this will shift to ```event.dataset : container something``` ,when the AWP team standardizes the dataset, in order to remain consistent across detection rules.

Long-Term:

Move rule enablement and compatibility from detection rule tags and rule based specification to deployment and policy based designations.

```[tasklist]
# Action Items
- [ ] Create Detection Rule PR adding proper event.dataset to all Linux rules @brokensound77
- [x] Speak with Dan and Norrie about prioritizing the addition of critical fields like event.dataset along with formalization of the dataset @imays11 @DefSecSentinel
```

**Comment by imays11** [comment]
Verified today with a new stack that we have the fields we're looking for and they are consistent across file and process events. 
![image](https://github.com/elastic/detection-rules/assets/59296946/d328ab28-6e57-4826-8041-0387f49ab568)
