### ISSUE TITLE
[Bug] Unusual Windows User Privilege Elevation Activity

### ISSUE THREAD

**Issue by MakoWish** [elastic/detection-rules#2819]
**Describe the bug**

This rule has been the noisiest alert we have enabled, and because of it, I have assigned only myself as a recipient. I was hoping the model would eventually learn "normal" behavior and quiet down, but it has not. I spent some time looking into a few alerts to see why they were triggering, and it seems to be the difference between the SubjectDomainName being reported as the NetBIOS version of the domain, and the TargetDomainName being reported as the full domain name. I.e.:

`winlog.event_data.SubjectUserName: jdoe`
`winlog.event_data.SubjectDomainName: CTSO`
`winlog.event_data.TargetUserName: jdoe`
`winlog.event_data.TargetDomainName: contoso.com`

The subject and target are 100% the same user, but based on how Windows is logging the event, this ML rule is interpreting the events as "run as" activities. 

I honestly don't know how this can be fixed, but hoping to hear some thoughts on how we could get this rule to not trigger on events like this. 

**To Reproduce**
Here is a sample sanitized event that triggered the rule:

```
{
  "agent": {
    "name": "Server1",
    "id": "bb4a7bd9-9e72-44ce-9dd6-123456789abc",
    "ephemeral_id": "255bf3cc-43ea-4f56-b582-987654321cba",
    "type": "winlogbeat",
    "version": "8.3.3"
  },
  "process": {
    "name": "lsass.exe",
    "pid": 992,
    "executable": "C:\\Windows\\System32\\lsass.exe"
  },
  "winlog": {
    "computer_name": "Server1.contoso.com",
    "process": {
      "pid": 992,
      "thread": {
        "id": 21664
      }
    },
    "keywords": [
      "Audit Success"
    ],
    "logon": {
      "id": "0x13cd67b1"
    },
    "channel": "Security",
    "event_data": {
      "LogonGuid": "{abcdef12-b7c0-5467-6542-20d327e76ae9}",
      "IpPort": "-",
      "SubjectLogonId": "0x13cd67b1",
      "TargetLogonGuid": "{abcdef12-f3e9-165b-581e-88319e1dbed3}",
      "TargetInfo": "TERMSRV/Computer1",
      "SubjectUserName": "jdoe",
      "TargetServerName": "Computer1",
      "IpAddress": "-",
      "SubjectDomainName": "CTSO",
      "TargetUserName": "jdoe",
      "TargetDomainName": "contoso.com",
      "SubjectUserSid": "S-1-5-21-123456789-252729241-123456789-25430"
    },
    "opcode": "Info",
    "record_id": "6748237",
    "task": "Logon",
    "event_id": "4648",
    "provider_guid": "{12345678-5478-4994-a5ba-123789456fed}",
    "activity_id": "{01f78c75-2270-0002-cbf5-321987654df}",
    "api": "wineventlog",
    "provider_name": "Microsoft-Windows-Security-Auditing"
  },
  "log": {
    "level": "information"
  },
  "short_message": "A logon was attempted using explicit credentials.",
  "message": "A logon was attempted using explicit credentials.\n\nSubject:\n\tSecurity ID:\t\tS-1-5-21-123456789-252729241-123456789-25430\n\tAccount Name:\t\tjdoe\n\tAccount Domain:\t\tCTSO\n\tLogon ID:\t\t0x13CD67B1\n\tLogon GUID:\t\t{abcdef12-b7c0-5467-6542-20d327e76ae9}\n\nAccount Whose Credentials Were Used:\n\tAccount Name:\t\tjdoe\n\tAccount Domain:\t\tcontoso.com\n\tLogon GUID:\t\t{abcdef12-f3e9-165b-581e-88319e1dbed3}\n\nTarget Server:\n\tTarget Server Name:\tComputer1\n\tAdditional Information:\tTERMSRV/Computer1\n\nProcess Information:\n\tProcess ID:\t\t0x3e0\n\tProcess Name:\t\tC:\\Windows\\System32\\lsass.exe\n\nNetwork Information:\n\tNetwork Address:\t-\n\tPort:\t\t\t-\n\nThis event is generated when a process attempts to log on an account by explicitly specifying that account’s credentials.  This most commonly occurs in batch-type configurations such as scheduled tasks, or when using the RUNAS command.",
  "monitoring": {
    "group": "Enterprise MS Team"
  },
  "tags": [],
  "@timestamp": "2023-05-26T20:02:56.560Z",
  "ecs": {
    "version": "1.12.0"
  },
  "related": {
    "hosts": [
      "Server1"
    ],
    "ip": [
      "10.0.0.21"
    ],
    "user": [
      "jdoe"
    ]
  },
  "@version": "1",
  "host": {
    "hostname": "Server1",
    "os": {
      "build": "19044.2965",
      "kernel": "10.0.19041.2965 (WinBuild.160101.0800)",
      "name": "Windows 10 Enterprise for Virtual Desktops",
      "type": "windows",
      "family": "windows",
      "version": "10.0",
      "platform": "windows"
    },
    "ip": [
      "10.0.0.21"
    ],
    "name": "Server1",
    "id": "eb4e83c3-ac05-4645-be0c-123456789abc",
    "mac": [
      "60-45-BD-C7-E5-4B"
    ],
    "architecture": "x86_64"
  },
  "event": {
    "ingested": "2023-05-26T20:02:59Z",
    "code": "4648",
    "provider": "Microsoft-Windows-Security-Auditing",
    "timezone": "+00:00",
    "created": "2023-05-26T20:02:57.665Z",
    "kind": "event",
    "module": "security",
    "action": "logged-in-explicit",
    "category": [
      "authentication"
    ],
    "type": [
      "start"
    ],
    "outcome": "success"
  },
  "user": {
    "effective": {
      "domain": "contoso.com",
      "name": "jdoe"
    },
    "domain": "CTSO",
    "name": "jdoe",
    "id": "S-1-5-21-123456789-252729241-123456789-25430"
  }
}
```

**Comment by ajosh0504** [comment]
@MakoWish Hmmm definitely not a trivial thing to solve easily. It almost sounds like we'd need some type of entity resolution to reconcile the subject and target domain names. However, some things to think about:
- How often do these types of events occur for this user? If they are rare, just by the nature of the job configuration, it will get flagged as an anomaly. If it's frequent, then yeah the model should learn that and eventually stop flagging it
- You may experiment with changing the bucket span for the anomaly detection job from 15 minutes to something bigger- this means the job will look at a larger time window to decide whether or not something is rare
- Are there other fields in the events themselves that you can think of, that can be included in the datafeed query to filter out such events from being counted as run as events?
- You can also change the [alert threshold](https://github.com/elastic/detection-rules/blob/main/rules/ml/privilege_escalation_ml_windows_rare_user_runas_event.toml#L9) if you'd only like to be alerted for the most anomalous of the anomalous events. 

Finally, our pre-built anomaly detection jobs are pretty generic behavioral indicators of suspicious activity. The best way to get the most out of them is to combine them with each other and/or with other detection alerts to generate higher fidelity alerts to detect on more specific scenarios.

**Comment by ajosh0504** [comment]
> How exactly would one go about doing that? We just have the OOB jobs and their related detection rules enabled. Not sure how we could combine them.

You could combine multiple detection rules (ML and otherwise) by writing [event correlation](https://www.elastic.co/guide/en/security/current/rules-ui-create.html#create-eql-rule) logic as another layer on top of exiting detection rules/alerts.

**Comment by w0rk3r** [comment]
I am closing this one as it has not received any updates since July. Please feel free to reopen if you need to.

**Comment by MakoWish** [comment]
I do not have permissions to reopen this, but I believe I found a working solution to this issue for anybody else that may run into this.

The key issue I have been running into is where the events are recorded with the subject showing the NetBIOS domain name, while the target is showing the FQDN. Some sample data that would trigger this may look like:

```
...
  "winlog.event_data.SubjectUserName": "jdoe",
  "winlog.event_data.SubjectDomainName": "CTSO",
  "winlog.event_data.TargetUserName": "jdoe",
  "winlog.event_data.TargetDomainName": "contoso.com",
...
```

You can see it was John Doe that ran something as John Doe, but based on the way the Windows Event Log is recorded, it mixed NetBIOS and FQDN, so this appears as though it is a different user when it is not. I adjusted the ML rule's data feed on my cluster to skip matches where the subject user is the same as the target user. The new query on that data feed uses a Painless script to ignore documents where the username is the same. The full query is now this:

```
{
  "bool": {
    "filter": [
      {
        "term": {
          "event.code": "4648"
        }
      },
      {
        "script": {
          "script": "doc['winlog.event_data.SubjectUserName'] != doc['winlog.event_data.TargetUserName']"
        }      
      }
    ],
    "must": [
      {
        "bool": {
          "should": [
            {
              "match": {
                "host.os.family": {
                  "query": "windows",
                  "operator": "OR"
                }
              }
            },
            {
              "match": {
                "host.os.type": {
                  "query": "windows",
                  "operator": "OR"
                }
              }
            }
          ]
        }
      }
    ]
  }
}
```

Just wanted to throw that out there in case others run into the same.
