### ISSUE TITLE
[Rule Tuning] Suspicious PowerShell Engine ImageLoad 

### ISSUE THREAD

**Issue by 0x0Faisal** [elastic/detection-rules#2840]
## Link to rule

[execution_suspicious_powershell_imgload.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/execution_suspicious_powershell_imgload.toml)

## Description

It appears that the rule is not excluding as expected due to a typo in the regex: `not process.executable regex~ """C:\\Program Files( \(x86\))?\\*\.exe"""` . According to this line it should exclude the executable that are in the directories `C:\Program Files` and `C:\Program Files (x86)`. However, using the previous regex it won't exclude anything.

## Example Data

What should be fixed is instead of `not process.executable regex~ """C:\\Program Files( \(x86\))?\\*\.exe"""` a dot "." is added to indicate that it will match anything after `( \(x86\))?\\.*`. Therefore the right query will be: `not process.executable regex~ """C:\\Program Files( \(x86\))?\\.*\.exe"""`

**Comment by w0rk3r** [comment]
Closing this issue as a KQL exclusion replaced the regex as part of https://github.com/elastic/detection-rules/pull/3107, which converted this rule to new_terms, which is working as expected.
