### ISSUE TITLE
[FR] Update Security Docs Release Process to Add Index Rules Page Per Stack

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2867]
#### Overview
Update security docs release process for detection rules to add all rules for each stack version, separate from downloadable updates.

As requested per @xcrzx.

#### Additional Information
More details to come.
```[tasklist]
### Generate Prebuilt Rules Reference Page
- [x] Review security-docs page 8.6+
- [x] Adjust `devtools.py` docs generation to generate rules index page
- [x] Update "How to Update Rules" References
- [x] Create a single PR to docs for testing and view preview link for testing
```

```[tasklist]
### Manual Update PRs to Old Security-Docs Branches
- [ ] https://github.com/elastic/security-docs/pull/3640
- [ ] https://github.com/elastic/security-docs/pull/3646
- [ ] https://github.com/elastic/security-docs/pull/3650
```

**Comment by approksiu** [comment]
Is it realistic to finish this work by July 5th (to accommodate BC schedule)? cc @Mikaayenson

**Comment by terrancedejesus** [comment]
> Is it realistic to finish this work by July 5th (to accommodate BC schedule)? cc @Mikaayenson

It may not be anymore because we are doing an unexpected Detection Rules release today.

**Comment by approksiu** [comment]
Thanks @terrancedejesus. What is a realistic timeframe for this?

**Comment by terrancedejesus** [comment]
> Thanks @terrancedejesus. What is a realistic timeframe for this?

By EOD July 7th, 2023 is doable.

**Comment by terrancedejesus** [comment]
@approksiu - This got de-prioritized by DED the last week. We are looking to pick this back up soon.

**Comment by approksiu** [comment]
@Mikaayenson please keep me posted about this, it still needs to be addressed. Thanks!

**Comment by Mikaayenson** [comment]
### Update July 25th

The plan is to add a new method within our `IntegrationSecurityDocs` class to rebuild the [prebuilt-rules-reference](https://github.com/elastic/security-docs/blob/main/docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc) page. Once the PR is built, we can test using the `release-docs` workflow. 

We will start this work today and hope to have this merged by the end of week.
