### ISSUE TITLE
EQL data replay unit tests

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#287]
EQL evaluation of data against expected RTA mappings needs to be added to `test_mappings`. There are some slight differences in the python engine and Elasticsearch EQL which will need to be accounted for - in particular multi-valued fields. 

There may also be some other subtle issues which @rw-access is aware of with regard to evaluation.

There is currently support for KQL evaluation for mapping testing.

**Comment by rw-access** [comment]
@brokensound77 you okay closing out this issue and a few related ones? I don't think we have this on the roadmap for a while. And if we do, we might as well do integration-style tests. Thoughts?

**Comment by brokensound77** [comment]
Yep, sounds good to me. We would need to reassess this testing as a whole to see what makes the most sense now. Once we get there, we can revisit these issues and open a new one
