### ISSUE TITLE
[Bug] Improper usage of `requires_os` in RTAs

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#2871]
The function `requires_os` accepts an arg list of strings, but many rtas pass a list directly. Proper syntax should be `requires_os(*metadata.platforms)`

All RTAs should be reviewed and corrected

_Originally posted by @brokensound77 in https://github.com/elastic/detection-rules/pull/2788#discussion_r1238882205_

**Comment by eric-forte-elastic** [comment]
Waited/waiting to merge this until Monday, as to not merge code in on Friday.
