### ISSUE TITLE
[Bug] Mismatch Required Field Types From Schemas Between Stack Versions

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#2894]
## Overview
During the `8.8.6` release, I noticed that the rule versions were descending for a couple rules. For this explanation we will focus on Potential Credential Access via DuplicateHandle in LSASS (02a4576a-7480-4284-9327-548a806b5e48). 

Before every release, we lock rule versions as we [did](https://github.com/elastic/detection-rules/pull/2892/files) for `8.8.6`. This rule was bumped from 104 -> 105 as shown in the version lock PR. This is accurate.

When we release the `v8.7.7` package in a previous release, the version of this rule was 104 and received changes since, thus making it version 105.

#### The issue
When using the `view-rule` CLI command on the `8.7` branch, we see that required fields differ from the required fields values on the `8.8` and `8.9` branch.

`8.8` branch using `view-rule` CLI.

<details>

```sql
  "required_fields": [
    {
      "ecs": true,
      "name": "event.code",
      "type": "keyword"
    },
    {
      "ecs": true,
      "name": "host.os.type",
      "type": "keyword"
    },
    {
      "ecs": true,
      "name": "process.name",
      "type": "keyword"
    },
    {
      "ecs": false,
      "name": "winlog.event_data.CallTrace",
      "type": "keyword"
    },
    {
      "ecs": false,
      "name": "winlog.event_data.GrantedAccess",
      "type": "keyword"
    }
```

</details>

`8.7` branch using `view-rule` CLI.

<details>

```
  "required_fields": [
    {
      "ecs": true,
      "name": "event.code",
      "type": "keyword"
    },
    {
      "ecs": true,
      "name": "host.os.type",
      "type": "keyword"
    },
    {
      "ecs": true,
      "name": "process.name",
      "type": "keyword"
    },
    {
      "ecs": false,
      "name": "winlog.event_data.CallTrace",
      "type": "unknown"
    },
    {
      "ecs": false,
      "name": "winlog.event_data.GrantedAccess",
      "type": "unknown"
    }
```

</details>

As a result, the 8.7 version of the rule will always be different. The required fields are build-time generated and the type of that field is typically pulled from the schema it belongs to. This means that up until `8.8`, the rule's required field types had been unknown, but in `8.8`+ are now defined.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/detection-rules/pull/2895
- [ ] https://github.com/elastic/detection-rules/pull/2896
```

**Comment by terrancedejesus** [comment]
#### Update 06/29/2023

Some notes during root cause analysis:
* It appears the build-time field `required_fields` has different values between `<=8.7` and `>=8.8` as noted in the original comment
* The following rules had version differences. They all are Winlogbeat/Windows integration rules.
    * Suspicious LSASS Access via MalSecLogon
    * Potential Credential Access via DuplicateHandle in LSASS
    * Suspicious Lsass Process Access
    * Potential Credential Access via LSASS Memory Dump
    * Potential LSASS Memory Dump via PssCaptureSnapShot
    * Suspicious Process Access via Direct System Call
    * Suspicious Process Creation CallTrace

**Comment by brokensound77** [comment]
Is this an actual bug or the result of changes values and upstream data mappings. If it is valid, do we still intend to address it?

**Comment by jvalente-salemstate** [comment]
> Is this an actual bug or the result of changes values and upstream data mappings. If it is valid, do we still intend to address it?

Whether a bug or not, I think resolving this would be helpful.  With over 1000 rules, there are a lot of rules to filter through. On many occasions I've ended up importing /enabling rules for sources we will likely never need (AWS).  I've got to manually filter, one at at time, for sources I am certain we're using, or just import all and only enable what I know is in use. 

Having this function (or a filter for installed / enabled integrations) work properly could help with that, as well as a better experience in the ATT&CK coverage view. It will show enabled/disabled rules with no integration installed in there.

**Comment by terrancedejesus** [comment]
At the moment, we address this issue by updating or adding a min-stack for rules where versions diverge because of changes in rules that are upstream and pulled into the repository. @shashank-elastic has witnessed this first-hand with many of the releases lately. Typically this is the request of build time dynamic fields, `related_integrations` or `required_fields`. Every now and then it may be an ECS schema update, such as changing the field type that causes us to have to min-stack to create divergent paths for versioning. This is not a bug, but rather the result of dependencies upstream that cause us to fork rule versions. Closing this issue.
