### ISSUE TITLE
[FR] Add 'Asset' tag category

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#2900]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Add the `Asset` category to [the tags](https://github.com/elastic/detection-rules/blob/35ea2727dcd016c0cf06f19c1cfb51990e51a9a9/detection_rules/schemas/definitions.py#L58):
```
EXPECTED_RULE_TAGS = [
    'Asset: ',
    'Data Source: Active Directory',
    'Data Source: Amazon Web Services',
```

**Describe alternatives you've considered**
Add assets in the title of a detection; Which works when there is a 1-to-1 relation, for 1-to-many (many assets
on a single detection) it wont.

**Additional context**
With #2725 tag categories have been introduced. Cleaning up the "random" mess of tags.
With our custom rules we have been tagging the assets they cover (e.g application names, platforms)
to have quick method of retrieving the rules which are specifically designed to cover an asset.

In my expertise most managers are interested in information on coverage, which this can do.

**Comment by SHolzhauer** [comment]
We make use of the `Asset: ` tag to denote which of our items in the CMDB are covered by a rule.

For example, we have a rule:
```
tags = ["Data Source: Amazon Web Services", "Asset: <application>", "Asset: <application 2>"]
```
This would be a rule based on cloudtrail (e.g) which coveres some of our assets.

The difference between `Data Source` and `Asset`:  
**Data Source** Where are the events coming from which enable us to create the detection  
**Asset** What is being covered; These values should match with our CMDB registrations.


When someone asks me: "how many rules are there for my asset(s)" I would select the `Asset` tag.  
The question "How many detection rely on AWS logging" would be answered with `Data Source`

**Comment by eric-forte-elastic** [comment]
@SHolzhauer We made a [PR](https://github.com/elastic/detection-rules/pull/3115) to potentially address this issue. While we initially approached a solution very similar to what you have proposed, we ultimately ended up adding an environment variable one can set to skip unit tests for tags all together. 

Our current desired enforcement is that all tags are valid for non-Elastic rules, the tag enforcement is for the pre-built rules. You should be able to add what ever tags you like.

Would this solution address your request or is there still a need for adding an explicit `Asset: ` tag category to our list of tags? 
Thanks!
