### ISSUE TITLE
[Rule Tuning] Potential Malicious File Downloaded from Google Drive

### ISSUE THREAD

**Issue by BenB196** [elastic/detection-rules#2980]
## Link to rule

https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml

## Description

In relatively large deployments (500+ hosts) this rule will never successfully run and will always timeout.

This appears to be a cardinality issue mainly with:

https://github.com/elastic/detection-rules/blob/3813a08f597291054785d1b9d092a5d9b787d25b/rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml#L33-L37

If you were to look at a 9-minute window with just the first query part (`event.action in ("exec", "fork", "start", "load")`), there are a significant number of matches:

![image](https://github.com/elastic/detection-rules/assets/8277432/bfb9bb49-4732-407d-972a-91dba780843f)

This part has an extremely high cardinality, with `process.entity_id` alone have ~250k unique values.

![image](https://github.com/elastic/detection-rules/assets/8277432/e33ea2b4-cd69-4b90-8377-23aa43cdb96e)

If you look at the combine `host.id` and `process.entity_id` you can better see the cardinality problem.

![image](https://github.com/elastic/detection-rules/assets/8277432/4e3c9e84-918c-45b9-a0bd-8ae9ad3028bf)

I think that this cardinality issue is causing excessively long running rule times.

## Example Data

Timeout Errors:

![image](https://github.com/elastic/detection-rules/assets/8277432/df55a042-2f4f-4664-91ae-69fa7d8bbf6f)

**Comment by w0rk3r** [comment]
Tunings to this rule are being tracked in this issue: https://github.com/elastic/detection-rules/issues/3391#issue-2084881587
