### ISSUE TITLE
[Rule Tuning] Threat Intel Hash Indicator Match

### ISSUE THREAD

**Issue by MakoWish** [elastic/detection-rules#3030]
## Link to rule

[threat_intel_indicator_match_hash.toml](https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/threat_intel_indicator_match_hash.toml)

## Description

This rule currently watches for matches on "imphash" hashes. Unfortunately this may only mean a file was created in a similar manner to a malware sample, but it does not mean the file is inherently malicious. While an imphash may assist with forensics, this is unfortunately causing false positives to the point the rule is exceeding "the maximum alert limit for the rule execution". I am proposing the removal of "imphash" matches due to the infeasibility of investigating and whitelisting hashes based on imphash matches. 

## Example Data

![maximum_alerts](https://github.com/elastic/detection-rules/assets/26614684/fe456846-8b15-47c5-8318-2950fcf47bc8)

**Comment by FlorianHeigl** [comment]
I think I also just had this, it matches on abuse.ch with some hash I can't even find in their database.
(8.12.2)
honestly, it is crazy how much pops up at `99` criticality.
will triple check to make sure i'm not complaining about a legit issue ;)
