### ISSUE TITLE
[Bug] Unit Test For Placeholder Fields

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3083]
## Summary

We're not catching rules with placeholders in the investigation guides that do not have transforms.  For example https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/threat_intel_indicator_match_url.toml has $osquery_1 but no transforms. 

The unit test logic introduced in https://github.com/elastic/detection-rules/pull/2602, should be adjusted to account for this so that rules can not have place holders without the proper transform included.

```python
 def test_plugin_placeholders_match_entries(self):
        """Test that the number of plugin entries match their respective placeholders in note."""
        for rule in self.production_rules.rules:
            has_transform = rule.contents.get('transform') is not None
            has_note = rule.con…
```

```python
 def test_if_plugins_explicitly_defined(self):
        """Check if plugins are explicitly defined with the pattern in note vs using transform."""
        for rule in self.production_rules.rules:
            note = rule.contents.data.get('note')
            if note is not None:
```

**Comment by terrancedejesus** [comment]
We may need to also check if anchors exist but no transform.

**Comment by brokensound77** [comment]
#3085 should resolve this
