### ISSUE TITLE
[Rule Tuning] Remote File Copy to a Hidden Share

### ISSUE THREAD

**Issue by begin-thread** [elastic/detection-rules#3103]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_remote_file_copy_hidden_share.toml

## Description
Hi team!

Here is an extract of the original rule

```
process where host.os.type == "windows" and event.type == "start" and
  process.name : ("cmd.exe", "powershell.exe", "robocopy.exe", "xcopy.exe") and
  process.args : ("copy*", "move*", "cp", "mv") and process.args : "$"
```

When using robocopy, the rule does not trigger because the robocopy command does not need the following arguments :
```
process.args : ("copy*", "move*", "cp", "mv") 
```

Here is an example of a command used that should trigger an alert
```
D:\>robocopy c:\_P15\test \\p15\c$\_exfil /s /MIR /TEE /V /R:3 /W:3

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : September 15, 2023 9:38:35 PM
   Source : c:\_P15\test\
     Dest : \\p15\c$\_exfil\

    Files : .

  Options : . /V /TEE /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /R:3 /W:3
```

I tried this modification and it triggers an alert
```
process where host.os.type == "windows" and event.type == "start" and (
(  process.name : ("cmd.exe", "powershell.exe", "xcopy.exe") 
   and process.args : ("copy*", "move*", "cp", "mv" ) 
   or 
   ( process.name : ("robocopy.exe") )
)
and process.args : "*$*" ) 
```
Thank you so much.

**Comment by begin-thread** [comment]
@w0rk3r I just saw that you work on my new issue, thank you so much for the trust!

**Comment by w0rk3r** [comment]
Hey 👋🏼, sorry for taking this long to push this one, but it was included in this PR: https://github.com/elastic/detection-rules/pull/3364

Let me know if you see any other improvements on it, and thanks again for bringing this to our attention! Looking forward to your next contributions

**Comment by begin-thread** [comment]
Thanks for your work on that, I am working on my next one!
