### ISSUE TITLE
[FR] Include namespace in index patterns

### ISSUE THREAD

**Issue by jameswiggins** [elastic/detection-rules#3111]
**This feature request is related to a problem:**
I need to deploy these detection rules, but I am utilizing multiple Kibana spaces and each space corresponds to a specific namespace in my index [naming scheme](https://www.elastic.co/guide/en/fleet/8.9/data-streams.html#data-streams-naming-scheme). The index patterns in each rule are too broad for me to use. For example, the rules related to windows query the winlogbeat-* index pattern. I need to include a namespace in the index pattern like this: winlogbeat-production-*. 

**Here is the solution I would like:**
I would like a way to include a user-defined namespace in the index patterns. 

When installing the rules, I would like to be prompted for a value for a namespace and have that value injected into the index patterns for each rule. If that value is left empty, then the rules are deployed as is e.g. winlogbeat-*. 

**Alternative solutions I have considered:**
Currently I cannot edit the index patterns for pre-built rules in Kibana. Could that field be made editable without breaking the connection / ability to update the rule. I do not want to duplicate the rule and lose the connection to updates from this repository! 

This FR may be a duplicate of this one: https://github.com/elastic/detection-rules/issues/1917, but I am creating this one to create some more information about the request and hopefully get some more traction on the topic. I feel like if Elastic allows you to create indices with namespaces then these Elastic Detection Rules should account for that!! 

Thank you for considering this Feature Request!!

**Comment by Mikaayenson** [comment]
👋 @jameswiggins Thanks for opening the issue. It sounds like you would like to update the index for prebuilt rules in the UI. Is that correct? This may be an issue better tracked by the team that manages the detection engine if this is the case. Based on your description, there are no changes that need to be made to this repo. Is that correct?
