### ISSUE TITLE
[Bug] Prepackaged rules seem to no longer ship with Kibana

### ISSUE THREAD

**Issue by wallrik** [elastic/detection-rules#3132]
I'm on the current release (`8.10.2`), but haven't had the button to update built-in rules since April or May. Maybe version `8.6.x`?

I've checked out [the link](https://www.elastic.co/guide/en/security/current/prebuilt-rules-changelog.html) from the README:
https://github.com/elastic/detection-rules/blob/f6b6bee5c287d2d6806000ed3ce2b7c605a2bb35/README.md#L107

I've also seen the docs link [Downloadable rule updates > Update v8.10.2](https://www.elastic.co/guide/en/security/current/prebuilt-rule-8-10-2-prebuilt-rules-8-10-2-summary.html). But I'm not sure how to actually download them? 🤔

There are [instruction here](https://www.elastic.co/guide/en/security/current/prebuilt-rules-management.html#update-prebuilt-rules) that say "The **Rule Updates** tab doesn’t appear if all your installed prebuilt rules are up to date."

But that's not true.

Kibana does absolutely spam errors that it cannot access `epr.elastic.co`, but that's been a thing since before this stopped working. Have the rules moved to there? Is there a supported way for air gapped systems to update?

My instance tells me there are no rules to update, yet I know I'm missing a lot.
`GET /api/detection_engine/rules/prepackaged/_status`
```json
{
  "rules_custom_installed": "<redacted>",
  "rules_installed": 798,
  "rules_not_installed": 0,
  "rules_not_updated": 0,
  "timelines_installed": 10,
  "timelines_not_installed": 0,
  "timelines_not_updated": 0
}
```

It used to be very simple, so I'm sorry if I'm missing some obvious change. Thanks 🙏

**Comment by terrancedejesus** [comment]
👋🏽 hello @wallrik - We are sorry to hear that you are not receiving the latest rule updates as expected. As referenced in https://github.com/elastic/kibana/pull/143839, rules are not longer shipped with Kibana as of 8.7. Instead rules are packaged and stored in [epr.elastic.co](https://epr.elastic.co/search?package=security_detection_engine&prerelease=true&all=true&include_policy_templates=true) where Fleet downloads and installs the latest compatible package automatically. 

If your on `8.10.2`, then the latest compatible package is `8.10.3` as of this comment, which would only be pulled by Fleet from EPR and includes ~938 rules.

You had mentioned that the EPR pulls have been erroring for awhile now? This may be the reason why you have not received any updates. 

For air-gapped solutions, Kibana references a [fleet-packages.json](https://github.com/elastic/kibana/blob/main/fleet_packages.json) file which is used to pre-install packages during deployment, from what I understand.

**Comment by wallrik** [comment]
Thank you @terrancedejesus. That definitely seems to be the pull request to blame! 😅

The EPR errors are just failed connections due to not being connected to the internet. I filed an issue with that as well, just now at elastic/kibana#167195

Trying `https://epr.elastic.co/search?package=security_detection_engine` I can see a zip-file, but I'm not sure what to do with it?

That's unfortunately extremely annoying. (Maybe I can have our sales rep give a nice discount for the next renewal 😅)

Is there a documented/supported way to get that over to an offline system?

**Comment by terrancedejesus** [comment]
@wallrik apologies for the latency. We had to discuss this matter with another team to ensure we are sharing the correct information. From what we discussed, the following Kibana example can be used to install the prebuilt rules package. **_It will attempt to pull from EPR and if unsuccessful, should attempt to load from a ZIP locally that is shipped with the stack during deployment_**. Therefore, if you updated to 8.10.1, there should be a `8.10.1` or `8.10.2` package available locally.

This can be done via the dev console of your stack.
```console
POST kbn:/api/fleet/epm/packages/security_detection_engine/8.10.2
{
  "force": true 
}
```

Should look something similar to the following, which I did to test.
<img width="2535" alt="Screenshot 2023-09-28 at 12 24 21 PM" src="https://github.com/elastic/detection-rules/assets/99630311/0074c89d-b092-40fc-92c9-095e81ee380f">


Regarding UI use for updating the prebuilt rules package, this https://github.com/elastic/kibana/issues/136617 seems to be related and a known issue that is being worked on.

**Comment by wallrik** [comment]
Wow, that actually worked!!! 🎉 And I can see them in the Rules view as either not installed or needing updates. Fantastic! 😊

New results from the `_status` API:
```json
{
  "rules_custom_installed": "<redacted>",
  "rules_installed": 798,
  "rules_not_installed": 163,
  "rules_not_updated": 760,
  "timelines_installed": 10,
  "timelines_not_installed": 0,
  "timelines_not_updated": 0
}
```

Next, I questioned how I would know which version gets shipped with each Kibana release, for the next time I need to update. But I found the path, so I think I'm good to just look there. 😊

`/usr/share/kibana/node_modules/@kbn/fleet-plugin/target/bundled_packages/security_detection_engine-8.10.2.zip`

Also, whilst not being the topic of this issue, using the `kbn:` prefix in the dev console blew my mind! 🤯 I have always messed around with getting `curl` to authenticate when I needed to communicate with Kibana! This is a huge quality of life update. 😅

This issue can be closed from my end. But it would be nice if the air gapped use-case was documented. Cheers 👍

**Comment by terrancedejesus** [comment]
🥳 Happy to know you got the new rules installed!

We release detection rules bi-weekly for current-3 (8.10 -> 8.7), meaning each stack minor version receives it's own prebuilt rules package update. You can track these in our [tags](https://github.com/elastic/detection-rules/tags).

Regarding packages shipped with Kibana, you can reference the [fleet_packages.json](https://github.com/elastic/kibana/blob/8ffa8d8ee4d55b6da0f1f694e80dec9aee63c237/fleet_packages.json#L61C16-L61C17) in Kibana to determine this typically or search EPR with these parameters and it will show you the latest package available based on the parameter. - https://epr.elastic.co/search?package=security_detection_engine&kibana.version=8.10.1

The `kbn:` is very useful for Kibana APIs indeed! We will get this documented in our public security docs, potentially in [rules management](https://www.elastic.co/guide/en/security/current/prebuilt-rules-management.html). Pleasure getting through this with ya and enjoy your weekend!
