### ISSUE TITLE
[New Rule] Network Reconnaissance Activity

### ISSUE THREAD

**Issue by maof97** [elastic/detection-rules#3133]
Hello I am in the process of fixing some 'blind spots' in the MITRE ATT&CK™ matrix and I thought maybe you can use this rule too.

## Description
This rule detects the usage of "arp" or "ip neigh[bor]" commands that indicate network discovery activity.

## Required Info
process.name
process.args

### Target indexes
filebeat-*, logs-windows.*, etc. (the default ones)

### Target Operating Systems
windows, linux, macOS

### Tested ECS Version
8.10.2

### Query
`event.type: start and (process.name: (arp or arp.exe) or (process.name: (ip or ip.exe) and process.args : (neigh or neighbor or neighbour)))`

### New fields required in ECS/data sources for this rule?
No

### Related issues or PRs
-

### References
This will cover the following MITRE ATT&CK™:

[Reconnaissance (TA0043)](https://attack.mitre.org/tactics/TA0043)
- [Gather Victim Host Information (T1592)](https://attack.mitre.org/techniques/T1592)
- [Gather Victim Network Information (T1590)](https://attack.mitre.org/techniques/T1590) 

Greetings 
Martin

**Comment by terrancedejesus** [comment]
> Hello I am in the process of fixing some 'blind spots' in the MITRE ATT&CK™ matrix and I thought maybe you can use this rule too.

@maof97 thanks for submitting this issue for a potentially new rule. The logic itself seems sound, focusing on local network reconnaissance via ARP or `ip.exe` for neighboring hosts. This may be a decent [building block rule](https://www.elastic.co/guide/en/security/current/building-block-rule.html) as well depending on expected volume of alerts if commonly used by network admins.

If you'd like, you can create a pull request for this and commit the new rule. If you have questions on doing so, we'd be happy to help.

Other than this, if you have example data or screenshots those are helpful!
