### ISSUE TITLE
[Rule Tuning] Cobalt Strike Command and Control Beacon 

### ISSUE THREAD

**Issue by ChestoOfGlen** [elastic/detection-rules#3187]
## Link to rule
https://github.com/elastic/detection-rules/blob/f584fb6e31fa6a052a316fa108adf83e9a0d5e82/rules/network/command_and_control_cobalt_strike_beacon.toml

## Description
This rule has a lack of capitalisation in the query with respect to the AND/OR operators in the most recent update. This is causing this rule to match on the word "and" in Elasticsearch instead of properly applying the logic and searching for the C2 destination traffic events.
The specific issue is with the last "AND", however I think that all AND/OR operators should be capitalised as that appears to be the standard defined in the Elastic documentation for query string/Lucene syntax (https://www.elastic.co/guide/en/elasticsearch/reference/8.10/query-dsl-query-string-query.html#query-string-syntax).
![image](https://github.com/elastic/detection-rules/assets/37160206/64a6348f-18b9-42bd-90ff-ffca0af01f79)

This has caused a huge amount of false positives in our environment since the rule package was updated around October 14.
![z-browser-32438219137-6035031742390-39b55aa9de690dc68abf0f1a1bde316e879171dbd7ec1b5adb4d0cefe36f1482](https://github.com/elastic/detection-rules/assets/37160206/e9cd0646-bdc0-4cb2-94fe-7dd883d30d63)

Confirming that running this same Lucene query in Discover returns only false positive results as it matches on the word "and".
![image](https://github.com/elastic/detection-rules/assets/37160206/d9a1d707-e183-4331-8d07-bf6f8de44b79)

And running it with properly capitalised AND/OR operators returns the expected zero results.
![image](https://github.com/elastic/detection-rules/assets/37160206/67896a5b-e04d-49be-a18a-a0cb3dcbbb51)

Finally, just to note, the previous commit for this rule had the "AND" properly capitalised.
https://github.com/elastic/detection-rules/blob/48cf95c8ebded1f68cb106086002a136594146ad/rules/network/command_and_control_cobalt_strike_beacon.toml#L43

![image](https://github.com/elastic/detection-rules/assets/37160206/bea2d919-6f3e-47a4-8547-06ccca2620b7)

Solution is to, naturally, update the query to use correct capitalisation for the AND/OR operators, in line with what appears in the query string/Lucene Elastic docs as linked above.

**Comment by brokensound77** [comment]
This will be resolved by #3194

**Comment by w0rk3r** [comment]
Hey @ChestoOfGlen, as https://github.com/elastic/detection-rules/pull/3194 will min_stack the rule at 8.10+, I pushed https://github.com/elastic/detection-rules/pull/3196 to fix this in previous versions and other occurrences. Thanks for bringing this to our attention, looking forward to more contributions!
