### ISSUE TITLE
[FR] Add suppression for missing fields option

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3191]
**Is your feature request related to a problem? Please describe.**
In https://github.com/elastic/kibana/pull/155055, D&R added support to suppress by missing fields.

**Describe the solution you'd like**
Update the alert supression schemas to support the `missing_fields_strategy`

**Additional context**
- Related to https://github.com/elastic/detection-rules/issues/2657
- [Reported](https://elasticstack.slack.com/archives/C016E72DWDS/p1697367379109409) missing by community member

**Comment by zeuhl** [comment]
Thanks a lot @Mikaayenson !
