### ISSUE TITLE
[FR] Updating Official Python Support from 3.8

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#3213]
## Related Issues/PRs

- https://github.com/elastic/detection-rules/pull/3204

## Summary

We will want to update from just supporting Python 3.8 as there are new features we would like to utilize in later Python versions. Additionally, we are having increased branching in our dependencies (see above issue) in order to directly support Python 3.8. Based on discussions we likely will move official support from 3.8 -> (3.10-3.11)

**Comment by Mikaayenson** [comment]
Update to python3.12
