### ISSUE TITLE
[FR] Add support for UEBA tags in Unit Testing

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3220]
**Is your feature request related to a problem? Please describe.**
In order to build out the UEBA functionality, I would like to leverage new Rule tags. These will be used in different rules as part of their detection logic. 

**Describe the solution you'd like**
I would like to see unit testing receive support for the following tag:

"Use Case: UEBA"

**Additional context**
Additional context around this can be found in:
https://github.com/elastic/detection-rules/issues/3099
https://github.com/elastic/detection-rules/issues/3086
https://github.com/elastic/detection-rules/issues/3105
https://github.com/elastic/detection-rules/issues/3106

Or in a gdoc, that you can find by sending me a message. 
cc: @brokensound77 @imays11 @DefSecSentinel @Mikaayenson

**Comment by brokensound77** [comment]
As an alternative to introducing so many new tags, could we not just add the `UEBA` tag and then reference the threat mapping tactic to derive the same information? A rule could look like this:

```sql
any where event.kind == "signal" and kibana.alert.rule.tags in ("UEBA") and 
  kibana.alert.rule.threat.tactic.name == "Execution"
```

**Comment by Aegrah** [comment]
Not sure how I missed this comment. But that is a very good idea. I will change the request.
