### ISSUE TITLE
[Bug] flow_denied missing in "Accepted Default Telnet Port Connection" SIEM rule query

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#3264]
"Accepted Default Telnet Port Connection" missing `flow_denied`

`(event.dataset:network_traffic.flow or event.category:(network or network_traffic)) and event.type:connection and not event.action:(flow_dropped or denied or deny or flow_terminated or timeout or Reject or network_flow) and destination.port:23`

Must become:

`(event.dataset:network_traffic.flow or event.category:(network or network_traffic)) and event.type:connection and not event.action:(flow_dropped or flow_denied or denied or deny or flow_terminated or timeout or Reject or network_flow) and destination.port:23`

**Comment by willemdh** [comment]
Forgot to mention => The issue applies when using panw.panos dataset

**Comment by willem-dhaese** [comment]
Any news on this? This rule is still missing `flow_denied`

**Comment by w0rk3r** [comment]
@willem-dhaese just pushed a PR to fix it, sorry for the delay
