### ISSUE TITLE
[New Rule] Obfusctaed PowerShell Script

### ISSUE THREAD

**Issue by Samirbous** [elastic/detection-rules#3293]
using 4104 (PS script block logging) 

to be extended with more pattern cc @w0rk3r :
```
event.category:process and host.os.type:windows and powershell.file.script_block_text : ("[string]::join(''" or ".RePlACE(([char]" or " [char][int] $_")
```

![image](https://github.com/elastic/detection-rules/assets/64742097/8be7c59d-b0fe-4d90-ad37-3ac59b7db396)

**Comment by terrancedejesus** [comment]
Re-opening. @w0rk3r
