### ISSUE TITLE
[New Rule] Indicator match "reversed" rules

### ISSUE THREAD

**Issue by nkhristinin** [elastic/detection-rules#3315]
## Description

Our prebuilt IM rules try to match the last 1 hour of user data with the latest 30 days of threat indicators.

But with this setup, we potentially have missing alerts for any new threat indicators and user data which older than 1 hour.

Did we consider creating "reverse" IM rules, which will query the latest 1 hour of threat indicators and match again 30 days (or several days which make sense for the client) of user data?

In this case, if there new threat is discovered and published, we can retroactively say if the client was affected before with new threats.

## Potential problems

- Performance. As we know the IM rule can cause performance issues, but for this case it's unlikely, as there shouldn't be a lot of documents in the last 1 hour of threat indicators data.

- Potential duplicate alerts. Depending on the condition this rule can overlap with the original prebuilt IM rules. But it can be fixed by changing the time query for user events.

**Comment by willemdh** [comment]
+1 for more flexibility
