### ISSUE TITLE
[Rule Tuning] Account Password Reset Remotely

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#3332]
part of https://github.com/elastic/ia-trade-team/issues/232

## Link to rule
https://github.com/elastic/detection-rules/blob/9a9f5437f287c7cba1d1598f59c0304350111a3f/rules/windows/persistence_remote_password_reset.toml

## Description

The current query has several problems and also needs to be reviewed for optimizations, as there have been reports of expensive executions

```sql
sequence by winlog.computer_name with maxspan=5m
  [authentication where event.action == "logged-in" and
    /* event 4624 need to be logged */
    winlog.logon.type : "Network" and event.outcome == "success" and source.ip != null and
    source.ip != "127.0.0.1" and source.ip != "::1"] by winlog.event_data.TargetLogonId
   /* event 4724 need to be logged */
  [iam where event.action == "reset-password" and
   (
    /*
       This rule is very noisy if not scoped to privileged accounts, duplicate the
       rule and add your own naming convention and accounts of interest here.
     */
    winlog.event_data.TargetUserName: ("*Admin*", "*super*", "*SVC*", "*DC0*", "*service*", "*DMZ*", "*ADM*") or
    winlog.event_data.TargetSid : ("S-1-5-21-*-500", "S-1-12-1-*-500")
    )
  ] by winlog.event_data.SubjectLogonId
```

###  FP risk from concurrent logins

If a `network` login occurs, then is logged out or if a second concurrent `network` session occurs, followed by the `reset`, the query would errantly join on the events. IOW, a race condition could occur where concurrent sessions collide.

```
Session A: network logon    # event 0
Session B: local logon
Session B: reset-password  # event 1, FP
Session A: logout
```

To fix this, the state should be reset on _new successful remote logins_ or possibly even _log outs_. Or if there is some way to link the events by a common session ID, that would be simpler.

Here is the pseudocode 

```sql
....
until [authentication where 
  (event.action == "logged-in" and winlog.logon.type : "Network" and event.outcome == "success" and source.ip != null and
    source.ip != "127.0.0.1" and source.ip != "::1") or
  event.action == "logged-out"]
```

### review for optimizations

Some suggestions
* can we eliminate the leading wildcard on all of the `winlog.event_data.TargetUserName`
* can we minimize matches on the first even any?
* can we join these by any shared session id?
* do we need all 3 index patterns? Will sysmon match on this or only native logs?
* others?

## Example Data

Can you share some @Samirbous

**Comment by Samirbous** [comment]
> Can you share some @Samirbous

@brokensound77 
each logon will have a unique LogonId (thus the join by `winlog.event_data.TargetLogonId / winlog.event_data.SubjectLogonId` its unique per logon session and **not subject to race condition**), the only optimiz I see for this rule is to exclude service account for the winlog.event_data.TargetUserName for the first, most observed naming convention for service account are : `and not winlog.event_data.TargetUserName : ("svc*", "PIM_*", "_*_", "*-*-*", "*$")` (ofc if an adversary compromise a SVC account they will bypass the rule). 

Without the first event in the seq we can't differentiate between local password reset and remote password reset, thus I would suggest to just exclude SVC accounts (they generate lot of pwd reset) and add a note that this rule may cause performance impact (let the users decide if they need to enable/disable per their use cases appetite).
