### ISSUE TITLE
[Rule Tuning] Malicious Remote File Creation - possible deprecation

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#3333]
part of https://github.com/elastic/ia-trade-team/issues/232

## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/lateral_movement_malicious_remote_file_creation.toml

## Description
There seem to be several issues with this rules intent and its query. Additionally it has been identified as being non-performant.

`description = "Malicious remote file creation, which can be an indicator of lateral movement activity."`

```sql
sequence by host.name
[file where event.action == "creation" and process.name : ("System", "scp", "sshd", "smbd", "vsftpd", "sftp-server")]
[file where event.category == "malware" or event.category == "intrusion_detection"
and process.name:("System", "scp", "sshd", "smbd", "vsftpd", "sftp-server")]
```

* There needs to be a `maxspan`
* The join key is far too loose from a performance and efficacy perspective
* This query doesn't seem to do what the description conveys
   * this will match anytime those processes _locally_ create a file followed by what appear to be _alert_ docs (??? if so, the index is missing)
   * it doesn't seem to convey remote file creation at all - maybe (if the intent) a more accurate name would be local malicious file created from remote source - but even this still is not how the query is written

Without further clarifying context, **I would lean towards deprecating this rule altogether**

**Comment by terrancedejesus** [comment]
@brokensound77 - These rules were created by the secML team and migrated over during the analytic package rule migration into detection rules.

**Comment by brokensound77** [comment]
Thanks, ++ to deprecate
