### ISSUE TITLE
[Rule Tuning] VNC (Virtual Network Computing) from the Internet

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#338]
## Description
I propose to extend the query with the 169.254.0.0/16 address block:

As stated in [RFC3927](https://tools.ietf.org/html/rfc3927) the address block is the address block _is valid for communication with other devices connected to the same physical (or logical) link_ and later on in the RFC _The non-forwarding rule means that hosts may assume that all 169.254/16 destination addresses are "on-link" and directly reachable_

Mainly cloud environment are prone to generate False Positives with this range.

## Example Data
```
event.category:(network or network_traffic) and network.transport:tcp and destination.port >= 5800 and destination.port <= 5810 and
  not source.ip:(10.0.0.0/8 or 127.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16 or 169.254.0.0/16 or "::1") and
  destination.ip:(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16)
```

**Comment by threat-punter** [comment]
Hi @SHolzhauer. Thanks for reporting this 🙂

This was taken care of under #576
