### ISSUE TITLE
[Rule Deprecation] Review `Remote File Creation on a Sensitive Directory` for performance tuning

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3423]
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/lateral_movement_remote_file_creation_in_sensitive_directory.toml

## Description
This rule was highlighted by internal architect consulting members regarding performance concerns. Here are some areas for improvement:

- Limit indexes (file-only related data patterns for `logs-endpoints`
- Adjust file paths to use `?` to remove focus on `C:\` drive
- Review use of wildcards and alternatives

**Comment by terrancedejesus** [comment]
This rule is being deprecated in favor of higher fidelity rules for lateral movement that are behavior or machine learning dependent. Originally, this rule was examined to determine if it could be tuned for performance as it uses excessive wildcards and is a cross-platform rule.

After further review, it has been determined that we should tune this rule in favor of similar detection from the following rules:

- Unusual Time or Day for an RDP Session (ML)
- Spike in Remote File Transfers (ML)
- Spike in Number of Processes in an RDP Session (ML)
- Unusual Remote File Extension (ML)
- High Variance in RDP Session Duration (ML)
- High Mean of RDP Session Duration (ML)

**Comment by willem-dhaese** [comment]
Also noticed "[RPC (Remote Procedure Call) from the Internet](https://www.elastic.co/guide/en/security/current/rpc-remote-procedure-call-to-the-internet.html)" doesn't contain `logs-panw.panos-*` which contains the needed data. Might also impact other firewalls, so it might be better to just add `logs-*` ?
