### ISSUE TITLE
[Rule Tuning] Searching for Saved Credentials via VaultCmd

### ISSUE THREAD

**Issue by hack-1m** [elastic/detection-rules#3424]
## Link to rule
Searching for Saved Credentials via VaultCmd :

The rule detection refers only to process.name: "vaultcmd.exe" but during the test with rta I received logs of process.name: "VaultCmd.exe".

![Capture d’écran 2024-02-04 à 15 13 13](https://github.com/elastic/detection-rules/assets/140447513/8fd543f7-9d0f-4335-9b58-c4323845b998)

<img width="933" alt="Capture d’écran 2024-02-03 à 14 16 21" src="https://github.com/elastic/detection-rules/assets/140447513/bbe1f30e-f331-4e26-a77f-3b59b1bfb32b">

## Description

There are several ways to change this behaviour:

Solution 1 Change the rule from process.name: "vaultcmd.exe" to process.name: "vaultcmd.exe" or process.name: "VaultCmd.exe". 

Solution 2 in the winlogbeat pipeline we force all processes to lowercase to make sure that this kind of behaviour is caught on rules looking for exact patterns. However, this will make rendering less comfortable.

Solution 3 Deport the lowercase directly into the winlogbeat process.

We could do this in a logstash but we can't be sure that this middleware will be used to retrieve logs.

**Comment by Aegrah** [comment]
Hi @hack-1m, thanks for contacting us. 

FYI, EQL queries using the ":" symbol are case-insensitive, meaning that the EQL query provided above will trigger on both of your examples. KQL, the query language you used to query Discover, is case-sensitive, and therefore you will be required to specify the exact matching name when querying the Discover tab. 

Feel free to try-out the EQL query provided in the rule, within the security timelines feature and LMK if this solved your issue!

Thanks.

ref: [EQL case sensitivity docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/eql-syntax.html#:~:text=For%20case%2Dinsensitive%20matching%2C%20use%20in~%20.&text=Returns%20true%20if%20the%20value%20is%20not%20contained%20in%20the,matching%2C%20use%20not%20in~%20.&text=Returns%20true%20if%20the%20string%20is%20contained%20in%20the%20provided%20list).

**Comment by hack-1m** [comment]
My bad, Indeed, after investigation, the rule works correctly.
Sincerly

De : Ruben Groenewoud ***@***.***>
Date : lundi, 5 février 2024 à 10:19
À : elastic/detection-rules ***@***.***>
Cc : Hakim DJELILI ***@***.***>, Mention ***@***.***>
Objet : Re: [elastic/detection-rules] [Rule Tuning] Searching for Saved Credentials via VaultCmd (Issue #3424)

Hi @hack-1m<https://github.com/hack-1m>, thanks for contacting us.

FYI, EQL queries using the ":" symbol are case-insensitive, meaning that the EQL query provided above will trigger on both of your examples. KQL, the query language you used to query Discover, is case-sensitive, and therefore you will be required to specify the exact matching name when querying the Discover tab.

Feel free to try-out the EQL query provided in the rule, within the security timelines feature and LMK if this solved your issue!

Thanks.

ref: EQL case sensitivity docs<https://www.elastic.co/guide/en/elasticsearch/reference/current/eql-syntax.html#:~:text=For%20case%2Dinsensitive%20matching%2C%20use%20in~%20.&text=Returns%20true%20if%20the%20value%20is%20not%20contained%20in%20the,matching%2C%20use%20not%20in~%20.&text=Returns%20true%20if%20the%20string%20is%20contained%20in%20the%20provided%20list>.

**Comment by Aegrah** [comment]
Good to hear! I will then close out the issue.

**Comment by hack-1m** [comment]
thanks

De : Ruben Groenewoud ***@***.***>
Date : lundi, 5 février 2024 à 13:49
À : elastic/detection-rules ***@***.***>
Cc : Hakim DJELILI ***@***.***>, Mention ***@***.***>
Objet : Re: [elastic/detection-rules] [Rule Tuning] Searching for Saved Credentials via VaultCmd (Issue #3424)

Closed #3424<https://github.com/elastic/detection-rules/issues/3424> as completed.
