### ISSUE TITLE
[Bug] KQL fails validation on uppercase keywords

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3548]
**Describe the bug**
If you change any kquery keywords (`AND`, `OR`, `NOT`), from lowercase to uppercase in our TOML rule detections, loading will fail validation. The existing logic https://github.com/elastic/detection-rules/blob/main/lib/kql/kql/parser.py#L119-L122 has existed since the feature was introduced. If you try use the capital forms within Kibana, validation does not fail.

**To Reproduce**
1. Go to any kquery rule
2. Change the keywords to uppercase
3. Run unit tests or `python -m detection_rules view-rule <path to rule>`

**Expected behavior**
Validation should not fail. It should match Kibana.

**Screenshots**
![Screenshot 2024-03-28 at 5 24 48 PM (1)](https://github.com/elastic/detection-rules/assets/1636709/7140d3b7-600e-41d4-8f2f-6457243e4469)

**Additional context**
This problem inflates as we are pushing towards a DaC initiative where users should be able to export rules from Kibana and import into TOML representations within a forked repo of detection-rules. If customers try to use our importer today, it will fail on rules when it shouldn't. 

<details><summary>KQL Patch</summary>
<p>

We may be able to delete this method altogether or make a small tweak to bypass the assertion, although im not sure if there's some other context as to why this was added.

```diff
diff --git a/lib/kql/kql/parser.py b/lib/kql/kql/parser.py
index e3017f2fc..5e1161ddd 100644
--- a/lib/kql/kql/parser.py
+++ b/lib/kql/kql/parser.py
@@ -118,7 +118,7 @@ class BaseKqlParser(Interpreter):
 
     def assert_lower_token(self, *tokens):
         for token in tokens:
-            if str(token) != str(token).lower():
+            if str(token).lower() != str(token).lower():
                 raise self.error(token, "Expected '{lower}' but got '{token}'".format(token=token, lower=str(token).lower()))
 
     def error(self, node, message, end=False, cls=KqlParseError, width=None, **kwargs):
```

</p>
</details>

**Comment by brokensound77** [comment]
I think we should leave this as is. Even though uppercase is valid KQL, it is the _only_ way for lucence, and thus, has served as a mechanism for us to differentiate between KQL and lucene.

Thoughts?

**Comment by Mikaayenson** [comment]
The only concern I have is if for whatever reason a customer wants to export 500+ rules the capital keywords are valid in Kibana and subsequent try to import into TOML files (failing validation). It would force them to unnecessarily modify many rules manually.

**Comment by Mikaayenson** [comment]
Speaking with @brokensound77 we should add a normalizer utils method to lowercase keywords.

**Comment by eric-forte-elastic** [comment]
> Speaking with @brokensound77 we should add a normalizer utils method to lowercase keywords.

If we add a normalizer, would it be correct to assume then that we would be modifying the rules contents on load/import? Would this not still cause an issue when exporting? Since exporting the rules still loads them and then exports them from the python object (which I think would be normalized)?

Alternatively, would this normalization only be done for validation?

**Comment by Mikaayenson** [comment]
> > Speaking with @brokensound77 we should add a normalizer utils method to lowercase keywords.
> 
> 
> 
> If we add a normalizer, would it be correct to assume then that we would be modifying the rules contents on load/import? Would this not still cause an issue when exporting? Since exporting the rules still loads them and then exports them from the python object (which I think would be normalized)?
> 
> 
> 
> Alternatively, would this normalization only be done for validation?

We would want this to occur on import/create. Historically this has been used to differentiate Lucene and Kql where capitalization matters for lucene.

**Comment by eric-forte-elastic** [comment]
> > > Speaking with @brokensound77 we should add a normalizer utils method to lowercase keywords.
> > 
> > 
> > If we add a normalizer, would it be correct to assume then that we would be modifying the rules contents on load/import? Would this not still cause an issue when exporting? Since exporting the rules still loads them and then exports them from the python object (which I think would be normalized)?
> > Alternatively, would this normalization only be done for validation?
> 
> We would want this to occur on import/create. Historically this has been used to differentiate Lucene and Kql where capitalization matters for lucene.

Gotcha, just to make sure I understood correctly, we then are not concerned about the case where a user imports a rule, and then exports to Kibana, and then exports from Kibana back to detection rules because resulting TOML file would be the same regardless of the format of the initial starting ndjson?

![image](https://github.com/elastic/detection-rules/assets/119343520/64b84edc-7e59-4616-a7ee-c26f79286704)
