### ISSUE TITLE
[FR] Back-porting Version Trimming

### ISSUE THREAD

**Issue by shashank-elastic** [elastic/detection-rules#3563]
**Is your feature request related to a problem? Please describe.**
Keep a check on the number of versions that the updates are back ported to. Thumb Rule is to stick with. release cadence of latest and latest-3 versions 

**Describe the solution you'd like**
Limit back porting to 8.10 as of now we are running GA of 8.13 

**Describe alternatives you've considered**
NA

**Comment by shashank-elastic** [comment]
Essentially:
- Dropping validation checks to latest - 3 (stack-schema-map.yaml)
- Backport checks will only be latest - 3 as well (lock-versions.yml)
- Moving forward we will always drop one then bumping to the next version.
- We need to decide when to make this change.

**Comment by Mikaayenson** [comment]
- Prior to trimming during the release, tag the branch.
- We should release - 3, but preserve - 5

**Comment by shashank-elastic** [comment]
This has to be completed this sprint cycle, Making this Urgent from conversation with @Mikaayenson

**Comment by shashank-elastic** [comment]
- Discussion On `test_previous_entries_gte_current_min_stack`

   - Should we really trim lock versions, if we find no value on this then we really dont need to run a trim.
   - IF we decide no trimming on lock versions file is needed this test case has to be removed. 
   - If we don't remove this test case, then we always have to trim every minor release and update min_stack to rules across. 

- We are clear on trimming to 5 versions and releasing to 3 
- It was decided to open a separate PR with necessary changes and put this in Design Review for further discussions. 
- Please note this has to be completed in this cycle, so will be driving this 🔥

**Comment by shashank-elastic** [comment]
PR Up for review : https://github.com/elastic/detection-rules/pull/3681
