### ISSUE TITLE
Threshold rule less than or checking when count is 0

### ISSUE THREAD

**Issue by kulbozz** [elastic/detection-rules#3617]
**Is your feature request related to a problem? Please describe.**
Problem statement: monitor for a condition with less than operator, supporting 0.

**Describe the solution you'd like**
I'm trying to implement a rule for monitoring when a rule hasn't has any alerts in X time period. Threshold rule only supports greater than and trying in ESQL counting also doesn't not count unless a value is present.

**Describe alternatives you've considered**
Here's an example in ESQL counting the number of building block alerts:

```
from .alerts-security.alerts
| where kibana.alert.building_block_type == "default"
| stats alert_count = count(*) by kibana.alert.rule.name
| where alert_count == 0
```

I want to know if a building block rule has 0 alerts in the last 1 week.

**Comment by w0rk3r** [comment]
Hey @kulbozz, while this is not a complete solution to your problem, here is a starting point to check whether or not a detection rule fired using ES|QL:

```
from .ds-.kibana-event*
| where kibana.alert.rule.execution.metrics.alert_counts.new IS NOT NULL
| stats alert_count=SUM(kibana.alert.rule.execution.metrics.alert_counts.new) by rule.name
| where alert_count == 0
```

To differentiate whether or not it is a building block rule, you'll need to create an enrich policy and the ENRICH command in ES|QL.

ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-enrich-data.html#esql-set-up-enrich-policy & https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-commands.html#esql-enrich
