### ISSUE TITLE
[FR][DAC] Consideration: expose kql parse parameters for custom rules validation

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#3624]
**Note**: this work will target the [DAC-feature](https://github.com/elastic/detection-rules/tree/DAC-feature) branch

related to #3407

---

**This is a consideration and not a commitment to work at this point**. We should review the feasibility and supportability. If it is doable and not deemed maintainable, we can move the example code to the DAC reference for users to manually implement.

---

Based on https://github.com/elastic/detection-rules/pull/3568, I will look at allowing normalization on KQL queries for custom rules and exposed in the config. (This allows uppercase operators)

https://github.com/elastic/detection-rules/pull/3407#issuecomment-2038338946

**Comment by eric-forte-elastic** [comment]
I think this is a result of the reversion of https://github.com/elastic/detection-rules/pull/3574. I think we just need a small PR to on the setting of a custom rule directory, set the normalization flag to be true instead of false.

**Comment by brokensound77** [comment]
upon further consideration and observations of how this should be leveraged, I don't think it should be default, but a config parameter. Noted in PR

**Comment by eric-forte-elastic** [comment]
PR merged.
