### ISSUE TITLE
[FR][DAC] Add exceptions importing from ndjson

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3674]
**Note**: this work will target the [DAC-feature](https://github.com/elastic/detection-rules/tree/DAC-feature) branch

related to #3407

---

**This is a consideration and not a commitment to work at this point**. We should review the feasibility and supportability. If it is doable and not deemed maintainable, we can move the example code to the DAC reference for users to manually implement.

---

Currently in the DAC-feature branch, we can manage exception list using a TOML file structure. When rules are exported/imported into kibana, they are uploaded with the rules using the rules API. This is a one way approach that allows users to manage exception list for DAC.

If users want to preserve their existing exceptions (from Kibana) in VCS using a DAC approach, they would have to manually write the exceptions in our TOML format. 

It would be great if we could export exceptions (only ones associated to a detection rule), and import into our TOML format.

**Comment by eric-forte-elastic** [comment]
## Update 6/20/24
- This issue is expected to be in review by July 1st.

**Comment by eric-forte-elastic** [comment]
## Update 7/7/24

We are also considering as part of this issue adding support for directly importing and exporting exceptions lists from the CLI in the following PRs:
- https://github.com/elastic/detection-rules/pull/3869
- https://github.com/elastic/detection-rules/pull/3870

**Comment by eric-forte-elastic** [comment]
PRs merged, issue development complete.
