### ISSUE TITLE
[FR][DAC] Unit Test Locked Version Support for Custom Config

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#3682]
## Summary
Currently when specifying a custom directory some of the unit tests in DAC fail. Specifically these are locked versions related checks. Since the branches specified in the stack-schema-map are expected to be different in a custom config, we will need a way to handle cases where customers wish to run unit tests with these custom configs.

I see two different approaches that we could take to address this problem, or we could use a combination of both.
1. We could use the unit tests configs to have users bypass these checks by default unless they would like to have them. 
2. We could use the `bypass_version_lock` config value when merged to also apply for these test cases

Example:
`tests/test_gh_workflows.py` which tests that the default versions in the lock-versions workflow mirror those from the schema-map. 
![lock_version_test](https://github.com/elastic/detection-rules/assets/119343520/f528479d-43c5-4e36-9552-b859492da9b5)

**Comment by Mikaayenson** [comment]
I'm not sure if we need a unit test for this. If a user is using custom rules, wouldn't these test cases be just something they bypass in their config?

**Comment by eric-forte-elastic** [comment]
Good discussion, going to add a flag in the setup-config to be a helper.
