### ISSUE TITLE
[New Rule] Unusual Svchost ChildProc - ChildLess Services

### ISSUE THREAD

**Issue by Samirbous** [elastic/detection-rules#369]
## Description

This rule identify unusual child processes of svchost where this last is hosting a servicedll that is not spawning normally child processes.

This is related to the activity of [baselining svchost child processes activity](https://docs.google.com/spreadsheets/d/1Uc30Hq1YTgC1U-ALrw76QGBWQGk6h1AfQEuLcqvbXKg/edit#gid=1536555953) (static analysis).

## Required Info

- **Eventing Sources:**

- **Target Operating Systems:**

- **Platforms**

- **Target ECS Version:** x.x.x
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**

**Comment by eklike100** [comment]
@Samirbous Any attack sources to check this rule?
