### ISSUE TITLE
[Rule Tuning] Attempts to Brute Force a Microsoft 365 User Account

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/detection-rules#3694]
## Link to rule

https://www.elastic.co/guide/en/security/current/attempts-to-brute-force-a-microsoft-365-user-account.html

## Description

This is a threshold rule that triggers on Failed logons for Entra/Azure AD or Exchange. 

There have been previous tuning issues to identify exceptions, particularly relating to MFA related failures. 

Additional exceptions are needed for this query.

|field|value|reason|
|---|---|---|
|`o365.audit.LogonError`|`SsoArtifactExpiredDueToConditionalAccess`|This is a failure generated after a valid session has expired. Clients and Browsers may keep attempting to poll, failing with this error every few minutes.|
|`o365.audit.LogonError`|`UserStrongAuthExpired`| similar to above. These are much lower volume but for any specific user it will trigger the rule|
|`o365.audit.LogonError`|`PasswordResetRegistrationRequiredInterrupt`|Not nearly as high volume, but this is not really a failure. The login session is interrupted to force or ask a user to create/update their self-service password reset instructions.|
|`o365.audit.LogonError`|`SsoUserAccountNotFoundInResourceTenant`|A variation of the existing exception, when the failure is via SSO.|

I've also added an ES|QL aggregation for count by LogonError with sample data over the last week. The first item is by far the most high volume. 

Another possible exception may be `DeviceAuthenticationRequired` as it seems to spike over weekends when an expired session generates failures until the user logs in the following week. I don't know what specifically is causing it though  since it is almost exclusively to users & devices where we don't have any policies requiring device auth. 

Existing Query

```
event.dataset:o365.audit and event.provider:(AzureActiveDirectory or Exchange) and
  event.category:authentication and event.action:(UserLoginFailed or PasswordLogonInitialAuthUsingPassword) and
  not o365.audit.LogonError:(UserAccountNotFound or EntitlementGrantsNotFound or UserStrongAuthEnrollmentRequired or UserStrongAuthClientAuthNRequired or InvalidReplyTo)
```

ES|QL to identify top `o365.audit.LogonError`

```
from logs-o365.audit-default
| where event.action in ("UserLoginFailed", "PasswordLogonInitialAuthUsingPassword")
| where event.provider in ("Exchange", "AzureActiveDirectory")
| where o365.audit.LogonError not in ("UserAccountNotFound", "EntitlementGrantsNotFound", "UserStrongAuthEnrollmentRequired" ,"UserStrongAuthClientAuthNRequired" , "InvalidReplyTo")
| stats Count = count() by o365.audit.LogonError
| sort Count desc
```
Top events. Suggested exceptions are in bold.

|Count|`o365.audit.LogonError`|
|---|---|
|**41457**| **SsoArtifactExpiredDueToConditionalAccess**|
|9919| DeviceAuthenticationRequired|
|8090| UserStrongAuthClientAuthNRequiredInterrupt|
|4175| IdsLocked|
|3669| AuthenticationFailedSasError|
|**2294**| **PasswordResetRegistrationRequiredInterrupt**|
|1723| InvalidUserNameOrPassword|
|**740**| **UserStrongAuthExpired**|
|320| TriggerBrowserCapabilitiesInterrupt|
|**267**| **SsoUserAccountNotFoundInResourceTenant**|
|250| FlowTokenExpired|
|121| UserUnauthorized|
|87| UserStrongAuthEnrollmentRequiredInterrupt|

## Example Data

Existing query with these additions

```
event.dataset:o365.audit and event.provider:(AzureActiveDirectory or Exchange) and
  event.category:authentication and event.action:(UserLoginFailed or PasswordLogonInitialAuthUsingPassword) and
  not o365.audit.LogonError:(UserAccountNotFound or EntitlementGrantsNotFound or UserStrongAuthEnrollmentRequired or UserStrongAuthClientAuthNRequired or InvalidReplyTo or SsoArtifactExpiredDueToConditionalAccess or PasswordResetRegistrationRequiredInterrupt or SsoUserAccountNotFoundInResourceTenant or UserStrongAuthExpired )


```

**Comment by jvalente-salemstate** [comment]
@w0rk3r if you haven't started and it's okay with you, I can submit a PR for this. I've got a commit ready with the changes and can submit that after running any tests.

**Comment by w0rk3r** [comment]
Hey @jvalente-salemstate that would be awesome! Feel free to open the PR

**Comment by jvalente-salemstate** [comment]
A note in case someone does know exactly what `DeviceAuthenticationRequired` means. I've left it out of my PR since I can't make sense of why I'm seeing it. 

We're a university and this only shows with a browser user agent on Mac OS. It also is only showing on student personal devices--which is where I am lost on this. We've not enrolled them yet in CA policies, and we do not require device auth on any devices, even our own managed ones. 
The volume and rate at which they're logged all appear machine generated and provide much more noise than any signal. However, without knowing why exactly it's here, being triggered, I wasn't comfortable including it.
