### ISSUE TITLE
[FR][DAC] Update Handling Data Views from Kibana

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#3697]
dependent on #3817 

## Summary 

This issue is to update how we handle Data Views from Kibana stemming from some feedback Justin had in this comment [here](https://github.com/elastic/detection-rules/pull/3679#pullrequestreview-2064609443).

Within `QueryRuleData`, we can add a new property `index_or_dataview -> list[str]` which returns whichever is set. The reason for making it a list even though dataview is a string is because we always iterate, so it saves us from doing a type check every time.

Then, we will need to search for every use of `data.index` (or `rule.contents.data.index` and all variations) and replace them with this new property where it makes sense.

To ensure this works properly, the bug in #3817 should be merged first, and backported

**Comment by brokensound77** [comment]
To keep things clean, I broke out the scope of the bug into #3817. The bug fix should target main and this work `DAC-feature`

**Comment by eric-forte-elastic** [comment]
PR merged.
