### ISSUE TITLE
[Rule Tuning] Attempt to Retrieve User Data from AWS EC2 Instance

### ISSUE THREAD

**Issue by ar3diu** [elastic/detection-rules#3720]
## Link to rule
https://github.com/elastic/detection-rules/blob/34294fbe6de810c7f2a01f3d16a0929c72b40a2f/rules_building_block/discovery_userdata_request_from_ec2_instance.toml#L23

## Description

Change the index pattern to `logs-aws.cloudtrail-*`.
## Example Data

![image](https://github.com/elastic/detection-rules/assets/61625853/173efa24-8ea0-49f7-9657-7cf4fa29a7aa)

**Comment by terrancedejesus** [comment]
This has been completed per https://github.com/elastic/detection-rules/pull/3770. Thank you for bringing this to our attention!
