### ISSUE TITLE
detection-rules-cfg.json

### ISSUE THREAD

**Issue by ladysady** [elastic/detection-rules#377]
Hello, 

For the file in the root directory pleae let me know if the following json will work: 

{
  "elastic_search_url": {},
  "kibana_url": {},
  "cloud_id": {},
  "elasticsearch_username": {},
  "elasticsearch_password": {},
  "kibana_username": {},
  "kibana_password": {}
}

**Comment by brokensound77** [comment]
Hello 👋 @ladysady,

You would need to tweak some of those slightly according to https://github.com/elastic/detection-rules/blob/main/CLI.md#setup-a-config-file. The easiest way to see which arguments _can_ be parsed from the config file and what their expected keys are, would be to look for usage of `getdefault` in the command

https://github.com/elastic/detection-rules/blob/60b3d47efdf81a9232af2a39a4337bcb01dca9d2/detection_rules/kbwrap.py#L15-L22

The values would also just be strings such as 

```json
"es_username": "my_username"
```

Hope this helps.
