### ISSUE TITLE
McAfee Trojan detection on detection-rules-main\rta\bin\Installer.msi

### ISSUE THREAD

**Issue by ferryversteeg** [elastic/detection-rules#378]
![image](https://user-images.githubusercontent.com/58332754/96241886-1321cc00-0fa3-11eb-8075-2861954997d3.png)

**Comment by threat-punter** [comment]
Thanks for reaching out @ferryversteeg. This is a false positive. `Installer.msi` is a benign MSI Installer file that is executed by the `[MsiExec with HTTP Installer](https://github.com/elastic/detection-rules/blob/main/rta/msiexec_http_installer.py)` Red Team Automation (RTA) script.
