### ISSUE TITLE
[Rule Tuning] Suspicious Inter-Process Communication via Outlook

### ISSUE THREAD

**Issue by ar3diu** [elastic/detection-rules#3803]
## Link to rule
https://github.com/elastic/detection-rules/blob/259efaf7165be7105a2fb990e3b7146ad6997f8f/rules/windows/collection_email_outlook_mailbox_via_com.toml#L17

## Description

Both events in the sequence should be related to the same host. I encountered false positives where an alert was triggered for two events from two different hosts.

## Example Data

```
sequence by host.id with maxspan=1m
[...] by process.executable
[...] by process.Ext.effective_parent.executable
```

**Comment by w0rk3r** [comment]
Hey @ar3diu, do you want to open a PR for this one or should I do it?

**Comment by ar3diu** [comment]
I just submitted it: https://github.com/elastic/detection-rules/pull/3806
_(There is a warning there regarding the contributor agreement. I just signed it but probably hasn't been updated yet)_
