### ISSUE TITLE
[Bug] PowerShell Suspicious Discovery Related Windows API Functions - not file.path not working as expected.

### ISSUE THREAD

**Issue by BugOrFeature** [elastic/detection-rules#3837]
**Describe the bug**
Rule: "PowerShell Suspicious Discovery Related Windows API Functions" does not properly exclude based on "and not file.path : ?\:\\\\ProgramData\\\\Microsoft\\\\Windows?Defender?Advanced?Threat?Protection\\\\DataCollection\\\\*"

**To Reproduce**
1. Execute powershell with discovery api functions from the excluded folder
2. Rule PowerShell Suspicious Discovery Related Windows API Functions should not be triggered
3. Rule is triggered and an alert is created

**Expected behavior**
No alerts should be created, as the script is ran from an excluded folder.

**Screenshots**
![image](https://github.com/elastic/detection-rules/assets/15825757/8228d533-e95b-4c25-a216-730eddc35338)

**Additional context**

**Comment by w0rk3r** [comment]
Hey @BugOrFeature, what stack version are you using?

**Comment by w0rk3r** [comment]
I've looked at the screenshot, and the rule version seems previous to https://github.com/elastic/detection-rules/pull/3505.

![image](https://github.com/elastic/detection-rules/assets/26856693/6b684de2-0c1b-4ace-934f-f804960be422)

For stack versions 8.12+, the syntax we were using to exclude Windows paths in KQL stopped working. So, we replaced it with Query DSL filters to exclude these FP patterns. If this is the case, updating the rules will do the job here. If it is not, please feel free to reopen the issue and provide more stack details, and we will look into it.

**Comment by BugOrFeature** [comment]
Thanks a lot! Updating the rules that solved the issue!
