### ISSUE TITLE
[FR] Adopt DAC with current ruleset

### ISSUE THREAD

**Issue by acumen-kevinr** [elastic/detection-rules#3907]
### Repository Feature

Detections-as-Code (DaC) - (primarily custom rule management)

### Problem Description

We have over 1,000 rules that we utilise within Kibana and we would like to transition to DAC as a methodology...is there a way for us to export our entire ruleset and have them generated in the relevant way (i.e. toml) within the DAC code? 

I know we can do one rule at a time, kind of, but realistically we'd want to be able to do them all in bulk. 

Let me know if there are any plans to add this or if theres a workaround.

### Desired Solution

As above - ability to import all rules

**Comment by eric-forte-elastic** [comment]
Hi @acumen-kevinr thanks for reaching out! Yes, you can do this using the DAC code. This code is currently in alpha on the DAC-feature branch of detection rules. The command I think you would be most interested in is the `detection_rules kibana export-rules` command. This will export all of the custom rules from your Kibana instance (you can also specify a specific space to use via `--space`) to toml files in your repo. Also there is an accompanying `import-rules` command you can run to push the rules from your repo to Kibana. 

Here are some reference materials that might be useful:

- An example Github Action workflow that pulls custom rules from a specified space and makes a PR to the fork of detection rules: [link](https://github.com/eric-forte-elastic/detection-rules-dac-demo/blob/6fdd0b121320ec5b8e117c9ce4bdbfcbdb2cdf1e/.github/workflows/pull_latest_from_elastic_security.yml#L38)
- Example Github Action workflow that pushes the rules back to Kibana: [link](https://github.com/eric-forte-elastic/detection-rules-dac-demo/blob/6fdd0b121320ec5b8e117c9ce4bdbfcbdb2cdf1e/.github/workflows/push_latest_to_elastic_security.yml#L70)
- Demo video walking through the example setup we have in that repo: [link](https://dac-reference.readthedocs.io/en/latest/etoe_reference_example.html#demo-video)

Please let us know if you run into any trouble or have any additional feedback, we are happy to help! Thanks!

**Comment by eric-forte-elastic** [comment]
Now we have merged in the DAC-feature branch https://github.com/elastic/detection-rules/pull/3889 in main, these features are now in beta. Please check out our [quick start guide](https://dac-reference.readthedocs.io/en/latest/etoe_reference_example.html#quick-start-example-detection-rules-cli-commands) for how to get started.
