### ISSUE TITLE
[Rule Tuning] AWS S3 Object Versioning Suspended

### ISSUE THREAD

**Issue by tttttx2** [elastic/detection-rules#3950]
### Link to Rule

https://github.com/elastic/detection-rules/blob/main/rules/integrations/aws/impact_s3_object_versioning_disabled.toml

### Rule Tuning Type

None

### Description

While technically not strictly required, it seems that there is no index defined on this rule. This does not seem to regularly occur otherwise.

Judging by other rules, index should probably be something like this: `["filebeat-*", "logs-aws.cloudtrail-*"]`

**Comment by w0rk3r** [comment]
Nice catch, @tttttx2. Thanks for bringing this to our attention. We will either introduce a unit test or mark this field as required so it doesn't happen again. Thanks!
