### ISSUE TITLE
[Rule Tuning] RPC (Remote Procedure Call) from the Internet

### ISSUE THREAD

**Issue by willem-dhaese** [elastic/detection-rules#3998]
### Link to Rule

[RPC (Remote Procedure Call) from the Internet](https://www.elastic.co/guide/en/security/current/rpc-remote-procedure-call-to-the-internet.html)

### Rule Tuning Type

Data Quality - Ensuring integrity and quality of data used by detection rules.

### Description

Noticed "[RPC (Remote Procedure Call) from the Internet](https://www.elastic.co/guide/en/security/current/rpc-remote-procedure-call-to-the-internet.html)" doesn't contain `logs-panw.panos*` which contains the needed data. Might also impact other firewalls, so it might be better to just add `logs-*` ? 

It might be useful to check all rules using `logs-network_traffic.*` and not `logs-*`..

**Comment by willem-dhaese** [comment]
- RPC (Remote Procedure Call) to the Internet
- RPC (Remote Procedure Call) from the Internet
- VNC (Virtual Network Computing) to the Internet
- VNC (Virtual Network Computing) from the Internet

This used to work before we migrated the panw Filebeat module to Elastic Agent PANW Integration...

**Comment by willem-dhaese** [comment]
Same for:

- Potential Network Sweep Detected

**Comment by willem-dhaese** [comment]
Please have a look at these rules @w0rk3r 🙏

**Comment by willem-dhaese** [comment]
Another : Potential SYN-Based Network Scan Detected

Ok, can `logs-panw.panos*` be added then?

Watch the `logs-panw.panos*`. We separated the different PANW subcategories to:

logs-panw.panos.traffic
logs-panw.panos.threat

etc.. (togheter with @ckauf )

This worked when we were using Filebeat panw module. it's really dissapointing this just stopped working after migrating to Elastic Agent integration... 

I heate having to duplicate rules, as it's a lot of work on our side to maintain all of the duplicated rules.

**Comment by Samirbous** [comment]
Hi @willem-dhaese thank you for reporting this. We have merged an [update](https://github.com/elastic/detection-rules/pull/4089) to add PAN-OS index to the relevant rules.
