### ISSUE TITLE
[Bug] Problem with a scaled_float field

### ISSUE THREAD

**Issue by vedard** [elastic/detection-rules#401]
**Describe the bug**
Hi, I want to create a rule using the field `system.process.cpu.total.norm.pct` from metricbeat, but there is an error when I run the unit tests. 

**To Reproduce**
1. Create a new rule
2. Use this query `event.module: system and system.process.cpu.total.norm.pct > 0.85`
3. Run tests `make test`
```
Error at line:1,column:62
Value doesn't match system.process.cpu.total.norm.pct's type: scaled_float
event.module: system and system.process.cpu.total.norm.pct > 0.85
                                                             ^^^^
```

**Expected behavior**
The test should pass, I don't think there is anything wrong in the query.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Version: Python 3.8.6

**Additional context**
In `parser.py`, the `convert_value` method does not seem to support a `scaled_float` field only `float` or `long`
```py
    def convert_value(self, field_name, python_value, value_tree):
        field_type = self.get_field_type(field_name)
        value_type = self.get_literal_type(python_value)

        if field_type is not None and field_type != value_type:
            if field_type in STRING_FIELDS:
                return eql.utils.to_unicode(python_value)
            elif field_type in ("float", "long"):
                try:
                    return float(python_value) if field_type == "float" else int(python_value)
                except ValueError:
                    pass
            elif field_type == "ip" and value_type == "keyword":
                if "::" in python_value or self.ip_regex.match(python_value) is not None:
                    return python_value

            raise self.error(value_tree, "Value doesn't match {field}'s type: {type}",
                             field=field_name, type=field_type)

        # otherwise, there's nothing to convert
        return python_value
```

**Comment by rw-access** [comment]
Is this still an issue with the latest `main`?

**Comment by vedard** [comment]
Yes, the issue is still there.

We fix it in our fork by adding the `scaled_float` type to this line:
https://github.com/elastic/detection-rules/blob/eb40c52c7c9cf7e4354fe975f10f4b4e917cd077/kql/parser.py#L178
