### ISSUE TITLE
Browser Extension Install - filters on wrong field

### ISSUE THREAD

**Issue by willemri** [elastic/detection-rules#4059]
### Link to Rule

https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_browser_extension_install.toml

### Rule Tuning Type

Data Quality - Ensuring integrity and quality of data used by detection rules.

### Description

The wrong field is being used to filter on: it should be event.type: "creation"  (instead of event.action)

in my logs, when i review the different fields, we have:
event.action: "File created (rule: FileCreate)"
event.type: "creation"

i've also changed the index from ["logs-endpoint.events.file-*"] to ["winlogbeat"]

### Example Data

file where host.os.type == "windows" and event.type: "creation" and 
(
  /* Firefox-Based Browsers */
  (
    file.name : "*.xpi" and
    file.path : "?:\\Users\\*\\AppData\\Roaming\\*\\Profiles\\*\\Extensions\\*.xpi" and
    not 
    (
      process.name : "firefox.exe" and
      file.name : ("langpack-*@firefox.mozilla.org.xpi", "*@dictionaries.addons.mozilla.org.xpi")
    )
  ) or
  /* Chromium-Based Browsers */
  (
    file.name : "*.crx" and
    file.path : "?:\\Users\\*\\AppData\\Local\\*\\*\\User Data\\Webstore Downloads\\*"
  )
)

**Comment by w0rk3r** [comment]
Hey @willemri, just included a fix for this on this one: https://github.com/elastic/detection-rules/pull/4056
