### ISSUE TITLE
Failing rules after elastic and kibana update on 8.14.3

### ISSUE THREAD

**Issue by PaHuf** [elastic/detection-rules#4063]
Hello,
we upgraded elastic and kibana from 8.8.2 to 8.14.3 and also the windows integration from 1.xx to 2.0 and noticed that following rules are failing now:

- Potential Credential Access via DCSync (unknown column [winlog.event_data.Properties])
- AdminSDHolder SDProp Exclusion Added (unknown column [winlog.event_data.AttributeLDAPDisplayName])
- Access to a Sensitive LDAP Attribute (unknown column [winlog.event_data.Properties])
- Remote Scheduled Task Creation via RPC (unknown column [winlog.event_data.RpcCallClientLocally])
- Startup/Logon Script added to Group Policy Object (unknown column [winlog.event_data.AttributeLDAPDisplayName])
- Windows Service Installed via an Unusual Client (unknown column [winlog.event_data.ParentProcessId])
- Scheduled Task Execution at Scale via GPO (unknown column [winlog.event_data.AttributeLDAPDisplayName])
- Temporarily Scheduled Task Creation (unknown column [winlog.event_data.TaskName])
- Group Policy Abuse for Privilege Addition (unknown column [winlog.event_data.AttributeLDAPDisplayName])

Prebuilt Security Detection Rules is on Version 8.14.10 and we updated the Rules. System integration is on the newest version as well as it's required for the above Rules as well.

It'd be great, if you could help me with this issue. Thank you.

**Comment by w0rk3r** [comment]
Hey @PaHuf, awesome that you're upgrading, great news! 

Is this a hard fail or a warning? If this is a warning, it is caused because no events that contain this field have been ingested yet, and the fields under `winlog.event_data.*` are dynamically parsed (https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html).

Once the events that contains the fields are ingested, this warning will go away as the mapping will be populated with them. 

Some of these rules have Setup instructions that are required in order to collect the needed events, for example, `AdminSDHolder SDProp Exclusion Added` has the following:

```
## Setup

The 'Audit Directory Service Changes' logging policy must be configured for (Success).
Steps to implement the logging policy with Advanced Audit Configuration:

Computer Configuration >
Policies >
Windows Settings >
Security Settings >
Advanced Audit Policies Configuration >
Audit Policies >
DS Access >
Audit Directory Service Changes (Success)
```

So if you don't collect these Active Directory events or they are not relevant to your env, you can disable the rule. Otherwise it is needed to apply this audit policy in your AD environment.

**Comment by w0rk3r** [comment]
I'll close the issue for now, but if you have more questions, I'll be following this issue and will respond. Thanks!

**Comment by PaHuf** [comment]
Hello @w0rk3r,

thank you for replying. The Rules are indeed failing to run.
I am not able to find a solution to fix it. I searched via GET _mapping and also came to the conclusion that the field is indeed missing in the searched indices. I also checked the index template if the field is also missing and found it to be true as well.
The fields in the suggestion are found in the .ds-logs-system.security-* index pattern but without any trace about the actual one needed for the Rule to run.
Link to the Rule: https://www.elastic.co/guide/en/security/current/windows-service-installed-via-an-unusual-client.html
![Image](https://github.com/user-attachments/assets/c697d2af-4b16-4841-a4d1-e0fc9515af0b)

**Comment by w0rk3r** [comment]
Hey @PaHuf, sorry, I got the warning thing wrong, it is indeed an error. 

The explanation I gave above solves exactly what you're dealing with. This error is not one you need to worry about if you don't have the data. The only action here is to follow the required steps to generate the data needed. For example, to the rule you shared, here are the setup instructions: https://www.elastic.co/guide/en/security/current/windows-service-installed-via-an-unusual-client.html#_setup_814

They are available in the SIEM as well:
![Image](https://github.com/user-attachments/assets/a0a5fc57-eafd-4d89-a7e4-eac462d4f7fc)

**Comment by FlorianHeigl** [comment]
@w0rk3r thanks for the nice explanation, also helped me :-)

well, partially, the setup guide does not exist for all and the guesswork is inconclusive, i.e. for 
_"Remote Scheduled Task Creation via RPC"_ and _Temporarily Scheduled Task Creation_
(verification_expection): it's quite hard to find out which audit gpo setting correlates to this. it feels problematic, i would like to know which rules i can trust...

**Comment by w0rk3r** [comment]
@FlorianHeigl we are in the process of creating more detailed Setup guides for Windows Rules that require more specific configuration. In that case, I think there right audit policy is this one (but I didn't test yet, lmk if you do):

```
Computer Configuration >
Windows Settings >
Security Settings >
Advanced Audit Policy Configuration >
System Audit Policies >
Object Access >
Audit Other Object Access 
```

**Comment by FlorianHeigl** [comment]
I'll add it and report back.

If i may suggest, use a json or similar format for these paths.

Why: It's becoming obvious that there will be a need to collect them all.
Users will need them to checklist, you'll find people want you to enable
all you process, then next you'll find you need to track them to the
related integrations.
Why: And then It comes back to people like me who'll write tests that
inject alerts or others who need to fine investigation guides, and we all
SHOULD map it onto ISO/BSI requirements and actually open up management
discussions on their IT'S operational maturity.
At the end it's just a few 100 kinds of events and we need to get people to
handle them competently. If we can't pull that info out of the descriptions
and manually need to go through all rules, that time is spent for a
generation.

Flo

Jonhnathan ***@***.***> schrieb am Mo., 7. Juli 2025, 14:21:

**Comment by FlorianHeigl** [comment]
And NO I DON'T MEAN PUT IT AS STIG XML FILES.


Florian Heigl ***@***.***> schrieb am Mo., 7. Juli 2025, 14:36:
