### ISSUE TITLE
[New Rule] Lateral movement via Cobalt Strike’s SMB PsExec module

### ISSUE THREAD

**Issue by peasead** [elastic/detection-rules#439]
## Description
Cobalt Strike is an offensive security tool that has several loadable modules. One module leverages PsExec commands over the SMB protocol for lateral movement.

This rule will detect when Cobalt Strikes' SMB PsExec module is being used in a default configuration.

## Required Info

- **Eventing Sources:**
  - winlogbeat-*
  - logs-endpoint.events.*

- **Target Operating Systems:**
Windows

- **Platforms**
NA

- **Target ECS Version:** 1.6.0
- **New fields required in ECS for this?** NA
- **Related issues or PRs** NA

## Optional Info
- **References:**
  - https://redcanary.com/blog/how-one-hospital-thwarted-a-ryuk-ransomware-outbreak/

## Example Data
```
process.pe.original_file_name:RUNDLL32.EXE and process.parent.name:services.exe 
and not process.args:* and destination.port:445
```

**Comment by peasead** [comment]
Request feedback from @Samirbous prior me creating PRs.

**Comment by Samirbous** [comment]
@peasead this will be detected by this existing [rule ](https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_direct_outbound_smb_connection.toml), only normal process in Windows that connects directly (outbound) to SMB port (445) is "System" process and always has a pid equal to 0x4.

**Comment by peasead** [comment]
Thanks, @Samirbous 

I'll close this one in favor of https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_direct_outbound_smb_connection.toml.
