### ISSUE TITLE
[Rule Tuning] Authentication Failed Events

### ISSUE THREAD

**Issue by janniten** [elastic/detection-rules#44]
The detection rule Authentication Failed Events is not using an allowed value for event.outcome

## Description
Describe the bug
The detection rule Authentication Failed Events is not using an allowed value for event.outcome
<https://www.elastic.co/guide/en/ecs/current/ecs-event.html>

It is defined as
event.category : "authentication" and event.outcome: "failed"
and should be
event.category : "authentication" and event.outcome: "failure"

## Example Data

![image](https://user-images.githubusercontent.com/33020901/87029511-9089b380-c1e0-11ea-801f-e34116a4d62f.png)

**Comment by rw-access** [comment]
Hello @janniten, I can't find the "Authentication Failed Events" rule in this repository. Is this a custom rule that you have in your stack?

**Comment by janniten** [comment]
Hi Ross,
My apologies. Yes It was a (wrong) custom rule that I've created several days ago and I didn´t remember
Sorry!

**Comment by rw-access** [comment]
No worries! And if you do have more questions like these when debugging your own rules, please feel free to make issues here or post questions in the #detection-rules channel of [Elastic community slack](https://ela.st/slack) and we'll do our best to help.

**Comment by janniten** [comment]
Thank you Ross,
In the next days I'll be working with rules related to winlogbeat's security module events
