### ISSUE TITLE
[New Rule] Possible Bloodhound or Sharphound Activity

### ISSUE THREAD

**Issue by peasead** [elastic/detection-rules#442]
## Description
Bloodhound and Sharphound are tools for exploring Active Directory domain security. Bloodhound is an open source application used for analyzing the security of active directory domains.

This rule will detect when `regsrv32.exe` is used for SMB enumeration.

## Required Info

- **Eventing Sources:**
  - winlogbeat-*
  - logs-endpoint.events.*

- **Target Operating Systems:**
Windows

- **Platforms**
NA

- **Target ECS Version:** 1.6.0
- **New fields required in ECS for this?** NA
- **Related issues or PRs** NA

## Optional Info
- **References:**
  - https://redcanary.com/blog/how-one-hospital-thwarted-a-ryuk-ransomware-outbreak/

## Example Data
```
process.pe.original_file_name:REGSVR32.EXE and destination.port:445
```

**Comment by peasead** [comment]
Request feedback from @Samirbous prior me creating PRs.

**Comment by Samirbous** [comment]
there is a generic [rule](https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_direct_outbound_smb_connection.toml) for this that has same logic but excludes only normal process in Windows that perform direct SMB connections (which is System process and has always same process ID equal to 0x4), so anything else is worth review (e.g. regsvr32, rundll32 etc., usual FPs are scanners related processes)

**Comment by peasead** [comment]
Okay, I'll move onto the next step and see if it's a worthwhile rule.
```
process.pe.original_file_name:(REGSVR32.EXE or RUNDLL32.EXE) and destination.port:445```

**Comment by austinsonger** [comment]
```json
((winlog.channel:Microsoft\-Windows\-Sysmon\/Operational AND winlog.event_id:1) AND (process.executable:(*\\Bloodhound.exe* OR *\\SharpHound.exe*) OR process.args:(*\ \-CollectionMethod\ All\ * OR *.exe\ \-c\ All\ \-d\ * OR *Invoke\-Bloodhound* OR *Get\-BloodHoundData*) OR (process.args:*\ \-JsonFolder\ * AND process.args:*\ \-ZipFileName\ *) OR (process.args:*\ DCOnly\ * AND process.args:*\ \-\-NoSaveCache\ *)))
```

#### References

- https://github.com/BloodHoundAD/BloodHound
- https://github.com/BloodHoundAD/SharpHound

**Comment by peasead** [comment]
Thanks @austinsonger 

Quick note on the **References**, it looks like SharpHound is deprecated for [SharpHound3](https://github.com/BloodHoundAD/SharpHound3) 

That said, `winlog.channel` is only a Winlogbeat field and Sharphound lights up the Security integration of the Elastic Endpoint Agent.
![image](https://user-images.githubusercontent.com/7442091/103231582-bffeba80-48fd-11eb-9713-6284f38b5ac7.png)

So, I think maybe what we do is use some of your `process.args` along with `process.pe.original_file_name:BloodHound.exe`? These look to be in Lucene?

**Comment by peasead** [comment]
What about something like this? We can build more on this, but as a jumping off point
```
event.category:process and event.type:(process_start or start) and (process.name:SharpHound.exe or 
process.pe.original_file_name:SharpHound.exe) and process.args:("--CollectionMethod" or "-c")
```

**Comment by peasead** [comment]
Stashing some options for now:
**KQL**
```
event.category:process and event.type:(process_start or start) and
 (process.name:(SharpHound.exe or BloodHound.exe) or
 process.pe.original_file_name:(BloodHound.exe or SharpHound.exe)) or
 process.args:(invoke-bloodhound or invoke-azurehound)
```
**EQL** (I like this better because we can do case-insensitivty)
```
process where event.type in ("start", "process_started") and 
(process.name:("sharphound.exe", "bloodhound.exe") or 
process.pe.original_file_name:("sharphound.exe", "bloodhound.exe")) or 
process.args:("invoke-bloodhound", "invoke-azurehound")
```

**Comment by peasead** [comment]
Possible smarter ways to find this. H/T @bm11100 
`event.module:powershell`
```
powershell.file.script_block_text
)
	$DeflatedStream.Read($UncompressedFileBytes, 0, 833024) | Out-Null
	$Assembly = [Reflection.Assembly]::Load($UncompressedFileBytes)
	$BindingFlags = [Reflection.BindingFlags] "Public,Static"
	$a = @()
	$Assembly.GetType("Costura.AssemblyLoader", $false).GetMethod("Attach", $BindingFlags).Invoke($Null, @())
	$Assembly.GetType("SharpHound3.SharpHound").GetMethod("InvokeSharpHound").Invoke($Null, @(,$passed))
}

message
)
	$DeflatedStream.Read($UncompressedFileBytes, 0, 833024) | Out-Null
	$Assembly = [Reflection.Assembly]::Load($UncompressedFileBytes)
	$BindingFlags = [Reflection.BindingFlags] "Public,Static"
	$a = @()
	$Assembly.GetType("Costura.AssemblyLoader", $false).GetMethod("Attach", $BindingFlags).Invoke($Null, @())
	$Assembly.GetType("SharpHound3.SharpHound").GetMethod("InvokeSharpHound").Invoke($Null, @(,$passed))
}
```

**Comment by bm11100** [comment]
And the built in windows integration covers `Microsoft-Windows-PowerShell/Operational`. We could then add a `logs-windows*` index. Just depends if we would want to do leading and trailing wildcards, which would pretty much be our only option in the script blocks.

**Comment by austinsonger** [comment]
This one would expand coverage for Elastic.

MITRE

| Tactic    | Technique ID | Technique Name              | Sub-Technique Name | Elastic Current Coverage|
| --------- | ------------ | --------------------------- | ------------------ | --------------|
| Discovery | T1087.001    | Account Discovery           | Local Account      |:x:|
| Discovery | T1087.002    | Account Discovery           | Domain Account     |:heavy_check_mark: |
| Discovery | T1482        | Domain Trust Discovery      |                    |:heavy_check_mark:  |
| Discovery | T1069.001    | Permission Groups Discovery | Local Groups       | :x:|
| Discovery | T1069.002    | Permission Groups Discovery | Domain Groups      |:heavy_check_mark:  |

**Comment by peasead** [comment]
7/1 - update

Suggesting this be taken over by Analysis and assessed for viability or closed.
