### ISSUE TITLE
[Bug] Kibana commit needs to update NOTICE.txt

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#53]
**Describe the bug**
Pre-commit hook not working and NOTICE.txt not updated.
I think we need to run a few `yarn` commands. We could also add a toggle to suppress this behavior, so we can skip this, because yarn isn't always set up. 

Context: https://github.com/elastic/kibana/pull/71332#issuecomment-657095553 from @spong
> @rw-access @brokensound77 -- needed to run `node scripts/notice` from kibana root to regenerate the `NOTICE.txt`. I missed this as part of https://github.com/elastic/detection-rules/pull/32 as I was thinking it happened during the build, but looks like it needs to be done manually after updating any `notice.ts` (similar to `i18n` behavior). I'll defer to you for where this command fits in with your existing rules workflow, but would it be fine to add as part of the generation of this PR?

**To Reproduce**
See https://github.com/elastic/kibana/pull/71332/commits

**Expected behavior**
NOTICE.txt populated correctly

**Screenshots**
N/A

**Comment by brokensound77** [comment]
Can this be closed @rw-access?
