### ISSUE TITLE
[New Rule] Elastic Auditing

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#544]
## Description
Detect possible signals in Elastic auditing logs. 

So lately I created some rules detecting signals in Elastic auditing data.

![image](https://user-images.githubusercontent.com/6462991/99373112-52ed1380-28c1-11eb-9928-b6f3315e00ce.png)

Would there be any interest if I would create a PR to add the above rules to the detection repo? _((if I find the time)_

## Required Info

- **Eventing Sources:**

event.dataset : elasticsearch.audit

- **Platforms**

Elastic

**Comment by threat-punter** [comment]
Hi @willemdh. Can you please provide some additional information on the use case for your custom rules and what behavior they're alerting your team to? Is your suggestion to add your custom rules to this repo to help other security users?

**Comment by willemdh** [comment]
Hey @threat-punter 

Well, these rules enable us to find users trying to access data or functionalities they should not, they find users who are attempting to use builtin accounts, find excessive authentication failures. We had a lot of value from those rules. I have to admit that most of the things they find are misconfigurations and they do need some filtering (on source.ip for example). But still before I was running these rules, we had to manually search through the auditing dashboards for this kind of stuff and now we get an email after which we can close the alert or escalate to a ticket and investigate further.

If you are not interested, I can understand, as these are not useful for everyone (you need a license for example and you better have a dedicated monitoring cluster to index your audit logs too etc)

Grtz

Willem

**Comment by threat-punter** [comment]
Thanks for the explanation, @willemdh. If your team views this behavior as notable and something to be triaged and investigated, I think there is a good chance that other teams will find the rules useful too.

**Comment by threat-punter** [comment]
Would you like to share some of your queries in this issue for further discussion?

**Comment by willemdh** [comment]
I will, but give me some time, as I'm on the midle of all kinds of stuff currently. Tx

**Comment by threat-punter** [comment]
I'm going to close this issue due to inactivity. Please feel free to re-open it or create a new issue if you'd like to pick the conversation up again. 👍

**Comment by willemdh** [comment]
Ok, sry, in the middle of a datacenter migration..

**Comment by threat-punter** [comment]
Take your time. I'll be here 👍
