### ISSUE TITLE
[FR] The Reconnaissance MITRE Tactic should be recognize as a valid option

### ISSUE THREAD

**Issue by maxverro** [elastic/detection-rules#591]
**Describe the bug**
When creating a new rule with the CLI we are not able to use the `Reconnaissance` Tactic. The script validates the name and returns the following error : 
`Reconnaissance not in valid options: Collection, Command and Control, Credential Access, Defense Evasion, Discovery, Execution, Exfiltration, Impact, Initial Access, Lateral Movement, Persistence, Privilege Escalation`

**To Reproduce**
1. Create a new rule like `python -m detection_rules create-rule rules/vulnerability-scanner/burpcollaborator_in_url.toml`
2. Fill in the details until you get prompt for `add mitre tactic? [y/N]`
3. Input `y`
4. When promp for `mitre tactic name (required):` input `Reconnaissance`

**Expected behavior**
Reconnaissance should be allowed as a valid MITTRE Tactic. See MITTRE ATT&CK for detail https://attack.mitre.org/tactics/TA0043/

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version: 11.0.1

**Additional context**
Rules to detect unauthorized usage of vulnerability scanners such as Burp, Acunetix or tools like sqlmap are a good fit for the `Reconnaissance`tactic. We can then classify them under the Active Scanning technique (https://attack.mitre.org/techniques/T1595/)

**Comment by threat-punter** [comment]
@brokensound77 - Do you know if we have any plans to support adding the Reconnaissance tactic to a rule?

**Comment by brokensound77** [comment]
The repo is currently on [ATT&CK v7.2](https://github.com/elastic/detection-rules/blob/main/etc/attack-v7.2.json.gz) and recon was added in v8, ref: https://attack.mitre.org/versions/v7/. Once we refresh, which should be sometime soon, in coordination with Kibana repo, the schema will be updated to allow it.
