### ISSUE TITLE
A new inbox rule is created in Microsoft 365

### ISSUE THREAD

**Issue by garyjblackwell** [elastic/detection-rules#594]
## Description
Microsoft 365 A new inbox or forwarding rule is created. 
Create a detection when an operation is: New-InboxRule.  We will need the 
source IP, source location, and the name of the new rule.

## Required Info

- **Eventing Sources:**
Microsoft 365

- **Target Operating Systems:**
Exchange Online

- **Platforms**
Microsoft 365

- **Target ECS Version:** Latest
- It should not require a new field - it may be under Operation

## Optional Info
- References:https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-outlook-rules-forms-attack?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide

## Example Data
{
  "CreationTime": "2020-11-19T13:31:30",
  "Id": "a-dashed-ID-code",
  "Operation": "New-InboxRule",
  "OrganizationId": "an-org-ID",
  "RecordType": 1,
  "ResultStatus": "True",
  "UserKey": "a-User-Key",
  "UserType": 2,
  "Version": 1,
  "Workload": "Exchange",
  "ClientIP": "IPAddr:Port",
  "ObjectId": "NAM.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/anOrg.onmicrosoft.com/Users Name\\Rule Name",
  "UserId": "UserID@tucancompany.com",
  "AppId": "00000002-0000-0ff1-ce00-000000000000",
  "ClientAppId": "",
  "ExternalAccess": false,
  "OrganizationName": "theclient.onmicrosoft.com",
  "OriginatingServer": "Server (15.20.3589.021)",
  "Parameters": {
    "AlwaysDeleteOutlookRulesBlob": "False",
    "Force": "False",
    "MoveToFolder": "Miscellaneous",
    "Name": "RuleName",
    "SubjectContainsWords": "SubjectWords",
    "MarkAsRead": "True",
    "StopProcessingRules": "True"
  },
  "SessionId": "dashed-session-id"
}

**Comment by bm11100** [comment]
Hi @garyjblackwell! We currently have a list of Microsoft 365 rules targeting the 7.11 release [here](https://github.com/elastic/detection-rules/pulls?q=label%3A%22Platform%3A+Microsoft+365%22+). You can see the detection logic used in those rules, and if interested in contributing, you can follow our guide [here](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md).

I don't currently have an Exchange test mailbox set up, but would imagine the logic for your rule looking like below - 
```
event.dataset:o365.audit and event.provider:Exchange and event.category:web and event.action:"New-InboxRule" and event.outcome:success
```
Perhaps you could test that in your environment and get a sense of noise levels, and if it works well, use the guide above to contribute to the repo. I'm always happy to help with the rule logic and creation, just let me know!

**Comment by bm11100** [comment]
Hi @garyjblackwell, any update on this?

**Comment by garyjblackwell** [comment]
I'm sorry, I have not tried it yet.  I've been covered up with other tasks.  I should be able to try it next week.

**Comment by garyjblackwell** [comment]
I looked through the 7.11 rules and did not see this rule. https://attack.mitre.org/techniques/T1114/003/
I used your search, and it came back with two results.  I simplified the rule to event.action:"New-InboxRule".  I believe it will work well.  
Thanks

**Comment by bm11100** [comment]
@garyjblackwell, correct, this is not in the current list of rules as it is awaiting a PR. Are you planning on contributing a PR following our guide [here](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md) or would you like me to go ahead and put it in for you?

**Comment by garyjblackwell** [comment]
I contributed and received the points.  
Thanks

**Comment by bm11100** [comment]
I don't see a PR from you, so I'll create one for the next release.  Thanks
