### ISSUE TITLE
[New Rule] Suspicious Service ImagePath Created

### ISSUE THREAD

**Issue by Samirbous** [elastic/detection-rules#602]
## Description

Identifies known malicious or suspicious service registry ImagePath values employed while elevating privilege via named pipe impersonation or via execution HKTL that leverage windows services for execution.

![image](https://user-images.githubusercontent.com/64742097/99939074-8d472c80-2d69-11eb-94a0-fd447efcdd83.png)

## Required Info

- **Eventing Sources:**

- **Target Operating Systems:**

- **Platforms**

- **Target ECS Version:** x.x.x
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**

**Comment by eklike100** [comment]
@Samirbous If you can help please tell attack method to generate such logs to test this rule. I tried `sc.exe create MyService binPath=%COMSPEC% powershell.exe -nop -w hidden -e (base64 reveerse shell payload)` attack was successful but couldn't get such  event.
