### ISSUE TITLE
[FR] preserver rule_id in kibana_upload

### ISSUE THREAD

**Issue by SHolzhauer** [elastic/detection-rules#612]
This FR is a result of discussion with @rw-access on Slack

**Is your feature request related to a problem? Please describe.**
What purpose does the rule_id  property serve in the toml files, specifically for the kibana_upload command?
It was my expectation this would be the id in kibana but looking at the code that appears to be generated on "runtime"

Using the kibana-upload command should have the option to use the `rule_id` from the toml file.  
This will also make #362 easier to implement.

**Describe the solution you'd like**
Add two flags to the `kibana_upload` command:

| flag | usage |
|---|---|
| `--preserve-id` | |
| `--force` | |

If the `--preserve-id` flag is used without the force option, it is verified prior to uploading a rule if the id already exists, if so;
The rule existing in Kibana it's name will be returned and the user is promted if it should be overridden.

The `--force` option skips the above verify step.

**Describe alternatives you've considered**
-

**Additional context**
By allowing the kibana_upload command to "override" existing rules in the detection engine the code can be "reused" in the flow for #362 instead of having to add new code to do nearly the same. This makes updating code down the line easier.

**Comment by operatorequals** [comment]
Yes. After that we will be ready for a Terraform resource using `detection_rules` to provision live rules!

**Comment by operatorequals** [comment]
Do we have any update on this?
There is a very strong use case in my org for this! I can further explain the need and test the feature if it starts working.

As 1 image is worth 1000 words, here is the Github Action we use to Push Rules in the SIEM:
![image](https://user-images.githubusercontent.com/6146328/152518787-a434fc83-0e4c-4940-9c03-42fe774ab96a.png)

It only pushes *new* rules with this configuration, but it would be very useful to "iron-out" all deployed rules with their new versions.

**Comment by operatorequals** [comment]
I created a Terraform Provider for Elastic Rules and Exceptions
https://github.com/operatorequals/terraform-provider-elastic-siem#why

**Comment by pandvan** [comment]
This is very needed for the usecase of my org.
We'd like to store rules in a private git repo and then deploy/upload them on several Kibana instances.
Without a way to update a rule, using the rule_id as index, we cannot adopt detection_rule tool in our pipeline.

As an intermediate step we tried to generate a _ndjson_ file with `export-rules` command and then manually import them using Kibana (it allows overwrites). But in this way custom rule actions are kept but exceptions are removed.

So, still searching to build a workflow for enable a git-ops based approach to manage Elastic Security detection rules.

**Comment by operatorequals** [comment]
In my organization we managed to do GitOps with TOML rules and Exceptions using the Terraform Provider mentioned above (https://github.com/elastic/detection-rules/issues/612#issuecomment-1084644745).

For this exact purpose I created a template repository (with Github Workflows and everything set), to manage Rules, Exceptions and Lists with per-PR `terraform plan` and `terraform apply` on merge (https://github.com/operatorequals/elastic-siem-terraform-template). It integrates with this repo us well using `git submodule`

We also created a 10' presentation on exactly that for BSides Athens (a small Security Conference). Find it here - https://www.youtube.com/watch?v=5ssqlLyYv8E

**Comment by Mikaayenson** [comment]
@SHolzhauer Do you recall if you ran into issues with preserving the rule_id for custom rules or did you try to preserve prebuilt rule's rule_id?

This issue may be good to close based on your description since rule_id is not generated at runtime today.

**Comment by eric-forte-elastic** [comment]
With the DaC feature now merged into main via https://github.com/elastic/detection-rules/pull/3889, and the rule_id no longer being generated at run time, this should no longer be an issue. For similar behavior to your `--force` suggestion, you can use the `--overwrite` flag to overwrite existing rules. Without this flag, existing rules with the same rule_id will be preserved in Kibana and not updated.

**Comment by SHolzhauer** [comment]
What we did was to use the api and build a simple wrapper job in our pipeline. I _johnny rigged_ some of the code into using the TOML files and preserving the ids which the API did support.

The DaC feature should take care of all of this (as that was the entire goal) but haven't tried it yet.
