### ISSUE TITLE
Rename googlecloud to gcp for event.dataset

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/detection-rules#627]
With renaming Filebeat module `googlecloud` to `gcp` in https://github.com/elastic/beats/pull/22214, detection rules that use `event.dataset: googlecloud.*` need to be renamed as well. For example: https://github.com/elastic/detection-rules/search?q=googlecloud

cc @andrewkroh

**Comment by rw-access** [comment]
Thanks @kaiyan-sheng. Was this a change between releases or within a single release? If it was between releases, maybe we should do an `or` of both to reduce breaking changes

**Comment by bm11100** [comment]
Adjusting rule syntax to account for gcp in this PR https://github.com/elastic/detection-rules/pull/729

**Comment by bm11100** [comment]
Closing, syntax changes made in https://github.com/elastic/detection-rules/pull/729
