### ISSUE TITLE
How do I import the rules into Kibana?

### ISSUE THREAD

**Issue by avi8892** [elastic/detection-rules#656]
Hi guys, I'm trying to import the rules into Kibana but I can't. Can anyone help me with that?

**Comment by jamesspi** [comment]
Hey @avi8892 - How are you trying to import the rules? Via the CLI?

Kibana requires a `.ndjson` file for UI based uploads. It you are trying to use detections from this repository, you will need to use the included CLI tool to import them via CLI, or covert them from `toml` to `ndjson`.

**Comment by avi8892** [comment]
> Hey @avi8892 - How are you trying to import the rules? Via the CLI?
> 
> Kibana requires a `.ndjson` file for UI based uploads. It you are trying to use detections from this repository, you will need to use the included CLI tool to import them via CLI, or covert them from `toml` to `ndjson`.

Thanks man!, can you please send me the command that shows how to convert the rules from tmol to ndjson?

**Comment by jamesspi** [comment]
@avi8892 Here's the full CLI documentation - https://github.com/elastic/detection-rules/blob/main/CLI.md

**Comment by avi8892** [comment]
> @avi8892 Here's the full CLI documentation - https://github.com/elastic/detection-rules/blob/main/CLI.md

Can you help me with it? no matter what I do it always asking for kibana url.

![image](https://user-images.githubusercontent.com/31028818/100840071-03d8de00-347e-11eb-9237-ea82d073365a.png)

**Comment by brokensound77** [comment]
Hello @avi8892, there was a bug for a bit but has since been resolved. Ensure you are up to date with main and hopefully that resolves it

**Comment by V1D1AN** [comment]
Hi everybody,

I have the same error :( , like @avi8892

**Comment by avi8892** [comment]
@V1D1AN it is not fixed even I did what was recommended.

**Comment by brokensound77** [comment]
So it actually is likely not a bug at all but an issue with how you are calling the command. It may be a bit subtle, but if you see under https://github.com/elastic/detection-rules/blob/main/CLI.md#commands-using-elasticsearch-and-kibana-clients, it shows that for commands under the client groups (`kibana` and `es`), you need to pass client args immediately after the respective group, such as:

`python -m detection-rules kibana -ku <username> -kp <password> upload-rule <...>`

So just shift all of your client args to before `upload-rule` and you should be good to go

**Comment by V1D1AN** [comment]
Thanks for your help.
It works with the command:

```
python3 -m detection_rules kibana --kibana-url http://127.0.0.1:5601/kibana -ku elastic -kp elastic upload-rule
```

**Comment by avi8892** [comment]
> Thanks for your help.
> It works with the command:
> 
> ```
> python3 -m detection_rules kibana --kibana-url http://127.0.0.1:5601/kibana -ku elastic -kp elastic upload-rule
> ```

Why is it trying to access this URL? 

![image](https://user-images.githubusercontent.com/31028818/102211508-600b1b80-3edc-11eb-85c8-473507460348.png)

**Comment by V1D1AN** [comment]
I have the same error with ELK 7.10.1 , not the version 7.9.2

**Comment by avi8892** [comment]
> I have the same error with ELK 7.10.1 , not the version 7.9.2

I'm on 7.10 :(

**Comment by V1D1AN** [comment]
![Error-elastic](https://user-images.githubusercontent.com/18678787/102214569-c5f5a400-3ed8-11eb-9cc9-c4a4986b010f.PNG)

**Comment by avi8892** [comment]
@V1D1AN Sad, I have already installed winlogbeat and everything :/

**Comment by V1D1AN** [comment]
Someone has already succeeded in importing rules into kibana ? you need another license than the "BASIC" license.
