### ISSUE TITLE
Tag every release please

### ISSUE THREAD

**Issue by ThorbenJ** [elastic/detection-rules#658]
Hi,

This repo tags just 7.9.0, 7.9.1 and 7.10.0, but not 7.9.2, 7.9.3, etc.

What could be done to ensure that the commit used for a particular release is always tagged? as not all are.

Why? Want to be able to match a release of the RTA TTPS with a target ES installation version.

Thanks,
Thorben

**Comment by rw-access** [comment]
Hi @ThorbenJ, we do tag every release from this repository. But I think I know the disconnect you're referring to.

For this repository in particular, we don't make a release for each _stack release_. So if there is a 7.10.1 stack release, there will most likely not be a 7.10.1 update to this repository, unless we're addressing a bug.

That said, I think you might just need to update the logic on your end to use the latest `{major}.{minor}` version `<=` to what you have. So if you're on stack 7.9.2 or 7.9.3, then you should use the best matching release, which is **7.9.1**.

**Comment by ThorbenJ** [comment]
Hi @rw-access, I had hope to be able to just blindly download the zip that GH generates for each tag, without the added complication of inspecting what tags are available and then selecting one.
You can see my initial version of the script here: https://github.com/ElasticSA/ec_spout/blob/master/rta_ttp.py
The goal is for Spout (https://wiki.elastic.co/display/PRES/EC+Spout) to be able to generate events that will trigger detection rules in demo sessions using the RTA TTP scripts.

**Comment by ThorbenJ** [comment]
Given your feedback, I think I'll just force the last number to 0; so 7.9.3 => 7.9.0. Selecting the nearest match for any version number is not a rabbit hole I'd like to go down.
Thanks you for the clarification.
