### ISSUE TITLE
[Rule Tuning] Logic bug for iptables disable rule

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#7]
## Description
Noticed a bug with the iptables rule after merging #5.

The existing `and`/`or` logic didn't properly account for precedence, and parts of the query were missing parentheses.
https://github.com/elastic/detection-rules/blob/46a400857026c1077eefe7120195a983c7b96136/rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml#L24

I believe the recommended change should be this
```python
event.category:process and event.action:(executed or process_started) and (
  (process.name:service and process.args:stop) or
  (process.name:chkconfig and process.args:off) or
  (process.name:systemctl and process.args:(disable or stop or kill))
) and process.args:(ip6tables or iptables or firewalld)
```

**Comment by phra** [comment]
ops, nice catch! i assumed that the AND operator was having precedence over the OR but I was probably wrong. (not a blue teamer here :smiley: )

> I believe the recommended change should be this

yes, i agree to semantically disambiguate the expression via parenthesis.

**Comment by rw-access** [comment]
oh, it's not your fault at all &mdash; this bug was there before your contribution. probably since day 1 of this rule.
but your contribution made me scrutinize the code a little closer and I noticed this

**Comment by phra** [comment]
oh.. nice one! happy to have contributed. :smile:

**Comment by rw-access** [comment]
@threat-punter I assigned you since you wrote the original version of this. Can you double check that the logic checks out?

**Comment by threat-punter** [comment]
I think the updated query looks great. Thanks @rw-access. I need to check something with regards to `event.category` before updating the rule. I'll pick this up again soon.

**Comment by rw-access** [comment]
Thanks @threat-punter. We can also skip the category field for now, and just focus on the logic. We can always come back to the ECS categorization later.

**Comment by threat-punter** [comment]
Yeah, I'll go with that option 👍

<img width="2240" alt="image" src="https://user-images.githubusercontent.com/56409778/86379476-21dcb100-bc48-11ea-9bb2-42791fddcb03.png">
