### ISSUE TITLE
[Rule Tuning] Enumeration of Administrator Accounts

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#709]
Rule `871ea072-1b71-4def-b016-6278b505138d` `Enumeration of Administrator Accounts` is failing in both the API search and detection engine with the following error

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "line 6:27: no viable alternative at input '(((process.name : \"net.exe\" or process.pe.original_file_name == \"net.exe\") or\\n    ((process.name : \"net1.exe\" or process.pe.original_file_name == \"net1.exe\") and\\n        not process.parent.name : \"net.exe\")) and\\n   process.args : (\"group\",'"
      }
    ],
    "type" : "parsing_exception",
    "reason" : "line 6:27: no viable alternative at input '(((process.name : \"net.exe\" or process.pe.original_file_name == \"net.exe\") or\\n    ((process.name : \"net1.exe\" or process.pe.original_file_name == \"net1.exe\") and\\n        not process.parent.name : \"net.exe\")) and\\n   process.args : (\"group\",'",
    "caused_by" : {
      "type" : "no_viable_alt_exception",
      "reason" : null
    }
  },
  "status" : 400
}
```

I did not find any obvious issues with the query so we need to determine if it is a bug in EQL or the rule

![image](https://user-images.githubusercontent.com/16747370/101871411-faabd900-3b2f-11eb-8795-4d8de6b50645.png)
![image](https://user-images.githubusercontent.com/16747370/101871451-0c8d7c00-3b30-11eb-8a55-b34ccb629761.png)

REF: https://github.com/elastic/kibana/pull/85506#discussion_r540722468

**Comment by rw-access** [comment]
I believe this was an intermittent issue because of the elasticsearch version that was used when tested. I think it's all sorted out. @spong can you confirm?

**Comment by spong** [comment]
> I believe this was an intermittent issue because of the elasticsearch version that was used when tested. I think it's all sorted out. @spong can you confirm?

[Commented](https://github.com/elastic/kibana/pull/85506#discussion_r541031894) over on the PR as well, but the es snapshot on the test cluster is from ~month ago (`2020-11-12`), so if this syntax was just recently supported then that's the mis-match. Will see about getting that upgraded 👍
