### ISSUE TITLE
[New Rule] Azure High Risk Signin

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#731]
## Description
Detect risky signins in Azure signin logs

![image](https://user-images.githubusercontent.com/6462991/102360630-8d29fd80-3fb2-11eb-802b-bd75f5faf972.png)

- **Eventing Sources:**
filebeat-*
event.dataset: azure.signin

- **Platforms**
Azure

There are also medium and low risky signins, so it might be better to make it a normal query and use an override to set severity depending on the value of `azure.signinlogs.properties.risk_level_during_signin`. I tried that however and I seem unable to use any valid value (medium / low) for `azure.signinlogs.properties.risk_level_during_signin` in the source value for the severity override?

![image](https://user-images.githubusercontent.com/6462991/102364543-dd0ac380-3fb6-11eb-8242-8f9158530aee.png)

This is an easy rule with a high value on detection imho, as it uses MS's ML and intelligence? Thoughts?

**Comment by willemdh** [comment]
Hey @bm11100,

We defintely have several low and medium risky signins. For example:

![image](https://user-images.githubusercontent.com/6462991/102470833-bf8c3700-4054-11eb-8f61-d348da3ff60e.png)

The field in Source field is `azure.signinlogs.properties.risk_level_during_signin`

I tried again and I can confirm I cannot select or enter 'low' or 'medium' in the Source Value field.

Is it possible that the override functionality only check for recent values, for example last hour / last 5 minutes?

Maybe if a 'risky' event happened recently, I can configure this.. Not sure..

Grtz

Willem

**Comment by bm11100** [comment]
Thanks @willemdh. I tested in a 7.9.1 cluster and I'm not able to repeat your error. The only values I have for that field are `none` since I don't have the ML enabled but it is populating correctly. 
![image](https://user-images.githubusercontent.com/56412096/102495860-a7acb700-4044-11eb-93b0-1a2d6ccf4746.png)


Do you know if you happened to paste the `azure.signinlogs.properties.risk_level_during_signin` value in with an empty space at the end? If I do that, I get a similar error as you see, since that field isn't actually a valid field. Could be hard to pick up on with a simple hover over.
![image](https://user-images.githubusercontent.com/56412096/102496203-1c7ff100-4045-11eb-9c86-2469d54e0fb0.png)

**Comment by willemdh** [comment]
Thanks for testing @bm11100 

Pasted the field and I was able to choose it in Source field, so I'm quite sure the source field was correct and had no spaces. But I might have made an error and maybe copied the original threshold query `event.dataset : "azure.signinlogs" AND azure.signinlogs.properties.risk_level_during_signin : "high"`

The result is of course there are no low or medium values to be found.

Thought it over and came up with this now, as `azure.signinlogs.properties.risk_level_during_signin` has `none` as value when there is no rsik detected.

![image](https://user-images.githubusercontent.com/6462991/102498649-88308100-407a-11eb-9951-5c1a48f8e63c.png)

So it seems to work, but I need a risky user signin to be sure... Could test myself with a login over VPN, but I'll probabaly have no time for that anymore as after tomorrow I'm on a 2 week holiday. I'll keep you posted once I have more info.

**Comment by bm11100** [comment]
Sweet, glad it works! We probably don't want to alert when there is a sign-in with no risk detected though. I think defaulting to high and overriding with medium/low is the way to go (pending how noisy medium/low risk sign-ins may be).  

Speaking with a colleague, I believe risk score override only supports a single value exact match against number fields, so pretty limited in its current state. I went ahead and put in an enhancement request [here](https://github.com/elastic/kibana/issues/86306) to have the ability to specify multiple risk scores for overrides within a single detection rule.

**Comment by willemdh** [comment]
Sweet indeed. 

Fyi, some time ago I also created https://github.com/elastic/beats/issues/22413 

Just so you know there is also an issue when trying to do an override on a keyword array. (We need this as event.type has multiple values..)

Thanks!

**Comment by bm11100** [comment]
Looks like this PR adds support for arrays in event fields for severity/risk overrides, landing in the 7.11 release https://github.com/elastic/kibana/pull/84643

**Comment by willemdh** [comment]
@bm11100 I'm not sure anymore if overriding the severity is the best option. The issue with the overrides is that it is currently not possible to define an action, based on the severity. For example we want an email to be sent only for high severity events. With the current override implementations, this is not possible. This does not only apply to this rule but also to other rules with overrides. It should be possible to define an action based on a conditional..

**Comment by bm11100** [comment]
@willemdh I updated the [enhancement request](https://github.com/elastic/kibana/issues/86306) to include defining an action as well. I think our best bet moving forward for now will be to create individual rules, for high risk, and potentially another for medium.  Looking back at your previous screenshot, it seems like when a high/medium risk sign on is detected, there is multiple events. In your data, would including `event.outcome:(Success or success)` get rid of some of the noise?

**Comment by bm11100** [comment]
@willemdh please review initial PR [here](https://github.com/elastic/detection-rules/pull/790).

**Comment by willemdh** [comment]
@bm11100 On my phone atm, I was having issues with event.outcome actually, please have a look at https://discuss.elastic.co/t/office365-signin-logs-event-outcome-seems-incorrect-sometimes/258832 it seems like the value is sometimes incorrect..

**Comment by bm11100** [comment]
Interesting, let me see what I can find out. 7.10.1 seems to be working for me.

![image](https://user-images.githubusercontent.com/56412096/103569584-91e91f80-4e95-11eb-8e4a-328d8e8b7f1a.png)

**Comment by willemdh** [comment]
Thanks for taking a look. This was kind of important, as we made a wrong conclusion and lost time. As you can see in the Azure screenshot, some signins were succesful, while Kibana shows failure for all. We are running 7.9.2.
