### ISSUE TITLE
[Question] How to write rules with multiple queries

### ISSUE THREAD

**Issue by Loginsoft-Research** [elastic/detection-rules#77]
Hi Elastic team,
What's the best way to rules with multiple queries?
Example:
**KQL query**:  `log.file.path : "/var/log/testing/testing.log" and message : "keyword1" or message : "keyword2" or message : "keyword3 or message : "keyword4" `
Is there any limitation on query length and what is the recommended way to write rules with multiple queries?

**Comment by rw-access** [comment]
hi @Loginsoft-Research.

I would recommend [reading up on KQL](https://www.elastic.co/guide/en/kibana/current/kuery-query.html) to familiarize with the syntax and capabilities of KQL. In particular, when you're searching multiple values for a single field, you can do this: `message:("keyword1" or "keyword2" or "keyword3" or "keyword4")`.

Any limitations on query length will be purely based on the generated query DSL and enforced by Elasticsearch. It's pretty large so if you do run into it, it's likely a sign that a single rule should be broken apart into multiple.
