### ISSUE TITLE
[FR] Support Self-signed Certificates via CLI

### ISSUE THREAD

**Issue by nicpenning** [elastic/detection-rules#772]
**Is your feature request related to a problem? Please describe.**
It appears that I cannot use the CLI tool due to self signed certificates.

**Describe the solution you'd like**
It would be great to have an option to trust the SSL connection.

I am seeing this error: 
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852))

Is there a way to bypass the certificate validation?

**Comment by Lexinga** [comment]
> **Is your feature request related to a problem? Please describe.** It appears that I cannot use the CLI tool due to self signed certificates.
> 
> **Describe the solution you'd like** It would be great to have an option to trust the SSL connection.
> 
> I am seeing this error: elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852))
> 
> Is there a way to bypass the certificate validation?



> **Is your feature request related to a problem? Please describe.** It appears that I cannot use the CLI tool due to self signed certificates.
> 
> **Describe the solution you'd like** It would be great to have an option to trust the SSL connection.
> 
> I am seeing this error: elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852))
> 
> Is there a way to bypass the certificate validation?



> **Is your feature request related to a problem? Please describe.** It appears that I cannot use the CLI tool due to self signed certificates.
> 
> **Describe the solution you'd like** It would be great to have an option to trust the SSL connection.
> 
> I am seeing this error: elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852))
> 
> Is there a way to bypass the certificate validation?

I still get this `Max retries exceeded with url: /internal/security/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)`  even with `--ignore-ssl-errors`

**Comment by nicpenning** [comment]
Try --no-verify. Not sure what command is needed but looking at the code, that may work.

**Comment by frederikb96** [comment]
Just for reference for others stumbling across this.

The issue is most likely because you tried to put the `--ignore-ssl-errors true` at the end of the command and not directly after `kibana`:
```bash
# WRONG
python -m detection_rules kibana import-rules  --ignore-ssl-errors true ...

# CORRECT
python -m detection_rules kibana --ignore-ssl-errors true import-rules ...
```
