### ISSUE TITLE
[Rule Tuning] Threats which define only a tactic must contain an empty array

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#812]
Related to https://github.com/elastic/kibana/issues/87546

In Kibana 7.11, ATT&CK techniques were made optional, but the field is still required to be set as an empty array. In 7.12, the schema in Kibana will be updated to make the field optional, no longer requiring an empty array. Once this is done, we can strip the empty array from the rules:

**Comment by rw-access** [comment]
@brokensound77 is this going to be done at build time or in TOML? i would prefer at build time, if possible

**Comment by brokensound77** [comment]
@rw-access that is a great idea! I just did all this work in this [branch](https://github.com/elastic/detection-rules/compare/main...brokensound77:rule-tuning/add-empty-technique?expand=1), but will update accordingly, in a much simpler fashion.

Thanks 🎈

**Comment by brokensound77** [comment]
closed by #828
