### ISSUE TITLE
[New Rule] Executable File Creation with Multiple Extensions

### ISSUE THREAD

**Issue by bm11100** [elastic/detection-rules#824]
## Description
Masquerading can allow an adversary to evade defenses and better blend in with the environment. One way it occurs is when the name or location of a file is manipulated as a means of tricking a user into executing what they think is a benign file type but is actually executable code.

## Required Info

- **Eventing Sources:**
`winlogbeat-*`, `logs-endpoint.events.*`

- **Platforms**
`windows`

## Optional Info
- **References:**

## Syntax
```
file where event.type == "creation" and 
  file.name:(
        "*.vbs.exe", 
	"*.vbe.exe", 
	"*.bat.exe",
	"*.js.exe",
	"*.cmd.exe",
	"*.wsh.exe",
	"*.ps1.exe",
	"*.pdf.exe",
	"*.docx.exe",
	"*.doc.exe",
	"*.xlsx.exe",
	"*.xls.exe",
	"*.pptx.exe",
	"*.ppt.exe",
	"*.txt.exe",
	"*.rtf.exe",
	"*.gif.exe",
	"*.jpg.exe",
	"*.png.exe",
	"*.bmp.exe",
	"*.hta.exe",
	"*.txt.exe",
	"*.img.exe"
	)
```

## Example Data

![image](https://user-images.githubusercontent.com/56412096/103930204-601dc600-50ec-11eb-85c9-285e41613622.png)

**Comment by Samirbous** [comment]
you can also add macOS cases ``` *.pdf.app, *.doc.app, *.docx.app, *.xls.app, *.xlsx.app  *.samestuff.pkg *.samestuff.dmg ```
