### ISSUE TITLE
[New Rule] Hijack Azure AD Applications

### ISSUE THREAD

**Issue by bm11100** [elastic/detection-rules#889]
## Description
Hardening Strategies for Microsoft 365 to Defend Against UNC2452 - thanks to @dstepanic17 for sharing the whitepaper.

The Azure AD Audit log and the Unified Audit Log record when credentials are added to both service principals and App Registrations. In most organizations, credentials will be added to service principals and App Registrations infrequently. Organizations should create rules to alert on the log events that get generated by these activities and audit them to ensure they are legitimate. 

## Required Info

- **Eventing Sources:**

- **Target Operating Systems:**

- **Platforms**

- **Target ECS Version:** x.x.x
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**
https://www.fireeye.com/content/dam/collateral/en/wp-m-unc2452.pdf

## Example Data
`“Operation”: “Add service principal credentials.”`

**Comment by austinsonger** [comment]
Wouldn't this include more `Operation` than just "Add service principal credentials."


```
event.dataset: azure.auditlogs and azure.auditlogs.operation_name : 
       (
       "Add service principal credentials.", 
       "Add owner to service principal",
       "Update application - Certificates and secrets management" 
       ) and 
       event.outcome: (success or Success)
```

**Comment by austinsonger** [comment]
Just a Update.

```
event.dataset: azure.auditlogs and azure.auditlogs.operation_name: ("Add service principal credentials." or 
"Update application – Certificates" or "secrets management") and event.outcome: (success or Success)
```

**Comment by bm11100** [comment]
We do have a rule (Azure Application Credential Modification) that currently looks for `Update application - Certificates and secrets management`

**Comment by austinsonger** [comment]
So this would be the query


```
event.dataset: azure.auditlogs and azure.auditlogs.operation_name : "Add service principal credentials." and 
event.outcome: (success or Success)
```

**Comment by bm11100** [comment]
> So this would be the query
> 
> ```
> event.dataset: azure.auditlogs and azure.auditlogs.operation_name : "Add service principal credentials." and 
> event.outcome: (success or Success)
> ```

I'm thinking that's probably what we will have to go with. Unfortunately, Azure doesn't have the most robust logging.
