### ISSUE TITLE
[Bug] Validation error: 'metadata' is a required property

### ISSUE THREAD

**Issue by ArdRay** [elastic/detection-rules#90]
**Describe the bug**
Rule creation fails with the following error `jsonschema.exceptions.ValidationError: 'metadata' is a required property`.  Using `--required-only`, it does not mandate metadata as a required field.

**To Reproduce**
1. Run ` python3 -m detection_rules create-rule test`.
2. Fill all required fields. 
3. [errorlog.txt](https://github.com/elastic/detection-rules/files/4971531/errorlog.txt)

**Expected behavior**
Expected behavior is the creation of the .toml rule-file, based on the cli input.

**Desktop (please complete the following information):**
 - OS: Testing on MacOS and alpine linux
 - Version: Python 3.8.5

**Comment by brokensound77** [comment]
Hello @ArdRay 👋,

Thanks for the report. It looks like a bug was introduced in a recent commit but will be resolved once #83 merges.

As a temporary workaround, you could comment out this line in the mean time:
https://github.com/elastic/detection-rules/blob/d15da0ada1e5037572c18c99fca62a1266e71bda/detection_rules/rule.py#L283
