### ISSUE TITLE
[FR] Jumpcloud integration + Detection Rules

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#925]
**Describe the solution you'd like**
Add Jumpcloud integration like you did for Okta

**Additional context**
- [Jumpcloud API](https://docs.jumpcloud.com/2.0/api-overview)

**Comment by brokensound77** [comment]
👋 hey @austinsonger, this would probably be better served in the integrations [repo](https://github.com/elastic/integrations). [Here](https://github.com/elastic/integrations/pull/632) is an example PR in the repo requesting a new integration.

Hope this helps
