### ISSUE TITLE
[Rule Tuning] Microsoft 365 Rules with identical queries?

### ISSUE THREAD

**Issue by willemdh** [elastic/detection-rules#930]
Hello,

Today, I was browsing through some of the Microsoft 365 detection rules, and I noticed the following two rules have an identical query?

https://github.com/elastic/detection-rules/blob/main/rules/microsoft-365/credential_access_microsoft_365_brute_force_user_account_attempt.toml

https://github.com/elastic/detection-rules/blob/main/rules/microsoft-365/credential_access_microsoft_365_potential_password_spraying_attack.toml

Query:

`event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication and event.action:UserLoginFailed and event.outcome:failure`

Not sure if it's a bug, or maybe these rules are still being tuned?

Willem

**Comment by bm11100** [comment]
Hey @willemdh! You are correct that the base KQL query is the same, however, they are threshold rules that have different threshold fields.  If you look at the very bottom of the rules, one is looking for Potential Brute Force Attempts (failures by `user.id` greater than 10), while the other is looking for Potential Password Spraying Attempts (failures by `source.ip` greater than 25). 

```
[rule.threshold]
field = "user.id"
value = 10
```
```
[rule.threshold]
field = "source.ip"
value = 25
```
The rule names (and descriptions) are slightly different to reflect this `Attempts to Brute Force a Microsoft 365 User Account` and `Potential Password Spraying of Microsoft 365 User Accounts` but good eye!

**Comment by willemdh** [comment]
Thanks for clarifying, I should have taken a closer look..
