### ISSUE TITLE
Update License to Elastic v2

### ISSUE THREAD

**Issue by rw-access** [elastic/detection-rules#940]
I think we should update the license to Elastic v2. We might also want to change the license field of the rules to Elastic License v2. There might be some implications to these changes, so we should double check with other teams if the change is necessary and what should happen.

Here's where the Elasticsearch repo changed it https://github.com/elastic/elasticsearch/commit/a92a647b9f17d1bddf5c707490a19482c273eda3

This includes
* Markdown documentation
* LICENSE.txt
* All python files
* License validation unit tests

**Comment by brokensound77** [comment]
resolved by #944
