### ISSUE TITLE
[New Rule] Enumeration spawned from WmiPrvSe saved to a file

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#943]
## Description
related to https://github.com/elastic/kibana/pull/91082#discussion_r574446942

There is an existing rule (`770e0c4d-b998-41e5-a62e-c7901fd7f470`) focusing on the execution of certain enumeration commands launched from `WmiPrvSe.exe`. This new rule should focus on attempts to capture such information to a file, without explicitly defining a list of the sub commands.

Something roughly similar to

```sql
sequence with maxspan=2m
[process where event.type in ("start", "process_started") and
  process.name : "cmd.exe" and 
  process.args : ("/c", "-c") and process.args : ">" and process.args : "*.*"] by process.parent.entity_id
[process where event.type in ("start", "process_started") and
  process.name : "wmiprvse.exe"] by process.entity_id
```

## Required Info

- **Eventing Sources:**
`winlogbeat-*`, `logs-windows.*`, `logs-endpoint.events.*`
- **Target Operating Systems:**
windows

cc: @bm11100 @rw-access

**Comment by rw-access** [comment]
I think you can do this in a single event.
Also if you do something like `sequence [high volume] [high volume]` it will likely time out.
