### ISSUE TITLE
[FR] Save the stack version that a given rule is released

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#958]
Save the stack version (such as `7.13`) that a rule was introduced in. This can be added to the `version.lock` file and should be included in generated artifacts and enriched rule indexes, where it makes sense.

cc: @paulewing

**Comment by rw-access** [comment]
Thanks @brokensound77.

I think under `[internal]` we can track all of these similar things:
* minimum _compatible_ stack (in its current state)
* minimum _compatible_ ECS (already done)
* first _introduced_ stack

comparing the first and third options means we can easily look at a rule and tell if we've ever opted in to new stack/ecs features or fields.
