### ISSUE TITLE
[New Rule] O365 Exchange Malicious E-Mail Inbox Rule Detected

### ISSUE THREAD

**Issue by austinsonger** [elastic/detection-rules#962]
## Description

This rule will identify for some suspicious behaviors when the attackers create inbox rules to delete emails that contain certain keywords. This behavior often occured after initial compromise victim.

## Required Info

**Eventing Sources:**
Microsoft 365

**Target Operating Systems:**
Exchange Online

**Platforms**
Microsoft 365

### Query

```
event.dataset:o365.audit and event.provider:Exchange and event.category:web and event.action:"New-InboxRule"
```

### Additional
I know the keywords would be the following, but I don't know the way I would add it to the query above.

Parameters.keyword:`(*Deleted\ Items* OR *Junk\ Email*)) `

event.message:`(*helpdesk* OR *security\ alert* OR *suspicious* OR *fake* OR *malicious* OR *phishing* OR *spam* OR *do\ not\ click* OR *do\ not\ open* OR *hijacked* OR *Fatal* OR *payment\ remittance* OR *electronic\ payment* OR *compromise*))`

**Comment by bm11100** [comment]
Hey @austinsonger! Happy to help with the query. Do you have any sample (redacted) logs that I can view to assist?

**Comment by bm11100** [comment]
Hey @austinsonger. I created the initial rule [here](https://github.com/elastic/detection-rules/pull/1068). My sample logs don't include `New-InboxRule`. Are you able to provide a json with the parameters `o365.audit.Parameters` mentioned above so I can confirm? Thanks

**Comment by austinsonger** [comment]
> Hey @austinsonger. I created the initial rule [here](https://github.com/elastic/detection-rules/pull/1068). My sample logs don't include `New-InboxRule`. Are you able to provide a json with the parameters `o365.audit.Parameters` mentioned above so I can confirm? Thanks

I will get on this today.

**Comment by bm11100** [comment]
> > Hey @austinsonger. I created the initial rule [here](https://github.com/elastic/detection-rules/pull/1068). My sample logs don't include `New-InboxRule`. Are you able to provide a json with the parameters `o365.audit.Parameters` mentioned above so I can confirm? Thanks
> 
> I will get on this today.

Any update on this @austinsonger? Else, we may have to push this rule back to the 7.14 release.

**Comment by bm11100** [comment]
Merged. Can open a new issue if we want to tweak the parameters.
