### ISSUE TITLE
[New Rule] Amazon AWS EC2 Instance Connect was used

### ISSUE THREAD

**Issue by aarju** [elastic/detection-rules#965]
## Description

Detect when the AWS `EC2 Instance Connect` interface was used to connect to an EC2 instance. In some orgs this will be the normal way that an administrator accesses a system, but in many orgs the Instance Connect interface is never used. In situations like this the SOC team would want to get an alert when this interface is used.

### Target indexes

`filebeat-*` 

### Additional requirements

Filebeat used to collect cloudtrail via the aws module. `event.module:aws`

### Platforms

aws

### Tested ECS Version
x.x.x

### Query
`event.provider :"ec2-instance-connect.amazonaws.com" AND event.module : "aws"`

### References
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitor-with-cloudtrail.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html

**Comment by bm11100** [comment]
This one is interesting and I think it's worth adding to our list of rules. We can add in the API call and successful outcomes as well. I wonder if there is anything else we can key in on like anomalous user agents or source addresses. 
```
event.dataset:aws.cloudtrail and event.provider:"ec2-instance-connect.amazonaws.com" and event.action:SendSSHPublicKey and event.outcome:success
```

**Comment by terrancedejesus** [comment]
Closing this as complete. Ref: https://github.com/elastic/detection-rules/pull/3634
