### ISSUE TITLE
[FR] New and tuned rules leveraging new threshold rule features

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#977]
related to #975 
related to https://github.com/elastic/kibana/pull/92667

New features:
* can specify multiple `threshold` fields
* can define a `cardinality.field` and `cardinality.value` to limit to unique results against in a specified field

We should review all `threshold` rules to see how the new features could add value. Additionally, we should start thinking about new opportunities for detections as well.

**Comment by w0rk3r** [comment]
This one looks ready to be closed to me as we did multiple tunings, and we are using these features in a some rules.
